- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
- Typos in BlocBuilder fixed (analagous -> analogous)
- `FlutterError` added when a BlocProvider does not exist above current context
None
> fix typos in flutter_bloc docs and add FlutterError when BlocProvider not found

- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
update `BlocProvider` to use `ancestorInheritedElementForWidgetOfExactType` instead of `ancestorWidgetOfExactType`
None
> BlocProvider use ancestorInheritedElementForWidgetOfExactType

- packages/flutter_bloc/lib/src/bloc_builder.dart
**READY**
NO
According to https://www.dartlang.org/guides/language/effective-dart/design#dont-use-the-legacy-typedef-syntax we should not use the legacy typedef syntax
None
None
None
* none, as the new syntax typedef syntax is a superset of the old one.
> Replaced legacy typedef syntax: BlocWidgetBuilder

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/pubspec.yaml
- performance_tests/flutter_bloc/bloc_provider/README.md
**READY**
NO
- Address #56
- `BlocProvider` performance enhancement to use `InheritedWidget` directly without `StatefulWidget` wrapper.
None
> BlocProvider performance enhancements (v0.5.1)

- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/counter/counter.dart
- packages/bloc/test/helpers/counter/counter_exception_bloc.dart
**READY**
NO
Exceptions thrown in `mapEventToState` should not break the `Stream`
None
> Handle Exceptions in MapEventToState

- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_delegate.dart
- packages/bloc/test/bloc_delegate_test.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/counter/on_error_bloc.dart
**READY**
YES, this requires BlocDelegate to register a `onError` handler. Should this be optional?
This allows a library user to hook into exceptions thrown during even processing.
https://github.com/felangel/bloc/pull/97
> User can hook into bloc exceptions

- docs/_coverpage.md
- docs/coreconcepts.md
- packages/bloc/CHANGELOG.md
- packages/bloc/pubspec.yaml
- packages/bloc/test/bloc_delegate_test.dart
**READY**
NO
- `onError` added to `Bloc`
- `onError` added to `BlocDelegate`
#98 
#97 
None
> bloc v0.9.0 rc

- packages/angular_bloc/pubspec.yaml
- packages/bloc/CHANGELOG.md
- packages/bloc/pubspec.yaml
- packages/flutter_bloc/pubspec.yaml
- performance_tests/flutter_bloc/bloc_builder/pubspec.yaml
- performance_tests/flutter_bloc/bloc_provider/pubspec.yaml
**READY**
NO
Restrict `rxdart` version to `<0.21.0` due to breaking changes. (#104)
None
> restrict rxdart to < 0.21.0

- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/pubspec.yaml
- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/pubspec.yaml
**READY**
NO
Update `flutter_bloc` and `angular_bloc` to require `bloc` `^0.9.3` (#106, #104)
Branch | PR
master | #105 
None
> Update flutter_bloc and angular_bloc to require bloc v0.9.3

- packages/bloc/CHANGELOG.md
- packages/bloc/lib/src/bloc.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/counter/counter_bloc.dart
**READY**
NO
- Calls to `dispatch` after after `dispose` has been called trigger `onError` in the `Bloc` and `BlocDelegate`.
- version bump to `0.9.4`
None
> bloc v0.9.4

- docs/architecture.md
**READY**
NO
Add new content about bloc state subscription to architecture section in documentation.
> add bloc state subscription to architecture section

- packages/bloc/CHANGELOG.md
- packages/bloc/README.md
- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/bloc_delegate_test.dart
- packages/bloc/test/helpers/async/async_bloc.dart
- packages/bloc/test/helpers/complex/complex_bloc.dart
- packages/bloc/test/helpers/counter/counter_bloc.dart
- packages/bloc/test/helpers/counter/counter_exception_bloc.dart
- packages/bloc/test/helpers/counter/on_error_bloc.dart
- packages/bloc/test/helpers/simple/simple_bloc.dart
**READY**
YES
`mapEventToState` function signature changed (#161)
- `Stream<S> mapEventToState(S currentState, E event)` -> `Stream<S> mapEventToState(E event)`
- `currentState` can be accessed as a property of the bloc and no longer needs to be an argument.
None
> bloc v0.11.0

- extensions/intellij/intellij_generator_plugin/build.gradle
- extensions/intellij/intellij_generator_plugin/gradle/wrapper/gradle-wrapper.properties
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocAction.kt
- extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- Explicitly specify the `idea-version` in the `plugin.xml` to address #227 
- Also addresses #158 by allowing users to generate a bloc regardless of the current directory.
None
> Fix IntelliJ Plugin Compatibility Issues

- packages/flutter_bloc/lib/flutter_bloc.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_listener_tree.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/bloc_provider_tree.dart
- packages/flutter_bloc/test/bloc_listener_test.dart
- packages/flutter_bloc/test/bloc_listener_tree_test.dart
**READY**
NO
Adding a `BlocListenerTree` widget to avoid nested `BlocListener`
Just use this flutter App example :
```dart
import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
// This widget is the root of your application.
@override
return MaterialApp(
title: 'Bloc Listener Text',
theme: ThemeData(
primarySwatch: Colors.blue,
),
home: TestPage(),
);
}
}
class TestPage extends StatelessWidget {
@override
BlocA blocA = BlocA();
BlocB blocB = BlocB();
Widget _widget = Center(
child: ButtonBar(
children: <Widget>[
FlatButton(
onPressed: () => blocA.dispatch(BlocATrigger()),
child: Text('A'),
),
FlatButton(
onPressed: () => …
```
> flutter_bloc : bloc_listener_tree

- packages/bloc/README.md
- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
**READY**
NO
When `dispose` is called on a `bloc` if events are pending, no new states are emitted and an exception is not passed to `onError`. (#257)
None
> dispose while events are pending does not emit new states or trigger onError

- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
**READY**
NO
Expose `Stream<Event` in bloc (similar to `state` stream). (#259)
None
> expose bloc event stream

- packages/bloc/README.md
- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_delegate.dart
- packages/bloc/test/bloc_delegate_test.dart
- packages/bloc/test/bloc_test.dart
**READY**
YES
`onTransition` and `onError` in `BlocDelegate` will now have a reference to the given `bloc`. (#259)
`BlocDelegate` implementations need to be updated.
> Include bloc in BlocDelegate onTransition and onError

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_builder_test.dart
**READY**
NO
- Fix null previousState in BlocBuilder condition (#328)
None
> Fix null previousState in BlocBuilder condition

- packages/bloc/CHANGELOG.md
- packages/bloc/lib/src/bloc.dart
- packages/bloc/pubspec.yaml
**READY**
NO
- Deprecate the bloc `event` stream API (#326)
None
> deprecate bloc event stream

- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/bloc_provider_tree_test.dart
**READY**
YES
Update `BlocProvider` to handle initializing and disposing the bloc to eliminate the need to create a `StatefulWidget` just to manage a bloc (#84).
This PR allows us to go from:
```dart
class MyApp extends StatefulWidget {
State<MyApp> createState() => _MyAppState();
}
class _MyAppState extends State<MyApp> {
MyBloc _myBloc;
@override
initState() {
super.initState();
_myBloc = MyBloc();
}
@override
return BlocProvider(
bloc: _myBloc,
child: MyPage(),
);
}
@override
dispose() {
_myBloc.dispose();
super.dispose();
}
}
```
To this:
```dart
class MyApp extends StatelessWidget {
@override
return BlocProvider(
builder: (BuildContext context) => MyBloc(),
child: MyPage(),
);
}
}
```
- Breaking change which …
> Update BlocProvider to automatically dispose blocs

- packages/flutter_bloc/README.md
- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
YES
- Update `BlocProvider` to expose `dispose` method to allow full control over when a bloc should be disposed.
This PR allows us to go from:
```dart
class MyApp extends StatefulWidget {
State<MyApp> createState() => _MyAppState();
}
class _MyAppState extends State<MyApp> {
MyBloc _myBloc;
@override
initState() {
super.initState();
_myBloc = MyBloc();
}
@override
return BlocProvider(
bloc: _myBloc,
child: MyPage(),
);
}
@override
dispose() {
_myBloc.dispose();
super.dispose();
}
}
```
To this:
```dart
class MyApp extends StatelessWidget {
@override
return BlocProvider(
builder: (BuildContext context) => MyBloc(),
dispose: (BuildContext context, MyBloc bloc) => bloc.dispose(),
child: MyPage(),
);
}
}
``` …
> Expose dispose method on BlocProvider

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/README.md
- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
YES
Go from:
```dart
BlocProvider(
builder: (context) => CounterBloc(),
dispose: (context, bloc) => bloc.dispose(),
child: Container(),
)
```
to
```dart
BlocProvider(
builder: (context) => CounterBloc(),
child: Container(),
)
```
And from:
```dart
BlocProvider(
builder: (context) => CounterBloc(),
dispose: (context, bloc) => null,
child: Container(),
)
```
to
```dart
BlocProvider(
builder: (context) => CounterBloc(),
dispose: false,
child: Container(),
)
```
Breaking API Change to `BlocProvider` which will be released in flutter_bloc v0.17.0
> Update BlocProvider to Automatically Dispose Bloc

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/README.md
- packages/flutter_bloc/lib/flutter_bloc.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_listener_tree.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/bloc_provider_tree.dart
- packages/flutter_bloc/lib/src/copyable.dart
- packages/flutter_bloc/lib/src/immutable_provider.dart
- packages/flutter_bloc/lib/src/immutable_provider_tree.dart
- packages/flutter_bloc/lib/src/tree_buildable.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/bloc_provider_tree_test.dart
- packages/flutter_bloc/test/immutable_provider_test.dart
- packages/flutter_bloc/test/immutable_provider_tree_test.dart
**READY**
NO
Allow developers to provide immutable values, such as repositories, throughout the widget tree (#354).
- `ImmutableProvider`
- `ImmutableProviderTree`
- `BlocProvider`
- `BlocProviderTree`
- `BlocListener`
- `BlocListenerTree`
None
> Expose ImmutableProvider and ImmutableProviderTree

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_listener_test.dart
- packages/flutter_bloc/test/bloc_listener_tree_test.dart
**READY**
NO
Revert changes introduced in #214 in order to guarantee that `BlocListener` is only called on state changes (addresses #368).
branch | PR
master | #214 
Revert changes introduced in #214
> BlocListener should only be called on state changes

- packages/flutter_bloc/lib/src/bloc_provider.dart
**READY**
NO
- Include `dispose` in `BlocProvider` `copyWith` (addresses #376)
None
> fix BlocProvider copyWith()

- packages/flutter_bloc/README.md
- packages/flutter_bloc/lib/flutter_bloc.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/multi_bloc_listener.dart
- packages/flutter_bloc/test/multi_bloc_listener_test.dart
**HOLD**
YES
branch | PR
provider | [link](https://github.com/felangel/bloc/pull/385)
> Renamed BlocListenerTree to MultiBlocListener

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_listener_test.dart
**Development**
NO
Add an optional `condition` property to `BlocListener` which takes the `previousState` and `currentState` as arguments and must return a `bool` which determines whether or not call listener
```dart
import 'package:equatable/equatable.dart';
enum SessionState { notInitialized, signedIn, notSignedIn }
class AuthState extends Equatable {
final bool isLoading;
final SessionState sessionState;
AuthState(this.isLoading, this.sessionState)
: super([isLoading, sessionState]);
}
```
```dart
...
@override
Stream<AuthState> mapEventToState(AuthEvent event) async*{
if (event == AuthEvent.SignOut) {
yield currentState.copyWith(true);
await _signOut();
yield currentState.copyWith(false, SessionState.notSignedIn);
}
}
...
```
```dart
...
@override …
```
> Add optional condition to BlocListener

- packages/flutter_bloc/README.md
- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_bloc_listener.dart
- packages/flutter_bloc/test/bloc_builder_test.dart
- packages/flutter_bloc/test/bloc_listener_test.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/multi_bloc_listener_test.dart
- packages/flutter_bloc/test/multi_bloc_provider_test.dart
**READY**
YES
Instead of having to manually do the bloc lookup for `BlocBuilder` and `BlocListener` whenever the bloc is not specified, the default behavior will be to lookup the bloc via `BlocProvider` automatically.
```dart
BlocBuilder(
bloc: BlocProvider.of<CounterBloc>(context),
builder: (BuildContext context, int state) { ... },
) 
```
```dart
BlocBuilder<CounterBloc, int>(
builder: (context, state) { ... },
)
```
```dart
BlocListener(
bloc: BlocProvider.of<CounterBloc>(context),
listener: (int previousState, int currentState) => { ... },
)
```
```dart
BlocListener<CounterBloc, int>(
listener: (previousState, currentState) => { ... },
)
```
It is now possible to provide and access a bloc within the same `build`
```dart
@override
return …
```
> flutter_bloc v0.20.0-rc

- extensions/vscode/snippets/snippets.json
#Status
**READY**
NO
Prevent implicit `dynamic` in the generated BloC code as it violates a commonly used dart analyzer rule: `implicit-dynamic: false`.
Making `dynamic` implicit encourages using it and makes it harder to find where it's being used.
> Prevent implicit dynamic

- packages/bloc/CHANGELOG.md
- packages/bloc/README.md
- packages/bloc/lib/src/bloc.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/complex/complex_bloc.dart
- packages/bloc/test/helpers/complex/complex_event.dart
- packages/bloc/test/helpers/complex/complex_state.dart
- packages/bloc/test/helpers/counter/counter_bloc.dart
- packages/bloc/test/transition_test.dart
**READY**
YES
- Removed Bloc `event` Stream ([#326](https://github.com/felangel/bloc/issues/326))
- Renamed `transform` to `transformEvents`
- Added `transformStates` ([#382](https://github.com/felangel/bloc/issues/382))
```dart
@override
Stream<State> transformEvents(events, next) {
return (events as Observable<Event>).switchMap(next);
}
```
```dart
@override
Stream<State> transformEvents(events, next) {
return super.transformEvents(
(events as Observable<Event>).debounceTime(
Duration(milliseconds: 300),
),
next,
);
}
```
```dart
@override
Stream<State> transformStates(states) {
return (states as Observable<State>)
.debounceTime(Duration(seconds: 100));
}
```
Breaking changes to bloc which will be included in v0.15.0
> Add transformStates to bloc

- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_delegate_test.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/async/async_bloc.dart
- packages/bloc/test/helpers/counter/counter_bloc.dart
- packages/bloc/test/helpers/counter/counter_error_bloc.dart
- packages/bloc/test/helpers/counter/counter_exception_bloc.dart
**READY**
YES
- Addresses #558 
```dart
bloc.state.listen(print);
```
becomes
```dart
bloc.listen(print);
```
```dart
bloc.currentState
```
becomes
```dart
bloc.state
```
- Breaking change to the bloc API which will require a major version bump + updates to `flutter_bloc` and `angular_bloc`
> Refactor Bloc to extend Stream<State>

- packages/bloc/README.md
- packages/bloc/example/main.dart
- packages/bloc/example/pubspec.yaml
- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_delegate_test.dart
- packages/bloc/test/deprecated_bloc_test.dart
**READY**
NO
- Addresses #558 
```dart
bloc.dispatch
```
becomes
```dart
bloc.add
```
And
```dart
bloc.dispose
```
becomes
```dart
bloc.close
```
- `dispatch` and `dispose` are deprecated and will be removed in the next major version
> Bloc implements Sink<Event>

- examples/angular_counter/lib/src/counter_page/counter_bloc.dart
- examples/angular_counter/lib/src/counter_page/counter_page_component.dart
- examples/angular_counter/pubspec.yaml
- examples/github_search/angular_github_search/lib/src/search_form/search_bar/search_bar_component.dart
- examples/github_search/angular_github_search/lib/src/search_form/search_form_component.dart
- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/README.md
- packages/angular_bloc/example/example.dart
- packages/angular_bloc/lib/src/pipes/bloc_pipe.dart
- packages/angular_bloc/pubspec.yaml
- packages/angular_bloc/test/bloc_pipe_test.dart
**READY**
YES
- Update `angular_bloc` to use `bloc ^v0.16.0`
- Breaking changes which will be introduced in `angular_bloc v0.11.0`
> update angular_bloc to use bloc v0.16.0

- examples/flutter_firebase_login/lib/main.dart
Add line:
`WidgetsFlutterBinding.ensureInitialized();`
to `lib/main.dart` `main()` to ensure plugin available in the flutter_firebase_login example.
See https://github.com/felangel/hydrated_bloc/issues/17
**READY** 
NO
See above
Unknown
branch | PR
N/A
N/A
Outline the steps to test or reproduce the PR here.
Clone and test flutter_firebase_login example.
Shows blank screen without change.
N/A
*
> [flutter_firebase_login] add WidgetsFlutterBinding.ensureInitialized()

- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/counter/counter.dart
- packages/bloc/test/helpers/counter/on_transition_error_bloc.dart
**READY**
NO
- Exceptions thrown in `onTransition` should be passed to `onError` and should not break bloc functionality (#641)
None
> Handle exceptions in onTransition

- packages/bloc/README.md
- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
**READY**
YES
Previously calling `close` on a bloc would immediately ignore all pending events. This pull request would change the behavior so that calling `close` would prevent new events from being processed while allowing pending events to finish being processed (see conversation in #611 and #639 for more details).
- Breaking change in bloc
> update bloc.close to process pending events

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/example/main.dart
- packages/bloc_test/lib/bloc_test.dart
- packages/bloc_test/lib/src/mock_bloc.dart
- packages/bloc_test/pubspec.yaml
- packages/bloc_test/test/emits_exactly_test.dart
- packages/bloc_test/test/mock_bloc_test.dart
**READY**
NO
- Add `MockBloc` to `bloc_test` in order to simplify bloc mocks (addresses #636)
Example:
```dart
class MockCounterBloc extends Mock implements CounterBloc {}
void main() {
test('...', () {
final bloc = MockCounterBloc();
bloc.skip(1); // throws exception
});
}
```
```dart
class MockCounterBloc extends MockBloc<CounterEvent, int> implements CounterBloc {}
void main() {
test('...', () {
final bloc = MockCounterBloc();
bloc.skip(1); // is stubbed automatically to return an empty stream
});
}
```
- `MockBloc` would also allow for specialized mocking functionality moving forward.
- New functionality to be included in bloc_test v2.1.0
> Add MockBloc to bloc_test

- .gitignore
- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_builder_test.dart
- packages/flutter_bloc/test/bloc_listener_test.dart
**READY**
NO
- Patch `BlocBuilder` and `BlocListener` condition to be called with the previous used state of the bloc rather than the previous state of the bloc (#671)
None
> [Patch] flutter_bloc condition (previous state)

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/lib/src/emits_exactly.dart
- packages/bloc_test/pubspec.yaml
- packages/bloc_test/test/bloc_test_test.dart
- packages/bloc_test/test/emits_exactly_test.dart
- packages/bloc_test/test/helpers/complex_bloc.dart
- packages/bloc_test/test/helpers/helpers.dart
**READY**
NO
- `bloc_test` enhance `emitsExactly` to accept an `Iterable<Matcher>` (#695)
- Backward compatible feature which will be included in `bloc_test` v2.2.0
> bloc_test emitsExactly supports Iterable<Matcher>

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/README.md
- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_repository_provider.dart
- packages/flutter_bloc/lib/src/repository_provider.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/multi_bloc_provider_test.dart
- packages/flutter_bloc/test/multi_repository_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
- Deprecate `builder` in favor of `create` for `BlocProvider` and `RepositoryProvider` to align with the [provider](https://github.com/rrousselGit/provider/issues/259) API. 
- Deprecation of `builder` which will be introduced in `flutter_bloc` v2.1.0
- `builder` will be removed in `flutter_bloc` v3.0.0
> Deprecate builder for create in BlocProvider/RepositoryProvider

- docs/_sidebar.md
- docs/blocnamingconventions.md
**READY**
NO
- Add bloc naming conventions to documentation
None
> add bloc naming conventions to docs

- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/test/bloc_builder_test.dart
- packages/flutter_bloc/test/bloc_listener_test.dart
**READY**
YES
- Revert `condition` behavior in `BlocBuilder` and `BlocListener` to use previous state of bloc rather than previously used state in UI (#709)
- Addresses #730 since code is no longer redundant
- Reverts #671 and #678; will be included in v3.0.0
> revert condition to previous behavior

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/lib/src/emits_exactly.dart
- packages/bloc_test/test/bloc_test_test.dart
- packages/bloc_test/test/emits_exactly_test.dart
- packages/bloc_test/test/helpers/debounce_counter_bloc.dart
- packages/bloc_test/test/helpers/helpers.dart
**READY**
NO
- Add `duration` to `emitsExactly` (https://github.com/felangel/bloc/issues/726)
- Add `wait` to `blocTest` (https://github.com/felangel/bloc/issues/726)
None
> add wait to blocTest and duration to emitsExactly

- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/repository_provider.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/multi_bloc_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
- Expose `lazy` property on `BlocProvider` and `RepositoryProvider`
- Bump `provider` version to `^4.0.1` ([#748](https://github.com/felangel/bloc/issues/748))
- Changes included in v3.1.0
> Expose lazy parameter on RepositoryProvider and BlocProvider

- docs/blocnamingconventions.md
**READY**
NO
This pull request fixes a small typo in the docs.
> Fix typo in naming conventions docs

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/pubspec.yaml
- packages/bloc_test/test/bloc_test_test.dart
**READY**
NO
- Enable `blocTest` to add more than one asynchronous event at a time ([#724](https://github.com/felangel/bloc/issues/724))
- https://github.com/felangel/bloc/pull/756
- Fix which will be included in v3.0.1
> bloc_test v3.0.1

- packages/flutter_bloc/lib/flutter_bloc.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_bloc_listener.dart
- packages/flutter_bloc/lib/src/multi_bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_repository_provider.dart
- packages/flutter_bloc/lib/src/repository_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/multi_bloc_listener_test.dart
- packages/flutter_bloc/test/multi_bloc_provider_test.dart
- packages/flutter_bloc/test/multi_repository_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
As a developer, I shouldn't need to provider the Bloc/Repository type explicitly when using `MultiBlocProvider`, `MultiBlocListener`, or `MultiRepositoryProvider`.
```dart
MultiBlocProvider(
providers: [
BlocProvider<BlocA>(
create: (_) => BlocA(),
),
BlocProvider<BlocB>(
create: (_) => BlocB(),
),
child: MyChild(),
);
```
Instead, I should be able to omit the type and have it be correctly inferred:
```dart
MultiBlocProvider(
providers: [
BlocProvider(
create: (_) => BlocA(),
),
BlocProvider(
create: (_) => BlocB(),
),
child: MyChild(),
);
```
- Enhancement to be included in `flutter_bloc 3.2.0`
> Fix MultiBlocProvider and MultiRepositoryProvider type inference

- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_state.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_state.dart.template
- extensions/vscode/src/templates/bloc-state.template.ts
- extensions/vscode/src/templates/bloc.template.ts
**READY**
NO
Currently, the extension templates don't follow the recently added naming conventions. This PR fixes initial state naming.
> Update templates to follow initial state naming convention

- docs/flutterbloccoreconcepts.md
- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/README.md
- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/repository_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
- Fix type inference for: `MultiBlocProvider`, `MultiRepositoryProvider`, `MultiBlocListener` (#773)
```dart
MultiBlocProvider(
providers: [
BlocProvider<BlocA>(create: (_) => BlocA()),
BlocProvider<BlocB>(create: (_) => BlocB()),
],
)
```
```dart
MultiBlocProvider(
providers: [
BlocProvider(create: (_) => BlocA()),
BlocProvider(create: (_) => BlocB()),
],
)
```
- Fix swallowed exceptions within `BlocProvider` and `RepositoryProvider` (#807, #817)
- Add `BlocProviderExtension` and `RepositoryProviderExtension` on `BuildContext` (#608)
```dart
// with extension
final bloc = context.bloc<BlocA>();
// without extension
final bloc = BlocProvider.of<BlocA>();
```
- Non-Breaking Changes which will be included in `flutter_bloc v3.2.0`
> Add extensions to BlocProvider & RepositoryProvider + Fix Provider Error Handling

- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/simple/simple_bloc.dart
**READY**
NO
- Add tests to bloc to ensure multiple subscribers always get the latest emitted state (#836)
- None
> Add Multiple Subscription Tests to Bloc

- .github/DOCS_ISSUE_TEMPLATE.md
- .github/workflows/docs.yaml
**IN DEVELOPMENT**
NO
This PR adds a new workflow, which adds automatically a new issue on every source docs update.
Multiple assignees seem to fail, so for now, only I am assigned and we can add other guys later. See https://github.com/JasonEtco/create-an-issue/issues/41
> Add Docs workflow

- examples/flutter_login/test/unit/authentication/authentication_bloc_test.dart
- examples/flutter_login/test/unit/login/login_bloc_test.dart
- examples/flutter_weather/test/blocs/weather_bloc_test.dart
- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/example/main.dart
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/lib/src/emits_exactly.dart
- packages/bloc_test/test/bloc_test_test.dart
- packages/bloc_test/test/emits_exactly_test.dart
**READY**
YES
Closes #910
**Before:**
```dart
blocTest(
'...',
build: () => MyBloc(),
...
);
```
**After:**
```dart
blocTest(
'...',
build: () async => MyBloc(),
...
);
```
**Before:**
```dart
blocTest(
build: () async => CounterBloc(),
act: (bloc) => bloc.add(CounterEvent.increment),
expect: [0, 1],
);
```
**After:**
```dart
blocTest(
build: () async => CounterBloc(),
act: (bloc) => bloc.add(CounterEvent.increment),
expect: [1],
);
```
```dart
blocTest(
build: () async => CounterBloc(),
act: (bloc) => bloc.add(CounterEvent.increment),
skip: 0,
expect: [0, 1],
);
```
**Before:**
```dart
blocTest(
...
verify: () async { ... }
);
```
**After:**
```dart
blocTest(
...
verify: (bloc) async { ... }
);
```
**Before:**
```dart
test('emits [0, 1] when CounterEvent.increment is added', () async { …
```
> bloc_test v4.0.0

- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
**READY**
NO
The `stacktrace` was always `null` in `onError` methods, I have fixed it and also fixed the tests since they failed after the change.
> Fix stacktrace of onError methods

- docs/cs/flutterbloccoreconcepts.md
- docs/es/flutterbloccoreconcepts.md
- docs/flutterbloccoreconcepts.md
- docs/pt-br/flutterbloccoreconcepts.md
- docs/ru/flutterbloccoreconcepts.md
- docs/zh-cn/flutterbloccoreconcepts.md
**READY**
NO
Update docs with the new `create` parameter of `RepositoryProvider` class, instead of deprecated `builder` one.
> Update docs with create parameter of RepositoryProvider

- packages/flutter_bloc/lib/src/bloc_provider.dart
**READY**
NO
Github's syntax highlighting is broken starting from [this line](https://github.com/felangel/bloc/blob/3112783f581b0e1966b544b31cd74f473ea96bf9/packages/flutter_bloc/lib/src/bloc_provider.dart#L70).
> Fix syntax highlighting in bloc_provider.dart

- examples/flutter_firebase_login/lib/authentication_bloc/authentication_bloc.dart
I noticed that in the for state mapping for AppStarted event, the Try Catch block wraps the  _userRepository.isSignedIn(); 
This seems unnecessary since that repository just calls firebase.instance.currentUser() under the hood. The method only returns a Firebase User or a null value.
**READY**
NO
Remove unnecessary try catch block in firebase login example
Nill
Nill
* simplify firebase login example
> Remove try catch block in Auth Bloc in Firebase Login example

- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/pubspec.yaml
- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/pubspec.yaml
- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/pubspec.yaml
**READY**
NO
- Update to package:bloc v4.0.0-dev.2
- package:angular_bloc
- package:flutter_bloc
- package:bloc_test
- Release candidate for `angular_bloc`, `bloc_test`, and `flutter_bloc` packages
> update angular_bloc, bloc_test, and flutter_bloc to bloc v4.0.0-dev.2

- packages/bloc/CHANGELOG.md
- packages/bloc/lib/src/bloc.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/helpers/counter/counter_bloc.dart
- packages/bloc/test/helpers/counter/on_error_bloc.dart
- packages/bloc/test/helpers/counter/on_exception_bloc.dart
- packages/bloc/test/helpers/counter/on_transition_error_bloc.dart
**READY**
YES
- Add `mustCallSuper` to `onEvent`, `onTransition`, and `onError`
Breaking change which will be included in v4.0.0
> add mustCallSuper to onEvent, onTransition, and onError

- packages/bloc/CHANGELOG.md
- packages/bloc/README.md
- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_delegate.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/bloc_delegate_test.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/helpers/counter/counter_bloc.dart
- packages/bloc/test/helpers/counter/on_error_bloc.dart
- packages/bloc/test/helpers/counter/on_exception_bloc.dart
- packages/bloc/test/helpers/counter/on_transition_error_bloc.dart
**READY**
YES
- In debug mode, a `BlocUnhandledErrorException` will be thrown to make errors apparent while in development.
- In release mode, the bloc's behavior will remain unchanged.
As a result, with these changes it becomes important to call `super.onError` last when overriding `onError` in order to ensure the custom `onError` code is executed.
- Breaking changes which will be published in bloc v4.0.0-dev.4
> surface unhandled bloc errors in debug mode

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/lib/src/when_listen.dart
- packages/bloc_test/test/when_listen_test.dart
**READY**
NO
- Enable `whenListen` to stub the bloc state property as well as the state stream to ensure a consistent behavior and eliminate the need to have an additional `when`.
Previously, the following didn't guarantee that if you called `counterBloc.state` it would return 3. You'd need to stub the state separately.
```dart
whenListen(counterBloc, Stream.fromIterable([0, 1, 2, 3]);
print(counterBloc.state); // null
// we'd need to stub the state separately like...
when(counterBloc.state).thenReturn(3);
```
Now, `whenListen` will handle keeping the two in sync:
```dart
whenListen(counterBloc, Stream.fromIterable([0, 1, 2, 3]);
print(counterBloc.state); // 3
```
- Pending approval will be merged and published in `bloc_test v5.1.0`.
> bloc_test: whenListen stubs state as well

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/lib/src/when_listen.dart
- packages/bloc_test/pubspec.yaml
- packages/bloc_test/test/bloc_test_test.dart
- packages/bloc_test/test/helpers/exception_counter_bloc.dart
- packages/bloc_test/test/helpers/helpers.dart
- packages/bloc_test/test/when_listen_test.dart
**READY**
NO
- Closes #1122 
- Add optional `errors` to `blocTest` to enable developers to write expectations against unhandled exceptions thrown in the bloc throughout the course of the test.
```dart
blocTest(
'CounterBloc throws Exception when null is added',
build: () async => CounterBloc(),
act: (bloc) => bloc.add(null),
errors: [
isA<Exception>(),
]
);
```
- Enable `whenListen` to stub the bloc state property as well as the state stream to ensure a consistent behavior and eliminate the need to have an additional `when`.
Previously, the following didn't guarantee that if you called `counterBloc.state` it would return 3. You'd need to stub the state separately.
```dart
whenListen(counterBloc, Stream.fromIterable([0, 1, 2, 3]);
print(counterBloc.state); // null
// we'd need to stub the …
```
> bloc_test v5.1.0

- examples/angular_counter/lib/src/counter_page/counter_page_component.css
- examples/angular_counter/lib/src/counter_page/counter_page_component.dart
- examples/angular_counter/lib/src/counter_page/counter_page_component.html
- examples/angular_counter/pubspec.yaml
- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/README.md
- packages/angular_bloc/pubspec.yaml
**READY**
YES
closes #1174 
- Update `angular_bloc` to `angular_dart: ^6.0.0-alpha+1`
- updates which will be released pending merge in v5.0.0-dev.1
> angular_bloc v5.0.0-dev.1

- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
If BLoC depends on something injected with `Provider` and it's **not** lazily created, the exception is wrapped into `FlutterError` and provides description related to `BlocProvider`. That is wrong and confusing for the client as the problem is not in missing BLoC.
This PR fixes the error by checking the `valueType` of the thrown exception.
> flutter_bloc: Fix provider exception

- .gitignore
- README.md
- packages/bloc/CHANGELOG.md
- packages/bloc/README.md
- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_observer.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/bloc_observer_test.dart
- packages/bloc/test/bloc_test.dart
**READY**
NO
Bloc to implement `EventSink` rather than `Sink` which exposes `addError` for a more intuitive, friendly API to handle exceptions within a bloc.
Currently you have to `rethrow`:
```dart
Stream<MyState> mapEventToState(MyEvent event) async* {
try {
await someOperation();
} on SomeSpecificException catch (_) {
yield SomeSpecificFailureState();
rethrow; // currently necessary to propagate error to `onError` in `BlocObserver`.
}
}
```
Or `throw` when using `Either`:
```dart
yield* either.fold(
(failure) async * {
yield FailureState(failure);
throw failure;
}, 
(data) => ...
)
```
It is not immediately clear/obvious that (re)throwing bubbles the exception up to `onError` and can be improved:
```dart
Stream<MyState> mapEventToState(MyEvent event) async* {
try {
await …
```
> feat(bloc): addError

- docs/_snippets/recipes_flutter_bloc_access/anonymous_route_access/main.dart.md
**READY**
NO
In the Anonymous Route Access section of the Bloc Access Recipe, the App Widget BlocProvider should have `HomePage()` as its child instead of the `CounterPage()`.  
This is correctly coded in the relevant [gist](https://gist.github.com/felangel/92b256270c5567210285526a07b4cf21) but not in the `main.dart` file of this example.
*  None
- Introduction
- Core Concepts
- Tutorials
- Flutter
- AngularDart
- Flutter + AngularDart
- Recipes
- Flutter
- Tools
- Extensions
> Fixed doc error in the bloc access recipe

- docs/_snippets/flutter_weather_tutorial/integrate_gradient_container.dart.md
- docs/_snippets/flutter_weather_tutorial/settings.dart.md
**READY**
NO
While I was following the weather app tutorial I've noticed there are two instances of blocs in the tutorial that aren't used. In the real weather app codebase, those lines aren't present either, so I decided to remove them.
No PR's
No todos
No steps
No impact
> docs: removing unused lines of code in snippets

- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/README.md
- packages/angular_bloc/pubspec.yaml
**READY**
NO
- fix: update to `bloc ^5.0.1`
- fix: update to `angular_cubit ^0.1.0-dev.4`
> Fix/angular bloc v6.0.0 dev.6

- docs/_snippets/flutter_bloc_core_concepts/bloc_listener_explicit_bloc.dart.md
I think there is missing the child in this little example.
**READY**
NO
Little fix in flutter bloc listener documentation.
> docs: fix in snippets/bloc_listener_explicit_bloc

- .github/workflows/hydrated_bloc.yaml
- packages/hydrated_bloc/lib/src/hydrated_cubit.dart
- packages/hydrated_bloc/pubspec.yaml
- packages/hydrated_bloc/test/cubits/cubits.dart
- packages/hydrated_bloc/test/cubits/freezed_cubit.dart
- packages/hydrated_bloc/test/cubits/freezed_cubit.freezed.dart
- packages/hydrated_bloc/test/cubits/freezed_cubit.g.dart
- packages/hydrated_bloc/test/cubits/json_serializable_cubit.dart
- packages/hydrated_bloc/test/cubits/json_serializable_cubit.g.dart
- packages/hydrated_bloc/test/cubits/list_cubit.dart
- packages/hydrated_bloc/test/cubits/manual_cubit.dart
- packages/hydrated_bloc/test/cubits/simple_cubit.dart
- packages/hydrated_bloc/test/e2e_test.dart
- packages/hydrated_bloc/test/hydrated_bloc_test.dart
- packages/hydrated_bloc/test/hydrated_cubit_test.dart
**READY**
NO
- tests: add e2e tests for hydrated_bloc
- fix: error handling for `storage.write` 
@orsenkucher what do you think of these changes? I made a bunch of e2e tests with different (de)serialization approaches and they all seem to work fine without needing #1456.
The other thing that I noticed was we weren't awaiting `storage.write` and yet we still had it wrapped in a try/catch which didn't seem to make sense so I refactored to use `onError` instead. Let me know what you think.
> fix(hydrated_bloc): storage.write error + e2e

- docs/_snippets/testing/counter_bloc_test_bloc_test.dart.md
- docs/_snippets/testing/pubspec.yaml.md
- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/example/main.dart
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/pubspec.yaml
- packages/bloc_test/test/bloc_bloc_test_test.dart
- packages/bloc_test/test/blocs/async_counter_bloc.dart
- packages/bloc_test/test/blocs/blocs.dart
- packages/bloc_test/test/blocs/complex_bloc.dart
- packages/bloc_test/test/blocs/counter_bloc.dart
- packages/bloc_test/test/blocs/debounce_counter_bloc.dart
- packages/bloc_test/test/blocs/exception_counter_bloc.dart
- packages/bloc_test/test/blocs/instant_emit_bloc.dart
- packages/bloc_test/test/blocs/side_effect_counter_bloc.dart
- packages/bloc_test/test/cubit_bloc_test_test.dart
- packages/bloc_test/test/cubits/cubits.dart
- packages/bloc_test/test/cubits/instant_emit_cubit.dart
- packages/bloc_test/test/emits_exactly_test.dart
**READY**
YES
- **BREAKING**: `blocTest` make `build` synchronous
- fix: `blocTest` improve `wait` behavior when debouncing, etc...
- feat: `blocTest` do not require `async` on `act` and `verify`
The `build` parameter of `blocTest` was made asynchronous due to https://github.com/felangel/bloc/issues/910 in order to accommodate for cases where a bloc needed to be "prefilled" before executing act. This is no longer necessary because we can simply chain `emit` with the desired prefilled/seeded bloc state.
Previously if we had something like:
```dart
Future<void> prefillWithValidEmailAndPassword() async {
signInFormBloc.add(const SignInFormEvent.emailChanged('abc@gmail.com'));
signInFormBloc.add(const SignInFormEvent.passwordChanged('pazzwrd'));
await signInFormBloc.take(3).last;
}
blocTest( …
```
> fix: blocTest improvements

- packages/bloc/README.md
**READY**
NO
Docs were using `onChange` instead of `onError` when overriding `onError` in the Bloc and BlocObserver
> docs(bloc): fix onError BlocObserver usage in README

- docs/_snippets/flutter_weather_tutorial/simple_bloc_observer.dart.md
Change bloc to cubit in onError override, as per https://github.com/felangel/bloc/issues/1579#issuecomment-669449515
**READY**
YES
> docs: fix onError override in flutter weather tutorial

- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/test/bloc_builder_test.dart
**READY**
NO
- fix(flutter_bloc): BlocBuilder builder and buildWhen state synchronization fix (closes #1696)
- `builder` should not be triggered with state when `buildWhen` returns `false`
> fix(flutter_bloc): BlocBuilder builder and buildWhen state synchronization fix

- packages/bloc/lib/src/bloc.dart
> docs(bloc): small typo fix

- packages/bloc_test/README.md
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/test/bloc_bloc_test_test.dart
- packages/bloc_test/test/cubit_bloc_test_test.dart
**READY**
NO
- feat(bloc_test): add `seed` property to `blocTest`
```dart
blocTest<CounterBloc, int>(
'emits [42] when CounterEvent.increment is added and seed is 41',
build: () => CounterBloc(),
seed: 41
act: (bloc) => bloc.add(CounterEvent.increment),
expect: const <int>[42],
);
```
> feat(bloc_test): add seed property to blocTest

- examples/flutter_bloc_with_stream/lib/main.dart
- examples/flutter_complex_list/lib/list/view/list_page.dart
- examples/flutter_dynamic_form/lib/main.dart
- examples/flutter_form_validation/lib/main.dart
- examples/flutter_infinite_list/lib/posts/view/posts_list.dart
- examples/flutter_wizard/lib/main.dart
- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/README.md
- packages/flutter_bloc/example/lib/main.dart
- packages/flutter_bloc/lib/flutter_bloc.dart
- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_consumer.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_bloc_listener.dart
- packages/flutter_bloc/lib/src/multi_bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_repository_provider.dart
- packages/flutter_bloc/lib/src/repository_provider.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
- packages/hydrated_bloc/example/lib/main.dart
- packages/replay_bloc/example/lib/main.dart
**READY**
NO
- feat: add optional `listen` to `BlocProvider` and `RepositoryProvider`
- feat: add `context.select<T, R>(R Function(T value))` which allows widgets to listen to only a small part of the state of `T` (`R`).
- feat: add `context.watch<T>()` which allows widgets to listen to changes in the state of `T`
- feat: add `context.read<T>()` which allows widgets to access `T` without listening for changes
- deprecated: `context.bloc` in favor of `context.read` and `context.watch`
- deprecated: `context.repository` in favor of `context.read` and `context.watch`
- fix: rethrow `ProviderNotFoundException` from `RepositoryProvider` for external dependencies 
- docs: improve inline documentation for `BlocProvider` and `RepositoryProvider`
This closes #538 because `context.watch` with a …
> feat(flutter_bloc): context.read, context.watch, context.select

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/lib/src/bloc_consumer.dart
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_consumer_test.dart
**READY**
NO
- - fix: `BlocConsumer` does not respect `buildWhen` and results in unnecessary rebuilds (closes #1914)
> fix(flutter_bloc): remove context.watch from BlocConsumer

- examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
Fixes incorrect statement/doc-comment on what `Exception` is thrown on `logInWithGoogle`.
_This is my first PR! Hopefully I did this correctly. 👍🏻_
**READY**
NO
Was following the [firebase_login guide](https://bloclibrary.dev/#/flutterfirebaselogintutorial?id=repository) and noticed the doc comment was incorrect for the `logInWithGoogle()` method on `AuthenticationRepository`. It throws a `LogInWithGoogleFailure` exception and the comment says otherwise.
The comment was:
```dart
/// Throws a [LogInWithEmailAndPasswordFailure] if an exception occurs.
Future<void> logInWithGoogle() async {
```
The comment should be:
```dart
/// Throws a [LogInWithGoogleFailure] if an exception occurs.
Future<void> logInWithGoogle() async {
```
> Update authentication_repository.dart comment

- docs/fluttertodostutorial.md
**READY**
NO
Fixed a typo where 'an' is used before a noun starting with a consonant sound.
> docs: update fluttertodostutorial.md to fix typo

- CONTRIBUTING.md
READY
NO
The SimpleHTTPServer module has been merged into http.server in Python 3.0. The Python 3 equivalent of SimpleHTTPServer is http.server
> docs: [CONTRIBUTING.md] http.server instead of SimpleHTTPServer

- docs/zh-cn/gettingstarted.md
Add ZH-CN Translations to include changes from commit 900d2c2: add hydrated_bloc & replay_bloc to getting started overview
**READY**
NO
Add zh-cn translations to getting started overview: hydrated_bloc & replay_bloc
> docs: Add zh-cn translations getting started overview

- examples/github_search/common_github_search/lib/src/github_cache.dart
- examples/github_search/common_github_search/lib/src/github_client.dart
- examples/github_search/common_github_search/lib/src/github_repository.dart
- examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart
- examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_event.dart
- examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_state.dart
- examples/github_search/common_github_search/lib/src/models/github_user.dart
- examples/github_search/common_github_search/lib/src/models/search_result.dart
- examples/github_search/common_github_search/lib/src/models/search_result_error.dart
- examples/github_search/common_github_search/lib/src/models/search_result_item.dart
- examples/github_search/common_github_search/pubspec.yaml
- examples/github_search/flutter_github_search/ios/Flutter/Debug.xcconfig
- examples/github_search/flutter_github_search/ios/Flutter/Release.xcconfig
- examples/github_search/flutter_github_search/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- examples/github_search/flutter_github_search/lib/main.dart
- examples/github_search/flutter_github_search/lib/search_form.dart
- examples/github_search/flutter_github_search/pubspec.yaml
**READY**
NO
Migrate two examples to null safety.
> migrate github search to null safety

- packages/hydrated_bloc/README.md
READY
NO
Fix link pointing to old archived repo in README
> Fix link pointing to old archived repo

- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_consumer.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/test/bloc_builder_test.dart
- packages/flutter_bloc/test/bloc_consumer_test.dart
- packages/flutter_bloc/test/bloc_listener_test.dart
**READY**
NO
Fixes #2127
Closes https://github.com/felangel/bloc/pull/2181
To make a builder, listener or consumer update when the instance is changed we need a context dependency. However we can't use normal `context.watch` because BlocProvider uses a custom provider which also updates dependents when state is changed, therefore it would make `buildWhen` useless. Ideally we would reverse that, but that would also break compatibility. Adding another "normal" provider is also not an option since provider does not allow it and integrating special InheritedWidget is tricky.
There is a concept of "aspect" when it comes to dependencies. Provider exposes it by `context.select`, but it is a bit different   and it can't be used in `didUpdateDependencies`, but we can put it in build and use it to …
> fix(flutter_bloc): Add dependency to bloc instance for BlocBuilder/BlocListener/BlocConsumer

- packages/replay_bloc/lib/src/change_stack.dart
- packages/replay_bloc/lib/src/replay_bloc.dart
- packages/replay_bloc/lib/src/replay_cubit.dart
- packages/replay_bloc/test/blocs/counter_bloc.dart
- packages/replay_bloc/test/cubits/counter_cubit.dart
- packages/replay_bloc/test/replay_bloc_test.dart
- packages/replay_bloc/test/replay_cubit_test.dart
**READY**
NO
I added a `shouldReplay` method to `ReplayBloc` and `ReplayCubit`. The intention of this is described more in #2086, but basically, the idea is that a developer can override this method to filter out which states are saved in the undo/redo stack.
> feat(replay_bloc): filter which states are saved to the undo stack

- packages/bloc/README.md
**READY**
NO
I have updated this only paragraph which was confusing the users about `onChange` method: 
>State changes in cubit begin with predefined function calls which can use the emit method to output new states. onChange is called on each state change and contains the current and next state.
To
>State changes in cubit begin with predefined function calls which can use the emit method to output new states. **onChange is called right before a state change occurs and contains the current and next state.**
> docs(bloc): update `onChange` description in README

- examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart
- examples/flutter_firebase_login/test/sign_up/cubit/sign_up_cubit_test.dart
**READY**
NO
* Updates `SignUp Cubit` so that the `SignUp Button` will be enabled if both passwords match, regardless of the order in which the passwords were inputted. 
* closes #2179
> fix: sign up cubit password confirmation order

- extensions/intellij/README.md
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateEquatablePropsAction.kt
- extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
Adds a new option to the IntelliJ Generator menu, which generates `Equatable props` with defined class members.
For now, it looks like this
https://user-images.githubusercontent.com/67197047/124289277-6bf5bc80-db52-11eb-8baf-50987d843ed4.mp4
> feat(intelliJ): add Equatable props generator

- docs/flutterweathertutorial.md
Fix typo in flutterweathertutorial
**READY**
NO
Fix the name of the exceptiont thrown.
> docs(flutter_weather): fix typo in tutorial

- docs/_snippets/architecture/bloc_to_bloc_communication.dart.md
Fixed:
1. 'listen' is deprecated and shouldn't be used. Use stream.listen instead. Will be removed in v8.0.0.
2. Non-nullable instance field 'otherBlocSubscription' must be initialized.  Try adding an initializer expression, or add a field initializer in this constructor, or mark it 'late'.
YES | NO
> docs(architecture): update bloc-to-bloc communication snippet to null safety

- packages/flutter_bloc/README.md
- packages/flutter_bloc/lib/flutter_bloc.dart
- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_consumer.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_selector.dart
- packages/flutter_bloc/test/bloc_selector_test.dart
**READY**
NO
- feat(flutter_bloc): BlocSelector (closes #1989)
As a developer, I want to be able to select part of a bloc state and selectively rebuild UI in response to when the selected value changes. Currently this can be accomplishing via the `context.select` extension but it is not supported as a built-in widget (specifically in cases where the bloc is not available in the current `BuildContext`).
**BlocSelector** is a Flutter widget which is analogous to `BlocBuilder` but allows developers to filter updates by selecting a new value based on the current bloc state. Unnecessary builds are prevented if the selected value does not change. The selected value must be immutable in order for `BlocSelector` to accurately determine whether `builder` should be called again.
If the `bloc` …
> feat(flutter_bloc): BlocSelector

- packages/bloc_test/CHANGELOG.md
- packages/bloc_test/README.md
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/pubspec.yaml
- packages/bloc_test/test/bloc_bloc_test_test.dart
**READY**
NO
- feat(bloc_test): add `setUp` and `tearDown` methods
As a developer, I want to have the ability to execute set up and tear down code as part of a `blocTest` so that I don't have to clutter the `build` and `verify` api:
```dart
blocTest(
setUp: () {
// Execute any set up code needed prior to building the bloc.
when(() => repository.someMethod()).thenReturn(...);
},
build: () => MyBloc(repository),
act: (bloc) => bloc.add(...),
expect: () => [...],
tearDown: () {
// Execute any tear down code needed after the test has run.
verifyNoMoreInteractions(repository);
},
);
```
> feat(bloc_test): add `setUp` and `tearDown`

- packages/hydrated_bloc/README.md
**READY**
NO
[https://pub.dev/packages/hydrated_bloc](https://pub.dev/packages/hydrated_bloc) mentions an example 404ing to [https://github.com/felangel/bloc/blob/master/example](https://github.com/felangel/bloc/blob/master/example)
Either point to the concrete url or maybe remove the wording.
> docs(hydrated_bloc): fix example link rendered on pub.dev

- docs/fluttercountertutorial.md
**READY**
NO
The tutorial starts by creating a brand new flutter project but then it tells you copy paste the pubspec from the bloc github, where the versions specified. I think for this type of "create a project" tutorial you need specific versions. The down side is updating the versions.
I was also missing which files i needed to create so I added a paragraph where it was missing.
In general the whole concept of the tutorial could be changed, since it would be better to just tell the reader to clone the bloc repo, and open Android Studio with the right example folder and then explain each file
> docs(fluttercountertutorial): specify file paths for each section

- docs/pt-br/_coverpage.md
- docs/pt-br/_sidebar.md
- docs/pt-br/migration.md
**READY**
NO
- add links to the Migration Guide in the sidebar and cover page
- add the sponsor info on the cover page
> Note: Currently, the Migration Guide (pt-br) already exists in the repo, however, there was no link pointing to this document.
> docs(pt-br): add links to the Migration Guide

- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
**READY**
YES
- feat(bloc)!: `add` throws `StateError` when bloc is closed
> feat(bloc)!: add throws StateError when bloc is closed

- packages/bloc/lib/src/bloc.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/cubit_test.dart
**READY**
YES
- feat(bloc)!: emit throws StateError when bloc is closed (closes #2261)
> feat(bloc)!: emit throws StateError when bloc is closed

- packages/flutter_bloc/example/analysis_options.yaml
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
- fix(flutter_bloc): BlocProvider explicit lazy to support `avoid_redundant_argument_values`
- closes #2916
> fix(flutter_bloc): BlocProvider explicit lazy to support avoid_redundant_argument_values

- docs/fluttertimertutorial.md
**READY**
NO
In the timer tutorial documentation, I just updated the event's function name (_onPaused) in the TimerBloc. The tutorial does not use _mapTimerPausedToState, instead, it uses the event handler named _onPaused. Thus, It should be used in order to avoid confusion.
> docs(flutter_timer_tutorial): rename _mapTimerPausedToState to _onPaused

- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/test/bloc_listener_test.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
- fix(flutter_bloc): BlocListener, BlocProvider missing child assertion
> fix(flutter_bloc): BlocListener, BlocProvider missing child assertion

- extensions/vscode/src/utils/convert-to.ts
- extensions/vscode/src/utils/wrap-with.ts
FINISH
NO
When wrapp with bloc snippet, the $ expression in the widget content will be removed.
***Root case:*** VS Code insertSnippet will execute the $ expression in the text.
***Fix:*** Escape the $ to prevent it from being executed incorrectly.
- [ x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
#2925
> Fixed  vscode wrap issue.

- .github/workflows/hydrated_bloc.yaml
- examples/flutter_weather/lib/main.dart
- examples/flutter_weather/test/app_test.dart
- examples/flutter_weather/test/helpers/hydrated_bloc.dart
- examples/flutter_weather/test/theme/cubit/theme_cubit_test.dart
- examples/flutter_weather/test/weather/cubit/weather_cubit_test.dart
- examples/flutter_weather/test/weather/view/weather_page_test.dart
- packages/hydrated_bloc/example/lib/main.dart
- packages/hydrated_bloc/lib/hydrated_bloc.dart
- packages/hydrated_bloc/lib/src/hydrated_bloc.dart
- packages/hydrated_bloc/test/e2e_test.dart
- packages/hydrated_bloc/test/hydrated_bloc_overrides_test.dart
- packages/hydrated_bloc/test/hydrated_bloc_test.dart
- packages/hydrated_bloc/test/hydrated_cubit_test.dart
- packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
YES
- feat(hydrated_bloc)!: HydratedBlocOverrides API
- closes #1421
> feat(hydrated_bloc)!: HydratedBlocOverrides API

- docs/_snippets/flutter_bloc_core_concepts/counter_bloc.dart.md
- docs/_snippets/flutter_bloc_core_concepts/counter_page.dart.md
READY
NO
Update examples on docs(flutterbloccoreconcepts) follow naming convention.
#3023
> docs(flutterbloccoreconcepts): rename events to follow naming conventions

- packages/flutter_bloc/example/lib/main.dart
**READY**
NO
- docs(flutter_bloc): update example to follow naming conventions
> docs(flutter_bloc): update example to follow naming conventions

- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_base.dart
- packages/flutter_bloc/lib/src/bloc_builder.dart
- packages/flutter_bloc/lib/src/bloc_consumer.dart
- packages/flutter_bloc/lib/src/bloc_listener.dart
- packages/flutter_bloc/lib/src/bloc_provider.dart
- packages/flutter_bloc/lib/src/bloc_selector.dart
- packages/flutter_bloc/pubspec.yaml
**READY**
NO
- refactor(bloc): add core interfaces (closes #2994)
> refactor(bloc): add core interfaces

- packages/bloc/lib/src/bloc_base.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/cubit_test.dart
**READY**
NO
- fix(bloc): make `onChange` and `addError` protected (closes #3068)
> fix(bloc): make onChange and addError protected

- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/test/bloc_bloc_test_test.dart
- packages/bloc_test/test/cubits/delayed_counter_cubit.dart
**READY**
NO
If an uncaught error occurs within a bloc, cubit, or within the `blocTest` they are currently being swallowed by default which makes it very difficult to debug. Instead of swallowing uncaught errors, this change rethrows uncaught errors so that it is clear that an exception has occurred during the `blocTest`.
If `errors` is not null, uncaught errors will be aggregated and evaluated against the `errors` matcher.
- closes #3058
> fix(bloc_test): throw uncaught exceptions

- packages/bloc/lib/src/bloc_base.dart
**READY**
NO
- refactor(bloc): use late keyword for internal state controller (closes #3089)
> refactor(bloc): use late keyword for internal state controller

- packages/bloc/CHANGELOG.md
- packages/bloc/pubspec.yaml
**READY**
NO
- fix: make `onChange` and `addError` protected ([#3071](https://github.com/felangel/bloc/pull/3071))
- refactor: use `late` keyword for internal state controller ([#3100](https://github.com/felangel/bloc/pull/3100))
- refactor: add `isClosed` to `Closable` ([#3066](https://github.com/felangel/bloc/pull/3066))
- refactor: add core interfaces ([#3012](https://github.com/felangel/bloc/pull/3012))
- refactor: internal reorganization ([#3011](https://github.com/felangel/bloc/pull/3011))
- docs: update example to follow naming conventions ([#3029](https://github.com/felangel/bloc/pull/3029))
> chore(bloc): v8.0.2

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/pubspec.yaml
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
- refactor: use core interfaces from `bloc v8.0.2` ([#3012](https://github.com/felangel/bloc/pull/3012))
- docs: update example to follow naming conventions ([#3027](https://github.com/felangel/bloc/pull/3027))
> chore(flutter_bloc): v8.0.1

- docs/fluttertodostutorial.md
Follow up to https://github.com/felangel/bloc/commit/4e1cfbb8ffafaa239c6c94e88844f985b5704a63
**READY**
NO
Both dashes should be character 45 instead of 151 and 45 (https://www.petefreitag.com/cheatsheets/ascii-codes/). I confirmed that copy/pasting the existing characters makes the command fail in the terminal.
> docs(fluttertodostutorial): use correct ascii character in `--recursive`

- packages/bloc/lib/src/emitter.dart
**READY**
NO
Included an additional slash to convert the block comment (`//`) to a doc comment (`///`). Closes #3166 .
> docs(bloc): Included missing slash in doc comment

- docs/flutterbloccoreconcepts.md
**IN DEVELOPMENT**
NO
Aims to resolve #3141 , by including an "Extension Methods usage" section that documents what and how extension methods included when importing `flutter_bloc` should be used.
> docs(flutter_bloc): Extension Methods documentation

- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/emitter.dart
**READY**
NO
- refactor(bloc): resolve analysis warning
> refactor(bloc): resolve analysis warning

- docs/_snippets/core_concepts/counter_bloc_on_error.dart.md
- docs/_snippets/core_concepts/counter_cubit_on_change.dart.md
Fix the order of super.onChange in docs
**READY**
NO
A fix on the order in which super.onChange is called in a couple of places, which otherwise contradicts the source docs.
> Fix the order of super.onChange in docs

- packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): support for mocktail v0.3.0
> chore(bloc_test): support for mocktail v0.3.0

- packages/hydrated_bloc/lib/src/hydrated_bloc.dart
- packages/hydrated_bloc/test/hydrated_bloc_test.dart
- packages/hydrated_bloc/test/hydrated_cubit_test.dart
**READY**
NO
- feat(hydrated_bloc): storagePrefix for obfuscation tolerance (closes #3255)
```dart
class CounterBloc extends HydratedBloc<CounterEvent, int> {
CounterBloc() : super(0) {
on<CounterIncrementPressed>((event, emit) => emit(state + 1));
on<CounterDecrementPressed>((event, emit) => emit(state - 1));
}
@override
String get storagePrefix => 'CounterBloc';
@override
int fromJson(Map<String, dynamic> json) => json['value'] as int;
@override
Map<String, int> toJson(int state) => {'value': state};
}
```
> feat(hydrated_bloc): storagePrefix for obfuscation tolerance

- extensions/vscode/.vscodeignore
- extensions/vscode/package.json
- extensions/vscode/webpack.config.js
**READY**
NO
VSCode extensions `.vscodeignore` was missing an entry for `node_modules` which meant the bundle size was larger by shipping unnecessary node_modules JS files. I also changed the webpack `output.path` to `dist` and package main entrypoint to `./dist/extension` so that output of `tsc -p ./` in `./out/` can also be safely ignored from VSCode extension bundle.
This change reduces the generated vsix file size from (1311 files, 2.32MB) to (15 files, 1.27MB).
**BEFORE**
**AFTER**
> fix(vscode): Reduce VSCode extension bundle size by ignoring node_modules and changing webpack output

- docs/_snippets/architecture/do_not_do_this_at_home.dart.md
READY
NO
Missed a constructor name when renaming 🤦‍♀️
> docs(architecture): fix constructor name in bloc-to-bloc communication snippet

- packages/bloc/lib/src/emitter.dart
Ready
NO
`Emitter.onEach` returns a `Future` from a function marked `async`. Since it returns the `Future` and does no `awaiting`, it doesn't need to be marked `async`.
This appears to have been an old typo. Not actually sure if this caused any bugs, but likely not working as intended.
> fix(bloc): remove unnecessary "async" from "Emitter.onEach"

- packages/bloc/README.md
- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_base.dart
- packages/bloc/lib/src/bloc_overrides.dart
- packages/bloc/test/bloc_event_transformer_test_legacy.dart
- packages/bloc/test/bloc_overrides_test.dart
- packages/bloc/test/bloc_test_legacy.dart
- packages/bloc/test/cubit_test_legacy.dart
**READY**
NO
- feat(bloc): deprecate `BlocOverrides` in favor of `Bloc.observer` and `Bloc.transformer` (#3470).
> feat(bloc): deprecate BlocOverrides

- docs/_snippets/core_concepts/simple_bloc_observer_on_change_usage.dart.md
- docs/_snippets/core_concepts/simple_bloc_observer_on_transition_usage.dart.md
- examples/angular_counter/web/main.dart
- examples/flutter_complex_list/lib/main.dart
- examples/flutter_counter/lib/main.dart
- examples/flutter_firebase_login/lib/main.dart
- examples/flutter_infinite_list/lib/main.dart
- examples/flutter_shopping_cart/lib/main.dart
- examples/flutter_todos/lib/bootstrap.dart
- examples/flutter_todos/pubspec.lock
- examples/flutter_todos/pubspec.yaml
- examples/flutter_weather/lib/main.dart
- examples/flutter_weather/test/app_test.dart
- examples/flutter_weather/test/helpers/hydrated_bloc.dart
- examples/flutter_weather/test/theme/cubit/theme_cubit_test.dart
- examples/flutter_weather/test/weather/cubit/weather_cubit_test.dart
- examples/flutter_weather/test/weather/view/weather_page_test.dart
- packages/flutter_bloc/example/lib/main.dart
- packages/replay_bloc/example/lib/main.dart
**READY**
NO
- chore(examples): upgrade to latest bloc/hydrated_bloc apis
> chore(examples): upgrade to latest bloc and hydrated_bloc

- examples/flutter_login/test/authentication/authentication_bloc_test.dart
**READY**
NO
Just a cleanup of flutter_login example tests
> chore(flutter_login): remove redundant setUp in authentication_bloc_test of flutter_login example

- examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml
- examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart
- examples/flutter_firebase_login/pubspec.yaml
Fixes: #3651
**READY**
NO
Fixing test failing 
```
m@m-inspiron5567:~/code/pr/bloc/examples/flutter_firebase_login/packages/authentication_repository$ flutter test
00:12 +4 -1: /home/m/code/pr/bloc/examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart: AuthenticationRepository loginWithGoogle calls signIn authentication, and signInWithCredential [E]
Bad state: A test tried to use `any` or `captureAny` on a parameter of type `AuthProvider`, but
registerFallbackValue was not previously called to register a fallback value for `AuthProvider`.  
```
> fix(flutter_firebase_login): Authentication Repository test failing

- examples/flutter_login/lib/app.dart
- examples/flutter_login/lib/authentication/bloc/authentication_bloc.dart
- examples/flutter_login/lib/main.dart
Repository dispose updated 
NO
AuthenticationRepository shouldn't be disposed from bloc. 
So best practice [comment](https://github.com/felangel/bloc/issues/952#issuecomment-598793189) by @felangel  
create a StatefulWidget to create the repository and handle releasing resources in the dispose.
> refactor(flutter_login): dispose authentication repository

- packages/bloc/example/main.dart
- packages/bloc/lib/src/bloc.dart
- packages/bloc/lib/src/bloc_observer.dart
- packages/bloc/test/bloc_observer_test.dart
**READY**
NO
Fixes https://github.com/felangel/bloc/issues/3703 by adding a const constructor to `BlocObserver`
> refactor(bloc): Add const constructor to `BlocObserver`

- examples/angular_counter/web/main.dart
- examples/flutter_complex_list/lib/main.dart
- examples/flutter_complex_list/lib/simple_bloc_observer.dart
- examples/flutter_counter/lib/counter_observer.dart
- examples/flutter_counter/lib/main.dart
- examples/flutter_firebase_login/lib/app/bloc_observer.dart
- examples/flutter_firebase_login/lib/main.dart
- examples/flutter_infinite_list/lib/main.dart
- examples/flutter_infinite_list/lib/simple_bloc_observer.dart
- examples/flutter_shopping_cart/lib/main.dart
- examples/flutter_shopping_cart/lib/simple_bloc_observer.dart
- examples/flutter_todos/lib/app/app_bloc_observer.dart
- examples/flutter_todos/lib/bootstrap.dart
- examples/flutter_todos/pubspec.lock
- examples/flutter_todos/pubspec.yaml
- examples/flutter_weather/lib/main.dart
- examples/flutter_weather/lib/weather_bloc_observer.dart
- packages/bloc_test/lib/src/bloc_test.dart
- packages/flutter_bloc/example/lib/main.dart
- packages/replay_bloc/example/lib/main.dart
**READY**
NO
Follows https://github.com/felangel/bloc/pull/3704 and relates to https://github.com/felangel/bloc/issues/3703
This PR updates all the bloc observers to have and use a const constructor.
> refactor: update BlocObserver instances to use const constructors

- packages/flutter_bloc/CHANGELOG.md
- packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore: add screenshots to `pubspec.yaml` ([#3717](https://github.com/felangel/bloc/pull/3717))
- chore(deps): upgrade to `bloc ^8.1.1` ([#3716](https://github.com/felangel/bloc/pull/3716))
- chore: update example to Dart 2.19 ([#3715](https://github.com/felangel/bloc/pull/3715))
- refactor: `BlocObserver` instances to use `const` constructors ([#3713](https://github.com/felangel/bloc/pull/3713))
- refactor: remove unnecessary single child widget mixins ([#3675](https://github.com/felangel/bloc/pull/3675))
- refactor: upgrade to Flutter 3.7 ([#3699](https://github.com/felangel/bloc/pull/3699))
- remove deprecated `invariant_booleans` lint rule
> chore(flutter_bloc): v8.1.2

- .github/workflows/angular_bloc.yaml
- .github/workflows/angular_dart_examples.yaml
- examples/angular_counter/pubspec.yaml
- examples/github_search/angular_github_search/analysis_options.yaml
- examples/github_search/angular_github_search/pubspec.yaml
- examples/github_search/common_github_search/analysis_options.yaml
- examples/github_search/common_github_search/pubspec.yaml
- packages/angular_bloc/pubspec.yaml
Hi @felangel! Sorry for the delay. I just published an AngularDart v8 pre-release that uses analyzer v5, so this should allow `angular_bloc` to use Dart 2.19 now.
**READY**
YES
Bump AngularDart to `v8.0.0-dev.0` to allow upgrading the minimum Dart SDK to 2.19
> refactor(angular_bloc)!: upgrade ngdart to v8 pre-release

- docs/_snippets/architecture/do_not_do_this_at_home.dart.md
READY
NO
While implementing lint rules for Bloc, I noticed that the copied example code doesn't compile due to a missing semicolon.
> docs(architecture): add missing semicolon in snippet

- README.md
Bloc Code Generator is discontinued, and is no longer recommended
READY
NO
The Bloc Code Generator package has been discontinued, and hence must be removed from the README page.
> docs: remove discontinued package from README

- README.md
- docs/es/README.md
- docs/jp/README.md
- docs/ko-kr/README.md
- packages/flutter_bloc/README.md
**READY**
NO
- chore: remove graphql example links from README
> chore: remove graphql example links from README

- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/test/bloc_bloc_test_test.dart
**HOLD**
NO
- fix(bloc_test): test timeouts due to uncaught exceptions (closes #3848)
> fix(bloc_test): test timeouts due to uncaught exceptions

- packages/hydrated_bloc/lib/src/hydrated_storage.dart
- packages/hydrated_bloc/test/hydrated_storage_test.dart
READY
NO
When closing the HydratedStorage with `HydratedStorage.close()` the _instance is not set to null.
Calling `HydratedStorage.build` afterwards returns the old instance. Thus skipping reopening the HiveBox.
When the hydrated_box.hive file is modified/replaced/etc. in between these two steps. Changes would not be visible because the file would not be reopened.
This fix sets the instance back to null, when closing the HydratedStorage, to force a complete rebuild of the HiveBox when building a new Storage.
This enables the following use-cases without having to implement a custom Storage:
* export of .hive file to external storage
* import of .hive file from external storage
> fix(hydrated_bloc) clear HydratedStorage instance on close

- analysis_options.yaml
- examples/flutter_dynamic_form/test/new_car/bloc/new_car_bloc_test.dart
- examples/flutter_firebase_login/lib/home/view/home_page.dart
- examples/flutter_firebase_login/test/app/routes/routes_test.dart
- examples/flutter_firebase_login/test/login/cubit/login_cubit_test.dart
- examples/flutter_firebase_login/test/sign_up/cubit/sign_up_cubit_test.dart
- examples/flutter_infinite_list/test/posts/bloc/post_bloc_test.dart
- examples/flutter_shopping_cart/lib/app.dart
- examples/flutter_shopping_cart/lib/cart/view/cart_page.dart
- examples/flutter_shopping_cart/test/cart/bloc/cart_bloc_test.dart
- examples/flutter_timer/lib/timer/view/timer_page.dart
- examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart
- examples/flutter_todos/pubspec.lock
- examples/flutter_todos/pubspec.yaml
- examples/flutter_weather/lib/search/view/search_page.dart
- examples/flutter_weather/packages/open_meteo_api/lib/src/open_meteo_api_client.dart
- examples/flutter_weather/packages/open_meteo_api/test/open_meteo_api_client_test.dart
- examples/flutter_wizard/lib/main.dart
- packages/bloc/test/bloc_test.dart
- packages/bloc/test/bloc_test_legacy.dart
- packages/bloc_concurrency/test/src/restartable_test.dart
- packages/flutter_bloc/test/bloc_builder_test.dart
- packages/flutter_bloc/test/bloc_provider_test.dart
- packages/flutter_bloc/test/multi_bloc_provider_test.dart
- packages/flutter_bloc/test/repository_provider_test.dart
- packages/hydrated_bloc/test/cubits/list_cubit.dart
- packages/hydrated_bloc/test/hydrated_bloc_test.dart
- packages/hydrated_bloc/test/hydrated_cubit_test.dart
- packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
NO
- chore: fix `require_trailing_commas`
> chore: fix `require_trailing_commas`

- docs/_snippets/core_concepts/counter_cubit_on_change_usage_output.sh.md
- docs/_snippets/core_concepts/simple_bloc_observer_on_event_output.sh.md
- docs/_snippets/core_concepts/simple_bloc_observer_on_transition_output.sh.md
- docs/coreconcepts.md
**READY**
NO
- docs(coreconcepts): fix outputs when observing blocs/cubits (closes #3797)
> docs(coreconcepts): fix outputs when observing blocs/cubits

- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/test/bloc_bloc_test_test.dart
- packages/bloc_test/test/cubit_bloc_test_test.dart
> fix(bloc_test): add await before expect

- examples/flutter_weather/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/hydrated_bloc/README.md
- packages/hydrated_bloc/pubspec.yaml
There are no breaking changes
It's simple, first of all, it adds all the platforms as supported in `pubspec.yaml`
Because in [pub.dev](https://pub.dev/packages/hydrated_bloc):
The analysis in the pub page package indicates the package does not support web
Also in `README.md` it didn't say that there is `HydratedStorage.webStorageDirectory` for the web so this simple pull request updates the `README.md` to make it more clear there is support for Flutter web
> chore(hydrated_bloc): add `platforms` to `pubspec.yaml`

- CONTRIBUTING.md
**READY**
NO
The `format` & `analyze` commands mentioned in the CONTRIBUTING.md became outdated quite some time ago, let's make them up to date.
> chore: update format and analyze commands in CONTRIBUTING.md

- docs/astro.config.mjs
“中国人” means Chinese people rather than a language.
> docs: fix chinese lang translation

- docs/src/components/landing/Discord.astro
- docs/src/components/landing/SponsorsGrid.astro
- docs/src/content/docs/es/index.mdx
**READY**
NO
- docs: add `es/index.mdx`
> docs: add `es/index.mdx`

- docs/astro.config.mjs
- docs/package-lock.json
- docs/src/content/docs/ar/index.mdx
/ar/index.mdx
**READY**
NO
/ar/index.md added
> docs: add `ar/index.mdx`

- docs/src/content/docs/fil/getting-started.mdx
- docs/src/content/docs/fil/why-bloc.mdx
**READY**
NO
Continuation of Filipino l10n. Add getting-started and why-bloc files.
> docs: add `getting-started` and `why-bloc` fil translation

- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocAction.kt
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocDialog.java
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateCubitAction.kt
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateEquatablePropsAction.kt
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/BlocGenerator.kt
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/BlocGeneratorFactory.kt
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/CubitGenerator.kt
- extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/CubitGeneratorFactory.kt
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/bloc_basic/bloc.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/bloc_basic/bloc_event.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/bloc_basic/bloc_state.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/bloc_equatable/bloc.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/bloc_equatable/bloc_event.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/bloc_equatable/bloc_state.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/cubit_basic/cubit_state.dart.template
- extensions/intellij/intellij_generator_plugin/src/main/resources/templates/cubit_equatable/cubit_state.dart.template
**READY**
NO
- feat(intellij): generate sealed classes (closes #3911)
> feat(intellij)!: generate sealed classes

- packages/flutter_bloc/lib/src/bloc_listener.dart
**READY**
NO
- docs(flutter_bloc): add missing comma to `BlocListener` API docs (closes #4101)
> docs(flutter_bloc): add missing comma to `BlocListener` API docs

- docs/package.json
- docs/src/components/landing/SponsorsGrid.astro
**READY**
NO
In the `Sponsor` interface there is an img property with the `ImageMetadata` type, we can specify it as a parameter for `<Image />`. `<Image />`is more optimized than the usual `<img />` tag and therefore I replaced it with `Image`
With this [commit](https://github.com/felangel/bloc/commit/0380353d822ce957fcc50d05cd1038451c7d316b), errors with types in TS are removed `Corresponding file not included in tsconfig.json`
> docs: use optimized astro `Image` in `SponsorsGrid.astro`

- docs/astro.config.mjs
NO
All the links in the left menu on https://bloclibrary.dev are broken -- require a trailing slash.
> docs: add trailing slash to introduction section links

- examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart
- examples/flutter_todos/packages/local_storage_todos_api/test/local_storage_todos_api_test.dart
- examples/flutter_todos/packages/todos_api/lib/src/todos_api.dart
**READY**
NO
Even though the lifetime of the `TodosApi` instance is tied to the application in this case, it's still valuable to add a `close` API to the interface since the `TodosApi` should expose a way to close the instance and free any allocated resources. (closes #4154)
> refactor(flutter_todos): add `close` to `TodosApi`

- docs/src/components/getting-started/InstallationTabs.astro
just replaced "dart pub add" for "flutter pub add" in flutter installation command
READY
No
just documentation update
> docs(getting-started): use `flutter pub add` for `flutter_bloc` installation

- docs/src/content/docs/tutorials/flutter-firebase-login.mdx
- examples/flutter_firebase_login/lib/login/view/login_form.dart
- examples/flutter_firebase_login/lib/sign_up/view/sign_up_form.dart
**READY**
NO
- Uses `context.select` instead of BlocBuilders
> refactor(flutter_firebase_login): use `context.select` instead of BlocBuilders

- examples/flutter_todos/lib/bootstrap.dart
**READY**
NO
Fixes zone mismatch error by removing `runZonedGuarded` and handling errors through `PlatformDispatcher` instead.
> fix(flutter_todos): fix zone mismatch error

- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/README.md
- packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v10.0.0-dev.4
> chore(angular_bloc): v10.0.0-dev.4

- bricks/cubit/CHANGELOG.md
- bricks/cubit/brick.yaml
- bricks/cubit/hooks/pubspec.yaml
**READY**
NO
- chore(bricks): cubit v0.3.0
> chore(bricks): cubit v0.3.0

- examples/flutter_weather/lib/weather/cubit/weather_cubit.dart
- examples/flutter_weather/test/weather/cubit/weather_cubit_test.dart
Name the `double` extension to make it available through imports in other files (i.e. in weather_cubit_test.dart).
**READY**
NO
I’m following the `flutter_weather` example, and I encountered an error in the `weather_cubit_test.dart` file:
```
The method 'toFahrenheit' isn't defined for the type 'double'.
Try correcting the name to the name of an existing method, or defining a method named 'toFahrenheit'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)
Type: InvalidType
```
However exports and imports are correct (I double-checked them).
Just naming the extension fixes this error.
EDIT: I realized a bit later that the extension was added again in the test file. So the current code is fully functional and my PR is less necessary.
- [] 🛠️ Bug fix (non-breaking change …
> refactor(weather_example): use named extension

- packages/bloc/lib/src/change.dart
- packages/bloc/lib/src/transition.dart
- packages/bloc/pubspec.yaml
- packages/bloc/test/blocs/async/async_event.dart
- packages/bloc/test/blocs/async/async_state.dart
- packages/bloc/test/transition_test.dart
**READY**
NO
- refactor(bloc): use `Object.hashAll` (closes https://github.com/felangel/bloc/issues/3090)
- bumps minimum Dart SDK to 2.14
> refactor(bloc): use `Object.hashAll`

- .github/actions/dart_package/action.yaml
- .github/workflows/main.yaml
- packages/bloc/lib/src/bloc_base.dart
- packages/bloc/pubspec.yaml
- packages/bloc_test/lib/src/bloc_test.dart
- packages/bloc_test/pubspec.yaml
**READY**
YES
- refactor(bloc)!: introduce `EmittableStateStreamableSource`
- closes https://github.com/felangel/bloc/issues/3377
- bumps `bloc_test` minimum Dart SDK to 2.14
> refactor(bloc)!: introduce `EmittableStateStreamableSource`

- packages/hydrated_bloc/README.md
- packages/hydrated_bloc/example/lib/main.dart
- packages/hydrated_bloc/lib/src/_migration/_migration_io.dart
- packages/hydrated_bloc/lib/src/_migration/_migration_stub.dart
- packages/hydrated_bloc/lib/src/hydrated_storage.dart
- packages/hydrated_bloc/test/e2e_test.dart
- packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
YES
- feat(hydrated_bloc)!: support for WASM
- Introduces `HydratedStorageDirectory` and modifies `HydratedStorage.build` signature to use `HydratedStorageDirectory` instead of `Directory` from `dart:io`
**Sample Usage**
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hydrated_bloc/hydrated_bloc.dart';
import 'package:path_provider/path_provider.dart';
void main() async {
WidgetsFlutterBinding.ensureInitialized();
HydratedBloc.storage = await HydratedStorage.build(
storageDirectory: kIsWeb
? HydratedStorageDirectory.web
: HydratedStorageDirectory((await getTemporaryDirectory()).path),
);
runApp(const App());
}
```
> feat(hydrated_bloc)!: support for WASM

- packages/angular_bloc/CHANGELOG.md
- packages/angular_bloc/pubspec.yaml
- packages/bloc/CHANGELOG.md
**READY**
NO
- chore(angular_bloc): v10.0.0-dev.5
> chore(angular_bloc): v10.0.0-dev.5

- docs/src/content/docs/ar/index.mdx
- docs/src/content/docs/de/index.mdx
- docs/src/content/docs/es/index.mdx
- docs/src/content/docs/fa/index.mdx
- docs/src/content/docs/fil/index.mdx
- docs/src/content/docs/fr/index.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/ko/index.mdx
- docs/src/content/docs/zh-cn/index.mdx
**READY**
NO
- docs: bump to bloc v9
> docs: bump to bloc v9

- docs/src/content/docs/migration.mdx
**READY**
NO
- docs(migration): updates for bloc v9
> docs(migration): updates for bloc v9

- docs/src/content/docs/faqs.mdx
- docs/src/content/docs/ko/faqs.mdx
- packages/hydrated_bloc/test/cubits/list_cubit.dart
**READY**
NO
Update the docs and a few test snippets to use `List.of` and `Map.of` instead of `List.from` and `Map.from`. The `of` factories offer better type-safety by enforcing the collection types at compile-time.
Some instances of the `from` factories remain, as they are used for type promotion. To find such cases, run the regex: `(List|Map).*[.]from`. These cases align with [Dart's documentation on `Map.from`](https://api.dart.dev/dart-core/Map/Map.from.html):
> Prefer using Map.of when possible, and only use Map.from to create a new map with more precise types than the original, and when it's known that all the keys and values have those more precise types.
> refactor: prefer `{List,Map}.of` over `{List,Map}.from`

- examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart
- Simplified the calculation of completedTodosAmount by removing unnecessary iterations over the todos list.
- Instead of filtering the list first and then removing items, now we compute the count using the difference in list lengths.
- Improves performance by reducing redundant operations.
**READY**
NO
Simplified the calculation of `completedTodosAmount` by eliminating unnecessary iterations over the todos list. Instead of filtering the list first to count completed todos and then removing them, we now determine the count using the difference between the initial and final list lengths.
> refactor(flutter_todos): simplify completedTodos logic

- docs/src/components/concepts/flutter-bloc/RepositoryProviderDisposeSnippet.astro
- docs/src/components/concepts/flutter-bloc/WeatherAppSnippet.astro
- docs/src/components/concepts/flutter-bloc/WeatherMainSnippet.astro
- docs/src/components/concepts/flutter-bloc/WeatherRepositorySnippet.astro
- docs/src/content/docs/flutter-bloc-concepts.mdx
- examples/flutter_bloc_with_stream/pubspec.yaml
- examples/flutter_complex_list/pubspec.yaml
- examples/flutter_counter/pubspec.yaml
- examples/flutter_dynamic_form/pubspec.yaml
- examples/flutter_firebase_login/pubspec.yaml
- examples/flutter_form_validation/pubspec.yaml
- examples/flutter_infinite_list/pubspec.yaml
- examples/flutter_login/pubspec.yaml
- examples/flutter_shopping_cart/pubspec.yaml
- examples/flutter_timer/pubspec.yaml
- examples/flutter_todos/pubspec.lock
- examples/flutter_todos/pubspec.yaml
- examples/flutter_weather/lib/main.dart
- examples/flutter_weather/packages/weather_repository/lib/src/weather_repository.dart
- examples/flutter_weather/pubspec.yaml
- examples/flutter_wizard/pubspec.yaml
- packages/flutter_bloc/example/pubspec.yaml
- packages/hydrated_bloc/example/pubspec.yaml
- packages/replay_bloc/example/pubspec.yaml
**READY**
NO
- docs: update to flutter bloc v9.1.0
> docs: update to flutter bloc v9.1.0

- packages/flutter_bloc/lib/src/multi_bloc_listener.dart
- packages/flutter_bloc/lib/src/multi_bloc_provider.dart
- packages/flutter_bloc/lib/src/multi_repository_provider.dart
- packages/flutter_bloc/pubspec.yaml
**READY**
YES
- refactor(flutter_bloc): support breaking change in `provider` v6.1.3
- this is technically a breaking change because `MultiBlocProvider`, `MultiBlocListener`, and `MultiRepositoryProvider` are no longer subclasses of `MultiProvider` but we're forced to do so due to the breaking changes introduced in `pkg:provider` v6.1.3 (closes https://github.com/felangel/bloc/issues/4383 and related to https://github.com/rrousselGit/provider/issues/907).
- I would have much preferred for @rrousselgit to have reverted the change and published 6.1.4 but it's been 5 hours since the breaking change was published and I don't want to keep waiting for an upstream fix since there hasn't been any update or indication that the change will be reverted and this is very disruptive change for all …
> fix(flutter_bloc): support breaking change in `provider` v6.1.3

- extensions/intellij/intellij_generator_plugin/build.gradle.kts
- extensions/intellij/intellij_generator_plugin/gradle.properties
**READY**
NO
Fix #4479 : Apache Commons Text seems to not being available in the ClassPath on 2025.1.1 of IntelliJ.
> fix(intellij): apache commons text missing on some IJ versions

- packages/flutter_bloc/lib/src/repository_provider.dart
**READY**
NO
This is a super nit and very minor, I found it while I was looking into the doc comment of `RepositoryProvider`.
> fix(docs): remove stray backtick in RepositoryProvider example code comment

- docs/src/content/docs/pt-br/flutter-bloc-concepts.mdx
Hi there, I noticed that some pages in pt-br are not translated. Since it's my mother language, I decided to contribute to the translation.
**READY**
NO
This PR translates the Flutter Bloc Concepts page from English to Brazilian Portuguese.
> docs(pt-br): add translations for flutter bloc concepts
