felangel/bloc

docs/update-pubspec.js
**READY**
NO
- docs: upgrade pubspec versions to v8.0.0
=> docs: upgrade pubspec versions to v8.0.0

docs/_coverpage.md, docs/az/_coverpage.md, docs/cs/_coverpage.md, docs/de-de/_coverpage.md, docs/es/_coverpage.md, docs/fr/_coverpage.md, docs/jp/_coverpage.md, docs/ko-kr/_coverpage.md, docs/pt-br/_coverpage.md, docs/ru/_coverpage.md, docs/zh-cn/_coverpage.md
**READY**
NO
- docs(coverpage): update localized coverpages
=> docs(coverpage): update localized coverpages

packages/angular_bloc/pubspec.yaml, packages/bloc/lib/src/bloc.dart, packages/bloc/test/bloc_overrides_test.dart, packages/bloc_concurrency/pubspec.yaml, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml, packages/flutter_bloc/pubspec.yaml, packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/hydrated_bloc_overrides_test.dart, packages/replay_bloc/lib/src/replay_bloc.dart, packages/replay_bloc/pubspec.yaml
**READY**
NO
- fix(bloc): allow bloc emit usage within tests (closes #2981)
```dart
// main.dart
import 'package:bloc/bloc.dart';
class CounterCubit extends Cubit<int> {
CounterCubit() : super(0);
void increment() => emit(state + 1); // OK
}
class CounterEvent {}
class CounterBloc extends Bloc<CounterEvent, int> {
CounterBloc() : super(0) {
on<CounterEvent>((event, emit) => emit(42)); // OK
}
void foo() => emit(42); // LINT
}
void main() {
final bloc = CounterBloc();
final cubit = CounterCubit();
bloc.emit(42); // LINT
cubit.emit(42); // LINT
}
```
```dart
// main_test.dart
import 'package:example/example.dart';
import 'package:test/test.dart';
void main() {
test('...', () {
final bloc = CounterBloc();
final cubit = CounterCubit();
bloc.emit(42); // OK
cubit.emit(42); // OK
});
}
```
=> fix(bloc): allow bloc emit usage within tests

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.0.1
=> chore(bloc): v8.0.1

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.0.1
=> chore(bloc_test): v9.0.1

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.1
=> chore(replay_bloc): v0.2.1

packages/angular_bloc/pubspec.yaml, packages/bloc_concurrency/pubspec.yaml, packages/flutter_bloc/pubspec.yaml, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore: remove bloc dependency override
=> chore: remove bloc dependency override

docs/_snippets/bloc_naming_conventions/event_examples_bad.md, docs/_snippets/bloc_naming_conventions/event_examples_good.md, docs/_snippets/bloc_naming_conventions/single_state_anatomy.md, docs/_snippets/bloc_naming_conventions/single_state_examples_good.md, docs/_snippets/bloc_naming_conventions/state_examples_bad.md, docs/_snippets/bloc_naming_conventions/state_examples_good.md, docs/blocnamingconventions.md
**READY**
NO
- docs(naming_conventions): single state class vs subclasses (closes #2935)
=> docs(naming_conventions): single state class vs subclasses

packages/bloc_tools/analysis_options.yaml, packages/bloc_tools/example/README.md, packages/bloc_tools/lib/src/command_runner.dart, packages/bloc_tools/pubspec.yaml, packages/bloc_tools/test/src/command_runner_test.dart
**READY**
NO
- chore(bloc_tools): dependency updates
- very_good_analysis
- mason
- pub_updater
=> chore(bloc_tools): dependency updates

docs/pt-br/migration.md
=> updating migration docs pt-BR

packages/hydrated_bloc/example/ios/Runner.xcodeproj/project.pbxproj, packages/hydrated_bloc/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/hydrated_bloc/example/lib/main.dart, packages/hydrated_bloc/example/pubspec.yaml
**READY**
NO
- fix(hydrated_bloc_example): use flutter_services_binding
=> fix(hydrated_bloc_example): use flutter_services_binding

examples/flutter_weather/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_weather/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_weather/lib/main.dart, examples/flutter_weather/pubspec.yaml
**READY**
NO
- chore(flutter_weather): use flutter_services_binding
=> chore(flutter_weather): use flutter_services_binding

packages/bloc/lib/bloc.dart, packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/bloc_base.dart, packages/bloc/lib/src/bloc_observer.dart, packages/bloc/lib/src/bloc_overrides.dart, packages/bloc/lib/src/change.dart, packages/bloc/lib/src/cubit.dart, packages/bloc/lib/src/emitter.dart, packages/bloc/lib/src/transition.dart
**READY**
NO
- refactor(bloc): maintain library exports (closes #3015)
=> refactor(bloc): maintain library exports

examples/angular_counter/lib/src/counter_page/counter_bloc.dart, examples/angular_counter/lib/src/counter_page/counter_page_component.dart, packages/angular_bloc/example/example.dart
**READY**
NO
- docs(angular_bloc): update example to follow naming conventions
=> docs(angular_bloc): update example to follow naming conventions

packages/bloc/README.md, packages/bloc/example/main.dart
**READY**
NO
- docs(bloc): update example to follow naming conventions
=> docs(bloc): update example to follow naming conventions

packages/hydrated_bloc/README.md, packages/hydrated_bloc/example/lib/main.dart
**READY**
NO
- docs(hydrated_bloc): update example to follow naming conventions
=> docs(hydrated_bloc): update example to follow naming conventions

packages/replay_bloc/README.md, packages/replay_bloc/example/lib/main.dart, packages/replay_bloc/lib/src/replay_bloc.dart
**READY**
NO
- docs(replay_bloc): update example to follow naming conventions
=> docs(replay_bloc): update example to follow naming conventions

packages/bloc_test/README.md, packages/bloc_test/example/main.dart
**READY**
NO
- docs(bloc_test): update example to follow naming conventions
=> docs(bloc_test): update example to follow naming conventions

packages/bloc/README.md, packages/bloc/example/main.dart
**READY**
NO
- docs(bloc): update example event names to be consistent
=> docs(bloc): update example event names to be consistent

packages/bloc_concurrency/README.md, packages/bloc_concurrency/example/main.dart
**READY**
NO
- docs(bloc_concurrency): update example to follow naming conventions
=> docs(bloc_concurrency): update example to follow naming conventions

packages/replay_bloc/lib/src/change_stack.dart
**READY**
NO
- refactor(replay_bloc): remove redundant function parameter syntax (closes #3016)
=> refactor(replay_bloc): remove redundant function parameter syntax

examples/flutter_infinite_list/test/posts/bloc/post_bloc_test.dart
**READY**
NO
- fix(flutter_infinite_list): resolve analysis warning
=> fix(flutter_infinite_list): resolve analysis warning

CONTRIBUTING.md
Wiki / Contributing.md update: Added docsify note, and guidance on snippets
Optional, but ready
NO
Added about one paragraph to guide on docsify (which isn't referenced elsewhere) and including to code files.
=> (docs) Contibuting.md Added docsify note, and guidance on snippets

extensions/intellij/README.md, extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml, extensions/vscode/README.md, extensions/vscode/snippets/bloc_test.json
**READY**
NO
Add Snippets for vscode and intellJ for MockBloc, MockCubit. and Fake state.
=> feat(extensions): add snippets for MockBloc, MockCubit, and Fake

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.3.0
=> chore(vscode): v6.3.0

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml, extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml
**READY**
NO
- chore(intellij): v3.2.0
=> chore(intellij): v3.2.0

examples/flutter_firebase_login/test/app/bloc/app_bloc_test.dart
**READY**
NO
Fixed test case to pass CI on example/flutter_firebase_login
=> test(firebase_login): fix failing logout test

docs/_snippets/faqs/bloc_provider_good_1.dart.md
=> docs(FAQs): fix BlocProvider snippet

docs/_snippets/faqs/bloc_provider_bad_1.dart.md
=> docs(FAQs): fix BlocProvider snippet typos bloc_provider_bad_1.dart.md

docs/_snippets/faqs/bloc_provider_good_2.dart.md
=> docs(FAQs): fix BlocProvider snippet typos bloc_provider_good_2.dart.md

packages/bloc_test/pubspec.yaml, packages/bloc_test/test/cubit_bloc_test_test.dart, packages/bloc_test/test/mock_bloc_test.dart
**READY**
NO
- refactor(bloc_test): upgrade to bloc v8.0.2
=> refactor(bloc_test): upgrade to bloc v8.0.2

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- fix: throw uncaught exceptions ([#3070](https://github.com/felangel/bloc/pull/3070))
- chore: upgrade to `bloc v8.0.2`
- docs: update example to follow naming conventions ([#3032](https://github.com/felangel/bloc/pull/3032))
=> chore(bloc_test): v9.0.2

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package.json, extensions/vscode/snippets/bloc.json, extensions/vscode/snippets/freezed_bloc.json, extensions/vscode/src/commands/new-bloc.command.ts, extensions/vscode/src/commands/new-cubit.command.ts, extensions/vscode/src/utils/get-template-setting.ts
**READY**
NO
- feat: add `_onevent` snippet for creating an internal event handler methood
- feat: improve `onevent` snippet to infer default event type
- feat: add new extension settings:
- `bloc.newBlocTemplate.createDirectory` (defaults to true)
- `bloc.newCubitTemplate.createDirectory` (defaults to true)
- refactor: remove deprecated snippets:
- `feventwhen`
- `feventmap`
=> feat(vscode): v6.4.0

examples/flutter_counter/integration_test/app_test.dart
**READY**
NO
- refactor(flutter_counter): remove unnecessary IntegrationTestWidgetsFlutterBinding
=> refactor(flutter_counter): remove unnecessary IntegrationTestWidgetsFlutterBinding

docs/zh-cn/coreconcepts.md
=> docs(coreconcepts): translation improvements (zh-cn)

docs/fluttertodostutorial.md
**READY**
NO
- docs(fluttertodostutorial): fix --desc typo in code snippets
=> docs(fluttertodostutorial): fix --desc typo in code snippets

docs/zh-cn/fluttertimertutorial.md
READY
NO
zh-cn translations for fluttertimertutorial.md
=> docs(fluttertimertutorial): add zh-cn translations

docs/zh-cn/_sidebar.md, docs/zh-cn/fluttertimertutorial.md
**READY**
NO
- docs(fluttertimertutorial): add zh-cn translation to sidebar
=> docs(fluttertimertutorial): add zh-cn translation to sidebar

packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): upgrade to mason 0.1.0-dev.4
=> chore(bloc_tools): upgrade to mason 0.1.0-dev.4

docs/zh-cn/angularcountertutorial.md, docs/zh-cn/blocintellijextension.md, docs/zh-cn/fluttertimertutorial.md
READY
NO
zh-cn translation for angularcountertutorial.md and blocintellijextension.md
=> zh-cn translation

extensions/vscode/src/utils/analyze-dependencies.ts, extensions/vscode/src/utils/get-pubspec-path.ts, extensions/vscode/src/utils/get-pubspec.ts
**READY**
NO
Relies on pubspec.lock instead of pubspec.yaml to check correct bloc versioning (closes #3131).
=> feat(vscode): check outdated version using the pubspec.lock file

extensions/vscode/package-lock.json
**READY**
NO
- chore(vscode): upgrade deps
=> chore(vscode): upgrade deps

extensions/vscode/README.md, extensions/vscode/snippets/bloc_test.json
**READY**
NO
- feat(vscode): add mock snippet
=> feat(vscode): add mock snippet

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- fix: update `BlocObserver` snippet to resolve Dart analyzer warning
- feat: determine versions via `pubspec.lock`
- feat: add `Mock` snippet
- chore: upgrade dependencies
=> chore(vscode): v6.5.0

extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml
**READY**
NO
- feat(intellij): add mock snippet
=> feat(intellij): add mock snippet

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- Support for Mock snippet
=> chore(intellij): v3.3.0

examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart, examples/flutter_todos/test/edit_todo/view/edit_todo_page_test.dart, examples/flutter_todos/test/home/view/home_page_test.dart, examples/flutter_todos/test/stats/view/stats_page_test.dart, examples/flutter_todos/test/todos_overview/view/todos_overview_page_test.dart
**READY**
NO
- refactor(examples): resolve analysis warnings
=> refactor(examples): resolve analysis warnings

docs/_snippets/flutter_bloc_core_concepts/counter_main.dart.md, docs/flutterbloccoreconcepts.md
**READY**
NO
- docs(flutterbloccoreconcepts): enhance `flutter_bloc` usage to include `BlocProvider`
=> docs(flutterbloccoreconcepts): enhance flutter_bloc usage to include BlocProvider

examples/flutter_todos/android/app/build.gradle, examples/flutter_todos/android/build.gradle, examples/flutter_todos/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_todos/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_todos/ios/Runner.xcworkspace/contents.xcworkspacedata, examples/flutter_todos/packages/local_storage_todos_api/pubspec.yaml, examples/flutter_todos/packages/todos_api/pubspec.yaml, examples/flutter_todos/packages/todos_api/test/todos_api_test.dart, examples/flutter_todos/pubspec.lock, examples/flutter_todos/pubspec.yaml, examples/flutter_todos/test/todos_overview/bloc/todos_overview_bloc_test.dart
**READY**
NO
- refactor(flutter_todos): upgrade to Flutter 2.10
=> refactor(flutter_todos): upgrade to Flutter 2.10

examples/flutter_bloc_with_stream/android/.gitignore, examples/flutter_bloc_with_stream/android/app/build.gradle, examples/flutter_bloc_with_stream/android/app/src/main/AndroidManifest.xml, examples/flutter_bloc_with_stream/android/app/src/main/res/drawable-v21/launch_background.xml, examples/flutter_bloc_with_stream/android/app/src/main/res/values-night/styles.xml, examples/flutter_bloc_with_stream/android/build.gradle, examples/flutter_bloc_with_stream/android/gradle/wrapper/gradle-wrapper.properties, examples/flutter_bloc_with_stream/ios/.gitignore, examples/flutter_bloc_with_stream/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_bloc_with_stream/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_bloc_with_stream/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_bloc_with_stream/ios/Runner/Info.plist, examples/flutter_bloc_with_stream/pubspec.yaml, examples/flutter_bloc_with_stream/test/ticker_page_test.dart
**READY**
NO
- refactor(flutter_bloc_with_stream): upgrade to Flutter 2.10
=> refactor(flutter_bloc_with_stream): upgrade to Flutter 2.10

examples/angular_counter/lib/src/counter_page/counter_page_component.dart, examples/angular_counter/pubspec.yaml
**READY**
NO
- refactor(angular_counter): upgrade to Dart 2.16
=> refactor(angular_counter): upgrade to Dart 2.16

examples/flutter_dynamic_form/android/.gitignore, examples/flutter_dynamic_form/android/app/build.gradle, examples/flutter_dynamic_form/android/app/src/main/AndroidManifest.xml, examples/flutter_dynamic_form/android/app/src/main/res/drawable-v21/launch_background.xml, examples/flutter_dynamic_form/android/app/src/main/res/values-night/styles.xml, examples/flutter_dynamic_form/android/build.gradle, examples/flutter_dynamic_form/android/gradle/wrapper/gradle-wrapper.properties, examples/flutter_dynamic_form/ios/.gitignore, examples/flutter_dynamic_form/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_dynamic_form/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_dynamic_form/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_dynamic_form/ios/Runner/Info.plist, examples/flutter_dynamic_form/pubspec.yaml
**READY**
NO
- refactor(flutter_dynamic_form): upgrade to Flutter 2.10
=> refactor(flutter_dynamic_form): upgrade to Flutter 2.10

examples/flutter_form_validation/android/.gitignore, examples/flutter_form_validation/android/app/build.gradle, examples/flutter_form_validation/android/app/src/main/AndroidManifest.xml, examples/flutter_form_validation/android/app/src/main/res/drawable-v21/launch_background.xml, examples/flutter_form_validation/android/app/src/main/res/values-night/styles.xml, examples/flutter_form_validation/android/build.gradle, examples/flutter_form_validation/android/gradle/wrapper/gradle-wrapper.properties, examples/flutter_form_validation/ios/.gitignore, examples/flutter_form_validation/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_form_validation/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_form_validation/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_form_validation/ios/Runner/Info.plist, examples/flutter_form_validation/pubspec.yaml
**READY**
NO
- refactor(flutter_form_validation): upgrade to Flutter 2.10
=> refactor(flutter_form_validation): upgrade to Flutter 2.10

examples/flutter_graphql_jobs/android/.gitignore, examples/flutter_graphql_jobs/android/app/build.gradle, examples/flutter_graphql_jobs/android/app/src/main/AndroidManifest.xml, examples/flutter_graphql_jobs/android/app/src/main/res/drawable-v21/launch_background.xml, examples/flutter_graphql_jobs/android/app/src/main/res/values-night/styles.xml, examples/flutter_graphql_jobs/android/build.gradle, examples/flutter_graphql_jobs/android/gradle/wrapper/gradle-wrapper.properties, examples/flutter_graphql_jobs/ios/.gitignore, examples/flutter_graphql_jobs/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_graphql_jobs/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_graphql_jobs/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_graphql_jobs/ios/Runner/Info.plist, examples/flutter_graphql_jobs/pubspec.yaml
**READY**
NO
- refactor(flutter_graphql_jobs): upgrade to Flutter 2.10
=> refactor(flutter_graphql_jobs): upgrade to Flutter 2.10

examples/github_search/angular_github_search/pubspec.yaml, examples/github_search/common_github_search/pubspec.yaml, examples/github_search/flutter_github_search/android/.gitignore, examples/github_search/flutter_github_search/android/app/build.gradle, examples/github_search/flutter_github_search/android/app/src/main/AndroidManifest.xml, examples/github_search/flutter_github_search/android/app/src/main/res/drawable-v21/launch_background.xml, examples/github_search/flutter_github_search/android/app/src/main/res/values-night/styles.xml, examples/github_search/flutter_github_search/android/build.gradle, examples/github_search/flutter_github_search/android/gradle/wrapper/gradle-wrapper.properties, examples/github_search/flutter_github_search/ios/.gitignore, examples/github_search/flutter_github_search/ios/Flutter/AppFrameworkInfo.plist, examples/github_search/flutter_github_search/ios/Flutter/Debug.xcconfig, examples/github_search/flutter_github_search/ios/Flutter/Release.xcconfig, examples/github_search/flutter_github_search/ios/Runner.xcodeproj/project.pbxproj, examples/github_search/flutter_github_search/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/github_search/flutter_github_search/ios/Runner/Info.plist, examples/github_search/flutter_github_search/pubspec.yaml
**READY**
NO
- refactor(github_search): upgrade to Flutter 2.10
=> refactor(github_search): upgrade to Flutter 2.10

.gitignore, examples/flutter_todos/.vscode/launch.json, extensions/vscode/.vscode/launch.json
**READY**
NO
- chore: track ./vscode/launch.json
=> chore: track ./vscode/launch.json

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.0.3
=> chore(bloc): v8.0.3

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.0.3
=> chore(bloc_test): v9.0.3

docs/_snippets/core_concepts/counter_bloc_stream_usage.dart.md
**READY**
NO
Fix in docs: typo.
=> docs(core_concepts): fix typo in counter_bloc_stream_usage

docs/fluttertodostutorial.md, examples/flutter_todos/lib/todos_overview/bloc/todos_overview_bloc.dart, examples/flutter_todos/lib/todos_overview/bloc/todos_overview_event.dart, examples/flutter_todos/test/todos_overview/bloc/todos_overview_bloc_test.dart, examples/flutter_todos/test/todos_overview/bloc/todos_overview_event_test.dart
**READY**
NO
the TodosOverviewTodoSaved event in the flutter_todos example is not used and should be removed.
=> chore: removing unused TodosOverviewTodoSaved

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v8.1.0
=> chore(hydrated_bloc): v8.1.0

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.5.1
=> chore(vscode): v6.5.1

bricks/README.md, bricks/cubit/CHANGELOG.md, bricks/cubit/LICENSE, bricks/cubit/README.md, bricks/cubit/__brick__/{{#snakeCase}}{{name}}{{/snakeCase}}_cubit.dart, bricks/cubit/__brick__/{{#snakeCase}}{{name}}{{/snakeCase}}_state.dart, bricks/cubit/brick.yaml, bricks/mason.yaml
**READY**
NO
- feat(bricks): add cubit brick
=> feat(bricks): add cubit brick

docs/flutterbloccoreconcepts.md
**READY**
NO
- docs(flutterbloccoreconcepts): context.bloc -> context.read (closes #3300)
=> docs(flutterbloccoreconcepts): context.bloc -> context.read

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.0.0-dev.1
=> chore(hydrated_bloc): v9.0.0-dev.1

packages/hydrated_bloc/lib/src/hydrated_bloc.dart, packages/hydrated_bloc/test/hydrated_cubit_test.dart, packages/hydrated_bloc/test/legacy/hydrated_cubit_legacy_test.dart
**READY**
NO
- fix(hydrated_bloc): update StorageNotFound toString()
=> fix(hydrated_bloc): update StorageNotFound toString()

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.0.0-dev.2
=> chore(hydrated_bloc): v9.0.0-dev.2

bricks/cubit/CHANGELOG.md, bricks/cubit/__brick__/{{#snakeCase}}{{name}}{{/snakeCase}}_cubit.dart, bricks/cubit/__brick__/{{#snakeCase}}{{name}}{{/snakeCase}}_state.dart, bricks/cubit/__brick__/{{name.snakeCase()}}_cubit.dart, bricks/cubit/__brick__/{{name.snakeCase()}}_state.dart, bricks/cubit/brick.yaml
**READY**
NO
- refactor(bricks): upgrade cubit to shorthand lambda syntax
=> refactor(bricks): upgrade cubit to shorthand lambda syntax

README.md
Hello and thank you for Bloc. I appreciate all the hard work that's gone into creating it
I added a link to my 11+ Hours video course about Bloc on YouTube
**READY**
NO
Added a link to the Video Tutorials section of the README.md file
=> docs: add link to bloc course

bricks/hydrated_bloc/CHANGELOG.md, bricks/hydrated_bloc/LICENSE, bricks/hydrated_bloc/README.md, bricks/hydrated_bloc/__brick__/{{name.snakeCase()}}_bloc.dart, bricks/hydrated_bloc/__brick__/{{name.snakeCase()}}_event.dart, bricks/hydrated_bloc/__brick__/{{name.snakeCase()}}_state.dart, bricks/hydrated_bloc/brick.yaml, bricks/mason.yaml
**READY**
NO
- feat(bricks): add hydrated_bloc
=> feat(bricks): add hydrated_bloc

bricks/hydrated_bloc/brick.yaml, bricks/hydrated_cubit/CHANGELOG.md, bricks/hydrated_cubit/LICENSE, bricks/hydrated_cubit/README.md, bricks/hydrated_cubit/__brick__/{{name.snakeCase()}}_cubit.dart, bricks/hydrated_cubit/__brick__/{{name.snakeCase()}}_state.dart, bricks/hydrated_cubit/brick.yaml, bricks/mason.yaml
**READY**
NO
- feat(bricks): add hydrated_cubit
=> feat(bricks): add hydrated_cubit

bricks/README.md, bricks/mason.yaml, bricks/replay_bloc/CHANGELOG.md, bricks/replay_bloc/LICENSE, bricks/replay_bloc/README.md, bricks/replay_bloc/__brick__/{{name.snakeCase()}}_bloc.dart, bricks/replay_bloc/__brick__/{{name.snakeCase()}}_event.dart, bricks/replay_bloc/__brick__/{{name.snakeCase()}}_state.dart, bricks/replay_bloc/brick.yaml
**READY**
NO
- feat(bricks): add replay_bloc
=> feat(bricks): add replay_bloc

bricks/README.md, bricks/mason.yaml, bricks/replay_bloc/brick.yaml, bricks/replay_cubit/CHANGELOG.md, bricks/replay_cubit/LICENSE, bricks/replay_cubit/README.md, bricks/replay_cubit/__brick__/{{name.snakeCase()}}_cubit.dart, bricks/replay_cubit/__brick__/{{name.snakeCase()}}_state.dart, bricks/replay_cubit/brick.yaml
**READY**
NO
- feat(bricks): add replay_cubit
=> feat(bricks): add replay_cubit

examples/github_search/flutter_github_search/lib/search_form.dart
**READY**
NO
- chore(flutter_github_search): fix analysis warnings
=> chore(flutter_github_search): fix analysis warnings

docs/flutterlogintutorial.md
**READY**
NO
- docs(flutter_login_tutorial): fix typo (closes #3357)
=> docs(flutter_login_tutorial): fix typo

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.6.0
=> chore(vscode): v6.6.0

examples/flutter_todos/ios/Runner/Info.plist, examples/flutter_todos/lib/generated_plugin_registrant.dart, examples/flutter_todos/lib/main_development.dart, examples/flutter_todos/lib/main_production.dart, examples/flutter_todos/lib/main_staging.dart, examples/flutter_todos/pubspec.lock, examples/flutter_todos/pubspec.yaml
**READY**
NO
- fix(flutter_todos): remove flutter_services_binding (closes #3367)
=> fix(flutter_todos): remove flutter_services_binding

docs/architecture.md
**READY**
NO
Fixes a broken weather tutorial link in the architecture documentation.
=> docs(architecture): fix broken link

docs/_snippets/recipes_flutter_show_snack_bar/main.dart.md
**READY**
NO
Replace Scaffold.of(context) with ScaffoldMessenger.of(context)
=> Replace Scaffold.of(context) with ScaffoldMessenger.of(context)

docs/pt-br/_sidebar.md, docs/pt-br/coreconcepts.md
**READY**
NO
Translates the core concepts document to pt-br.
=> docs(coreconcepts): add pt-br translation

.github/workflows/ci.yaml
**READY**
NO
- ci: use semantic_pull_request workflow
=> ci: use semantic_pull_request workflow

bricks/bloc/CHANGELOG.md, bricks/bloc/README.md, bricks/bloc/brick.yaml
**READY**
NO
- chore(bricks): bloc brick README updates
=> chore(bricks): bloc brick README updates

bricks/hydrated_bloc/CHANGELOG.md, bricks/hydrated_bloc/README.md, bricks/hydrated_bloc/brick.yaml
**READY**
NO
- chore(bricks): hydrated_bloc brick README updates
=> chore(bricks): hydrated_bloc brick README updates

bricks/replay_bloc/CHANGELOG.md, bricks/replay_bloc/README.md, bricks/replay_bloc/brick.yaml
**READY**
NO
- chore(bricks): replay_bloc brick README updates
=> chore(bricks): replay_bloc brick README updates

bricks/hydrated_cubit/CHANGELOG.md, bricks/hydrated_cubit/README.md, bricks/hydrated_cubit/brick.yaml
**READY**
NO
- chore(bricks): hydrated_cubit brick README updates
=> chore(bricks): hydrated_cubit brick README updates

bricks/replay_cubit/CHANGELOG.md, bricks/replay_cubit/README.md, bricks/replay_cubit/brick.yaml
**READY**
NO
- chore(bricks): replay_cubit brick README updates
=> chore(bricks): replay_cubit brick README updates

packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): upgrade to mocktail ^0.3.0
=> chore(bloc): upgrade to mocktail ^0.3.0

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.1.0
=> chore(bloc): v8.1.0

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.0.0-dev.3
=> chore(hydrated_bloc): v9.0.0-dev.3

packages/replay_bloc/example/ios/Runner.xcodeproj/project.pbxproj, packages/replay_bloc/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/replay_bloc/example/ios/Runner/Info.plist, packages/replay_bloc/example/lib/main.dart, packages/replay_bloc/lib/src/replay_bloc.dart, packages/replay_bloc/pubspec.yaml
**READY**
NO
- refactor(replay_bloc): upgrade to bloc: ^8.1.0
=> refactor(replay_bloc): upgrade to bloc: ^8.1.0

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.2
=> chore(replay_bloc): v0.2.2

docs/_coverpage.md, docs/az/_coverpage.md, docs/cs/_coverpage.md, docs/de-de/_coverpage.md, docs/es/_coverpage.md, docs/fr/_coverpage.md, docs/jp/_coverpage.md, docs/ko-kr/_coverpage.md, docs/migration.md, docs/pt-br/_coverpage.md, docs/ru/_coverpage.md, docs/update-pubspec.js, docs/zh-cn/_coverpage.md
**READY**
NO
- docs: upgrade to bloc v8.1.0
=> docs: upgrade to bloc v8.1.0

docs/pt-br/migration.md
=> docs(migration): v8.1.0 pt-br translation

packages/flutter_bloc/example/linux/flutter/generated_plugins.cmake, packages/flutter_bloc/example/pubspec.yaml, packages/flutter_bloc/example/windows/flutter/generated_plugins.cmake
**READY**
NO
- chore(flutter_bloc): remove path dependency from example pubspec.yaml
=> chore(flutter_bloc): remove path dependency from example pubspec.yaml

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.1.0
=> chore(flutter_bloc): v8.1.0

docs/update-pubspec.js
**READY**
NO
- docs: bump to flutter_bloc v8.1.0
=> docs: bump to flutter_bloc v8.1.0

packages/flutter_bloc/example/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): remove example dependency_overrides
=> chore(flutter_bloc): remove example dependency_overrides

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.1.1
=> chore(flutter_bloc): v8.1.1

packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml
**READY**
NO
- feat(bloc_test): upgrade to bloc: ^8.1.0
=> feat(bloc_test): upgrade to bloc: ^8.1.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.1.0
=> chore(bloc_test): v9.1.0

docs/update-pubspec.js
**READY**
NO
- docs: update to flutter_bloc v8.1.1 and bloc_test v9.1.0
=> docs: update to flutter_bloc v8.1.1 and bloc_test v9.1.0

examples/flutter_firebase_login/analysis_options.yaml, examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart, examples/flutter_firebase_login/packages/authentication_repository/analysis_options.yaml, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/packages/cache/analysis_options.yaml, examples/flutter_firebase_login/packages/cache/pubspec.yaml, examples/flutter_firebase_login/packages/form_inputs/analysis_options.yaml, examples/flutter_firebase_login/packages/form_inputs/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml
**READY**
NO
- chore(firebase_login): upgrade to very_good_analysis 3.0.2
=> chore(firebase_login): upgrade to very_good_analysis 3.0.2

docs/_snippets/flutter_weather_tutorial/data_layer/export_top_level_models.dart.md, docs/_snippets/flutter_weather_tutorial/data_layer/flutter_create_api_client.sh.md, docs/_snippets/flutter_weather_tutorial/data_layer/get_weather_method.dart.md, docs/_snippets/flutter_weather_tutorial/data_layer/location.dart.md, docs/_snippets/flutter_weather_tutorial/data_layer/location.json.md, docs/_snippets/flutter_weather_tutorial/data_layer/location_search_method.dart.md, docs/_snippets/flutter_weather_tutorial/data_layer/open_meteo_api_client_tree.md, docs/_snippets/flutter_weather_tutorial/data_layer/open_meteo_models_barrel_tree.md, docs/_snippets/flutter_weather_tutorial/data_layer/open_meteo_models_tree.md, docs/_snippets/flutter_weather_tutorial/data_layer/weather.dart.md, docs/_snippets/flutter_weather_tutorial/data_layer/weather.json.md, docs/_snippets/flutter_weather_tutorial/repository_layer/repository_models_barrel_tree.md, docs/flutterweathertutorial.md
**READY**
NO
- docs(flutter_weather): update tutorial to use open meteo api
=> docs(flutter_weather): update tutorial to use open meteo api

examples/flutter_todos/analysis_options.yaml, examples/flutter_todos/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_todos/ios/Flutter/Debug.xcconfig, examples/flutter_todos/ios/Flutter/Release.xcconfig, examples/flutter_todos/ios/Podfile, examples/flutter_todos/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_todos/ios/Runner.xcworkspace/contents.xcworkspacedata, examples/flutter_todos/packages/local_storage_todos_api/analysis_options.yaml, examples/flutter_todos/packages/local_storage_todos_api/pubspec.yaml, examples/flutter_todos/packages/todos_api/analysis_options.yaml, examples/flutter_todos/packages/todos_api/pubspec.yaml, examples/flutter_todos/packages/todos_repository/analysis_options.yaml, examples/flutter_todos/packages/todos_repository/pubspec.yaml, examples/flutter_todos/pubspec.lock, examples/flutter_todos/pubspec.yaml
**READY**
NO
- chore(flutter_todos): upgrade to Flutter 3.3.1 and Dart 2.18
=> chore(flutter_todos): upgrade to Flutter 3.3.1 and Dart 2.18

docs/flutterweathertutorial.md
**READY**
NO
- docs(flutter_weather): remove MetaWeather mention
=> docs(flutter_weather): remove MetaWeather mention

.github/workflows/bloc.yaml, .github/workflows/bloc_concurrency.yaml, .github/workflows/bloc_test.yaml
**READY**
NO
- ci: remove deprecated .packages reference
=> ci: remove deprecated .packages reference

packages/bloc_concurrency/test/src/droppable_test.dart
**READY**
NO
- test(bloc_concurrency): droppable coverage
=> test(bloc_concurrency): droppable coverage

bricks/bloc/CHANGELOG.md, bricks/bloc/README.md, bricks/bloc/__brick__/{{name.snakeCase()}}_bloc.dart, bricks/bloc/__brick__/{{name.snakeCase()}}_event.dart, bricks/bloc/__brick__/{{name.snakeCase()}}_state.dart, bricks/bloc/__brick__/{{~ basic_bloc }}, bricks/bloc/__brick__/{{~ basic_event }}, bricks/bloc/__brick__/{{~ basic_state }}, bricks/bloc/__brick__/{{~ equatable_bloc }}, bricks/bloc/__brick__/{{~ equatable_event }}, bricks/bloc/__brick__/{{~ equatable_state }}, bricks/bloc/__brick__/{{~ freezed_bloc }}, bricks/bloc/__brick__/{{~ freezed_event }}, bricks/bloc/__brick__/{{~ freezed_state }}, bricks/bloc/brick.yaml, bricks/bloc/hooks/pre_gen.dart, bricks/bloc/hooks/pubspec.yaml
**READY**
NO
- feat(bricks): bloc v0.2.0
=> feat(bricks): bloc v0.2.0

bricks/cubit/CHANGELOG.md, bricks/cubit/README.md, bricks/cubit/__brick__/{{name.snakeCase()}}_cubit.dart, bricks/cubit/__brick__/{{name.snakeCase()}}_state.dart, bricks/cubit/__brick__/{{~ basic_cubit }}, bricks/cubit/__brick__/{{~ basic_state }}, bricks/cubit/__brick__/{{~ equatable_cubit }}, bricks/cubit/__brick__/{{~ equatable_state }}, bricks/cubit/__brick__/{{~ freezed_cubit }}, bricks/cubit/__brick__/{{~ freezed_state }}, bricks/cubit/brick.yaml, bricks/cubit/hooks/pre_gen.dart, bricks/cubit/hooks/pubspec.yaml
**READY**
NO
- feat(bricks): cubit v0.2.0
=> feat(bricks): cubit v0.2.0

bricks/hydrated_cubit/CHANGELOG.md, bricks/hydrated_cubit/README.md, bricks/hydrated_cubit/__brick__/{{name.snakeCase()}}_cubit.dart, bricks/hydrated_cubit/__brick__/{{name.snakeCase()}}_state.dart, bricks/hydrated_cubit/__brick__/{{~ basic_cubit }}, bricks/hydrated_cubit/__brick__/{{~ basic_state }}, bricks/hydrated_cubit/__brick__/{{~ equatable_cubit }}, bricks/hydrated_cubit/__brick__/{{~ equatable_state }}, bricks/hydrated_cubit/__brick__/{{~ freezed_cubit }}, bricks/hydrated_cubit/__brick__/{{~ freezed_state }}, bricks/hydrated_cubit/brick.yaml, bricks/hydrated_cubit/hooks/pre_gen.dart, bricks/hydrated_cubit/hooks/pubspec.yaml
**READY**
NO
- feat(bricks): hydrated_cubit v0.2.0
=> feat(bricks): hydrated_cubit v0.2.0

bricks/replay_bloc/CHANGELOG.md, bricks/replay_bloc/README.md, bricks/replay_bloc/__brick__/{{name.snakeCase()}}_bloc.dart, bricks/replay_bloc/__brick__/{{name.snakeCase()}}_event.dart, bricks/replay_bloc/__brick__/{{name.snakeCase()}}_state.dart, bricks/replay_bloc/__brick__/{{~ basic_bloc }}, bricks/replay_bloc/__brick__/{{~ basic_event }}, bricks/replay_bloc/__brick__/{{~ basic_state }}, bricks/replay_bloc/__brick__/{{~ equatable_bloc }}, bricks/replay_bloc/__brick__/{{~ equatable_event }}, bricks/replay_bloc/__brick__/{{~ equatable_state }}, bricks/replay_bloc/__brick__/{{~ freezed_bloc }}, bricks/replay_bloc/__brick__/{{~ freezed_event }}, bricks/replay_bloc/__brick__/{{~ freezed_state }}, bricks/replay_bloc/brick.yaml, bricks/replay_bloc/hooks/pre_gen.dart, bricks/replay_bloc/hooks/pubspec.yaml
**READY**
NO
- feat(bricks): replay_bloc v0.2.0
=> feat(bricks): replay_bloc v0.2.0

bricks/replay_cubit/CHANGELOG.md, bricks/replay_cubit/README.md, bricks/replay_cubit/__brick__/{{name.snakeCase()}}_cubit.dart, bricks/replay_cubit/__brick__/{{name.snakeCase()}}_state.dart, bricks/replay_cubit/__brick__/{{~ basic_cubit }}, bricks/replay_cubit/__brick__/{{~ basic_state }}, bricks/replay_cubit/__brick__/{{~ equatable_cubit }}, bricks/replay_cubit/__brick__/{{~ equatable_state }}, bricks/replay_cubit/__brick__/{{~ freezed_cubit }}, bricks/replay_cubit/__brick__/{{~ freezed_state }}, bricks/replay_cubit/brick.yaml, bricks/replay_cubit/hooks/pre_gen.dart, bricks/replay_cubit/hooks/pubspec.yaml
**READY**
NO
- feat(bricks): replay_cubit v0.2.0
=> feat(bricks): replay_cubit v0.2.0

bricks/flutter_bloc_feature/CHANGELOG.md, bricks/flutter_bloc_feature/README.md, bricks/flutter_bloc_feature/brick.yaml, bricks/flutter_bloc_feature/hooks/pre_gen.dart
**READY**
NO
- feat(bricks): flutter_bloc_feature v0.2.0
=> feat(bricks): flutter_bloc_feature v0.2.0

docs/_snippets/flutter_infinite_list_tutorial/post_bloc_transformer.dart.md, docs/flutterinfinitelisttutorial.md
**READY**
NO
Solves  #3556 
While following along the documentation, in the section of PostBloc, the docs introduce the  `events.throttle(duration)` method. This method requires the **stream_transform/stream_transform.dart** package. But the package import statement is not in the code snippet, also there is no mention that this package is required to run the `events.throttle(duration)` method. 
The next code snippet does contain the import statement, but naive developers like me who are following along get stuck. We see the error and don't know what to do. Therefore I think it is necessary that there is some mention to the package import. Thus my Pull Request adds a note instruction and updates the code snippet to include the necessary changes.
=> docs(flutterinfinitelist): add stream_transform import for `throttle` api

docs/fluttertodostutorial.md
The create packages commands were not according to the recent version of very_good, encountered this problem while following the tutorial.
**READY**
NO
The New version of very_good_cli did not support creating packages by writing the directory path instead it has to be provided as the output directory,
=> docs(flutter_todos): update very_good_cli commands in tutorial

extensions/vscode/snippets/flutter_bloc.json
**READY**
NO
- fix(vscode): rename element to bloc in context.select snippet
=> fix(vscode): rename element to bloc in context.select snippet

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.6.2
=> chore(vscode): v6.6.2

.github/workflows/ci.yaml
**READY**
NO
- ci: retain original build job
=> ci: retain original build job

.github/workflows/build.yaml
**READY**
NO
- ci: fix broken build badge
=> ci: fix broken build badge

examples/flutter_firebase_login/analysis_options.yaml, examples/flutter_firebase_login/packages/authentication_repository/analysis_options.yaml, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/packages/cache/analysis_options.yaml, examples/flutter_firebase_login/packages/cache/pubspec.yaml, examples/flutter_firebase_login/packages/form_inputs/analysis_options.yaml, examples/flutter_firebase_login/packages/form_inputs/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml
**READY**
NO
- chore(flutter_firebase_login): update firebase deps
=> chore(flutter_firebase_login): update deps

README.md, docs/_coverpage.md, docs/az/README.md, docs/az/_coverpage.md, docs/cs/README.md, docs/cs/_coverpage.md, docs/de-de/README.md, docs/de-de/_coverpage.md, docs/es/README.md, docs/es/_coverpage.md, docs/fr/README.md, docs/fr/_coverpage.md, docs/jp/README.md, docs/jp/_coverpage.md, docs/ko-kr/README.md, docs/ko-kr/_coverpage.md, docs/pt-br/README.md, docs/pt-br/_coverpage.md, docs/ru/README.md, docs/ru/_coverpage.md, docs/zh-cn/README.md, docs/zh-cn/_coverpage.md, packages/angular_bloc/README.md, packages/bloc/README.md, packages/bloc_concurrency/README.md, packages/bloc_test/README.md, packages/bloc_tools/README.md, packages/flutter_bloc/README.md, packages/hydrated_bloc/README.md, packages/replay_bloc/README.md
**READY**
NO
Remove effective dart badges, as the packages no longer use the package and the package itself is deprecated.
=> docs: remove effective dart badges

packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): upgrade to mocktail ^0.3.0
=> chore(hydrated_bloc): upgrade to mocktail ^0.3.0

packages/hydrated_bloc/README.md
**READY**
NO
- docs(hydrated_bloc): add testing section to README
=> docs(hydrated_bloc): add testing section to README

examples/flutter_weather/test/weather/view/weather_page_test.dart
**READY**
NO
- tests(flutter_weather): minor improvement to weather_page_test.dart
=> test(flutter_weather): minor improvement to weather_page_test.dart

.github/workflows/angular_bloc.yaml, .github/workflows/angular_dart_examples.yaml, .github/workflows/bloc.yaml, .github/workflows/bloc_concurrency.yaml, .github/workflows/bloc_test.yaml, .github/workflows/bloc_tools.yaml, .github/workflows/docs.yaml, .github/workflows/flutter_bloc.yaml, .github/workflows/flutter_examples.yaml, .github/workflows/hydrated_bloc.yaml, .github/workflows/replay_bloc.yaml
**READY**
NO
- ci: upgrade actions
=> ci: upgrade actions

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/example/pubspec.yaml, packages/hydrated_bloc/example/pubspec_overrides.yaml, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.0.0
=> chore(hydrated_bloc): v9.0.0

docs/migration.md
**READY**
NO
- docs(migration): add hydrated_bloc v9.0.0 guide
=> docs(migration): add hydrated_bloc v9.0.0 guide

docs/update-pubspec.js
**READY**
NO
- docs: bump to hydrated_bloc 9.0.0 in update-pubspec script
=> docs: bump to hydrated_bloc 9.0.0 in update-pubspec script

docs/migration.md
**READY**
NO
- docs(migration): fix hydrated_bloc v9.0.0 snippet
=> docs(migration): fix hydrated_bloc v9.0.0 snippet

examples/flutter_weather/pubspec.yaml, examples/flutter_weather/pubspec_overrides.yaml
**READY**
NO
- chore(flutter_weather): upgrade to hydrated_bloc v9.0.0
=> chore(flutter_weather): upgrade to hydrated_bloc v9.0.0

docs/pt-br/migration.md
=> docs(migration): add hydrated_bloc v9.0.0 translation (pt-br)

README.md, docs/_coverpage.md, docs/az/_coverpage.md, docs/cs/_coverpage.md, docs/de-de/_coverpage.md, docs/es/_coverpage.md, docs/fr/_coverpage.md, docs/jp/_coverpage.md, docs/ko-kr/_coverpage.md, docs/pt-br/_coverpage.md, docs/ru/_coverpage.md, docs/zh-cn/_coverpage.md, packages/angular_bloc/README.md, packages/bloc/README.md, packages/bloc_concurrency/README.md, packages/bloc_test/README.md, packages/flutter_bloc/README.md, packages/hydrated_bloc/README.md, packages/replay_bloc/README.md
**READY**
NO
- docs(sponsors): add netguru
=> docs(sponsors): add netguru

docs/faqs.md
**READY**
NO
- docs(faqs): adding events within a bloc (closes #3594)
=> docs(faqs): adding events within a bloc

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v3.4.0
=> chore(intellij): v3.4.0

.github/workflows/bloc.yaml, .github/workflows/bloc_concurrency.yaml, .github/workflows/bloc_test.yaml, .github/workflows/bloc_tools.yaml, .github/workflows/flutter_bloc.yaml, .github/workflows/hydrated_bloc.yaml, .github/workflows/replay_bloc.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19uWbxfOVNTETAYzwyzSsqmOPuqDoLRsw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=EN8W_lK)
**READY**
YES | NO
https://github.com/felangel/bloc/issues/3652
Codecov@v1 deprecated on February 1, 2022.
migrate codecov/codecov-action@v1 to codecov/codecov-action@v3
=> ci: updated codecov v1 to v3

docs/faqs.md
=> docs(faqs): add section on exposing public methods

bricks/README.md
**READY**
NO
Just small fix in Mason repository URL.
=> docs(bricks): fix typo in mason repo url

bricks/flutter_bloc_feature/hooks/pre_gen.dart, bricks/flutter_bloc_feature/hooks/pubspec.yaml
**READY**
NO
- fix(bricks): flutter_bloc_feature remove recase
=> fix(bricks): flutter_bloc_feature remove recase

bricks/flutter_bloc_feature/CHANGELOG.md, bricks/flutter_bloc_feature/brick.yaml
**READY**
NO
- chore(bricks): flutter_bloc_feature v0.2.1
=> chore(bricks): flutter_bloc_feature v0.2.1

docs/assets/style.css
**READY**
NO
- docs: fix sidebar toggle width (closes #3192)
=> docs: fix sidebar toggle width

packages/hydrated_bloc/lib/src/hydrated_storage.dart
**READY**
NO
Updated the documentation to reflect breaking changes in v9.0.0
=> docs(hydrated_bloc): updated docs to reflect v9.0.0 changes

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore: add screenshots to `pubspec.yaml` ([#3708](https://github.com/felangel/bloc/pull/3708))
- refactor: `const` constructor support for `BlocObserver` ([#3704](https://github.com/felangel/bloc/pull/3704))
- refactor: upgrade to Dart 2.19 ([#3699](https://github.com/felangel/bloc/pull/3699))
- remove deprecated `invariant_booleans` lint rule
=> chore(bloc): v8.1.1

packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): upgrade to mocktail v0.3.0
=> chore(bloc_concurrency): upgrade to mocktail v0.3.0

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore: add screenshots to `pubspec.yaml`
- refactor: upgrade to Dart 2.19
- deps: upgrade to `very_good_analysis 3.1.0`
- docs: update example to follow naming conventions
=> chore(bloc_concurrency): v0.2.1

packages/flutter_bloc/example/lib/main.dart, packages/flutter_bloc/example/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): update example to Dart 2.19
=> chore(flutter_bloc): update example to Dart 2.19

packages/flutter_bloc/pubspec.yaml
**READY**
NO
- feat(flutter_bloc): upgrade to bloc ^8.1.1
=> feat(flutter_bloc): upgrade to bloc ^8.1.1

packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): update to bloc ^8.1.1
=> chore(hydrated_bloc): update to bloc ^8.1.1

packages/hydrated_bloc/example/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): update example to Dart 2.19
=> chore(hydrated_bloc): update example to Dart 2.19

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore: add screenshots to `pubspec.yaml` ([#3721](https://github.com/felangel/bloc/pull/3721))
- chore: update example to Dart 2.19 ([#3720](https://github.com/felangel/bloc/pull/3720))
- chore: update to `bloc ^8.1.1` ([#3719](https://github.com/felangel/bloc/pull/3719))
- feat: add `storage.close` ([#3705](https://github.com/felangel/bloc/pull/3705))
- docs: updated docs to reflect v9.0.0 changes ([#3701](https://github.com/felangel/bloc/pull/3701))
- refactor: upgrade to Dart 2.19 ([#3699](https://github.com/felangel/bloc/pull/3699))
- remove deprecated `invariant_booleans` lint rule
=> chore(hydrated_bloc): v9.1.0

packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): upgrade to bloc ^8.1.1
=> chore(bloc_test): upgrade to bloc ^8.1.1

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore: upgrade to `bloc ^8.1.1` ([#3723](https://github.com/felangel/bloc/pull/3723))
- refactor: `BlocObserver` instances to use `const` constructors ([#3713](https://github.com/felangel/bloc/pull/3713))
- refactor: upgrade to Dart 2.19 ([#3699](https://github.com/felangel/bloc/pull/3699))
- remove deprecated `invariant_booleans` lint rule
- docs: fix snippet in `README` ([#3552](https://github.com/felangel/bloc/pull/3552))
=> chore(bloc_test): v9.1.1

packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): upgrade to bloc ^8.1.1
=> chore(replay_bloc): upgrade to bloc ^8.1.1

packages/replay_bloc/example/lib/main.dart, packages/replay_bloc/example/pubspec.yaml, packages/replay_bloc/example/pubspec_overrides.yaml
**READY**
NO
- chore(replay_bloc): update example to Dart 2.19
=> chore(replay_bloc): update example to Dart 2.19

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/example/ios/Flutter/AppFrameworkInfo.plist, packages/replay_bloc/example/ios/Runner.xcodeproj/project.pbxproj, packages/replay_bloc/example/ios/Runner/Info.plist, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.3
=> chore(replay_bloc): v0.2.3

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
YES
- **BREAKING**: feat: upgrade to `ngdart v7.0.0`
- refactor: remove deprecated `invariant_booleans` lint rule
- docs: update example to follow naming conventions
- chore: add screenshots to `pubspec.yaml`
=> chore(angular_bloc): v9.0.0

examples/flutter_firebase_login/test/app/bloc_observer_test.dart, examples/flutter_todos/pubspec.lock
**READY**
NO
- chore: minor updates to firebase_login and flutter_todos
=> chore: minor updates to firebase_login and flutter_todos

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v10.0.0-dev.0
=> chore(angular_bloc): v10.0.0-dev.0

extensions/vscode/package.json, extensions/vscode/src/utils/wrap-with.ts
**READY**
NO
- fix(vscode): wrap with interpolation (closes #3696)
=> fix(vscode): wrap with interpolation

extensions/vscode/.vscode/launch.json, extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/tsconfig.json
**READY**
NO
- chore(vscode): v6.6.3
=> chore(vscode): v6.6.3

docs/_snippets/architecture/blocs_presentation.dart.md
**READY**
NO
`FirstBloc, FirstState` is more consistent in the example compared to  `WeatherCubit, WeatherState`
=> docs(architecture): improve `blocs_presentation.dart.md` snippet

README.md
READY
NO
I have changed the Articles section of the README file with lowercase characters at the beginning.
=> chore: update casing in articles section of README

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.5
=> chore(bloc_tools): v0.1.0-dev.5

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.1.2
=> chore(bloc): v8.1.2

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v10.0.0-dev.1
=> chore(angular_bloc): v10.0.0-dev.1

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.2.2
=> chore(bloc_concurrency): v0.2.2

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.1.2
=> chore(bloc_test): v9.1.2

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.1.3
=> chore(flutter_bloc): v8.1.3

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.1.1
=> chore(hydrated_bloc): v9.1.1

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.4
=> chore(replay_bloc): v0.2.4

examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
**READY**
NO
Fixed a small typo & added a doc string to `toUser` extension, just a little help and I hope this package getting better and better.
=> docs(firebase_login): improve inline api docs in `authentication_repository.dart`

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.1.3
=> chore(bloc_test): v9.1.3

docs/_snippets/core_concepts/counter_bloc_full.dart.md
**READY**
NO
add missing closing bracket `}` in bloc package doc  https://bloclibrary.dev/#/coreconcepts?id=counterbloc
=> docs: add missing closing bracket in `counter_bloc_full.dart.md`

docs/fluttertodostutorial.md
**READY**
NO
The command needs a subcommand that tells what to create, in this case, we use flutter_app for creating a flutter app named flutter_todos followed by a description message.
Old command: 
`very_good create flutter_todos --desc "..."`
New command:
`very_good create flutter_app flutter_todos --desc "..."`
#3859
=> docs(flutter_todos): update `very_good_cli` command

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.1.2
=> chore(hydrated_bloc): v9.1.2

docs/fluttertodostutorial.md
READY
NO
Recent versions of very_good no longer support the flags listed in the docs. An incomplete description of the changes is described [here](https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/site/docs/resources/syntax_changes_in_0_10_0.md). Unmentioned in that file but also broken is the `-o` flag, which the updates here also address.
=> docs(fluttertodostutorial): update `very_good_cli` commands to latest syntax

docs/fluttercountertutorial.md
**READY**
NO
Add missing `view.dart` export barrel file in `fluttercountertutorial.md` [doc page link](https://bloclibrary.dev/#/fluttercountertutorial?id=barrel)
=> docs: add missing export barrel in `fluttercountertutorial.md`

bricks/bloc/CHANGELOG.md, bricks/bloc/LICENSE, bricks/bloc/brick.yaml
**READY**
NO
- chore(bricks): bloc v0.3.0
=> chore(bricks): bloc v0.3.0

bricks/hydrated_bloc/CHANGELOG.md, bricks/hydrated_bloc/LICENSE, bricks/hydrated_bloc/brick.yaml
**READY**
NO
- chore(bricks): hydrated_bloc v0.3.0
=> chore(bricks): hydrated_bloc v0.3.0

bricks/flutter_bloc_feature/CHANGELOG.md, bricks/flutter_bloc_feature/LICENSE, bricks/flutter_bloc_feature/brick.yaml, bricks/flutter_bloc_feature/hooks/pre_gen.dart, bricks/flutter_bloc_feature/hooks/pubspec.yaml
**READY**
NO
- chore(bricks): flutter_bloc_feature v0.3.0
=> chore(bricks): flutter_bloc_feature v0.3.0

examples/flutter_todos/packages/todos_api/lib/src/models/todo.dart
The previous error message was not what the assert was checking. 
**READY**
NO
Changed error message to correctly suggest what the assert was checking
=> fix(flutter_todos): improve assertion message

packages/angular_bloc/pubspec.yaml, packages/bloc/pubspec.yaml, packages/bloc_concurrency/pubspec.yaml, packages/bloc_test/pubspec.yaml, packages/bloc_tools/pubspec.yaml, packages/flutter_bloc/pubspec.yaml, packages/hydrated_bloc/pubspec.yaml, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore: add topics to `pubspec.yaml`
=> chore: add topics to `pubspec.yaml`

packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): support `package:mocktail v1.0.0`
=> chore(bloc_test): support `package:mocktail v1.0.0`

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.1.4
=> chore(bloc_test): v9.1.4

examples/flutter_bloc_with_stream/pubspec.yaml, examples/flutter_complex_list/pubspec.yaml, examples/flutter_counter/pubspec.yaml, examples/flutter_dynamic_form/pubspec.yaml, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_infinite_list/pubspec.yaml, examples/flutter_login/pubspec.yaml, examples/flutter_shopping_cart/pubspec.yaml, examples/flutter_timer/pubspec.yaml, examples/flutter_todos/packages/local_storage_todos_api/pubspec.yaml, examples/flutter_todos/packages/todos_repository/pubspec.yaml, examples/flutter_weather/macos/Flutter/GeneratedPluginRegistrant.swift, examples/flutter_weather/packages/open_meteo_api/pubspec.yaml, examples/flutter_weather/packages/weather_repository/pubspec.yaml, examples/flutter_weather/pubspec.yaml, packages/angular_bloc/pubspec.yaml, packages/bloc/pubspec.yaml, packages/bloc_concurrency/pubspec.yaml, packages/bloc_tools/pubspec.yaml, packages/hydrated_bloc/pubspec.yaml
**READY/**
NO
- chore(deps): upgrade to `package:mocktail` v1.0.0
=> chore(deps): upgrade to `package:mocktail` v1.0.0

extensions/vscode/package.json, extensions/vscode/src/commands/new-bloc.command.ts, extensions/vscode/src/commands/new-cubit.command.ts, extensions/vscode/src/templates/bloc-event.template.ts, extensions/vscode/src/templates/bloc-state.template.ts, extensions/vscode/src/templates/cubit-state.template.ts
**READY**
NO
- feat(vscode): support sealed classes
=> feat(vscode): support sealed classes

extensions/vscode/README.md
**READY**
NO
- docs(vscode): fix badges on README
=> docs(vscode): fix badges on README

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.6.4
=> chore(vscode): v6.6.4

docs/fluttertodostutorial.md
**READY**
NO
docs: Misspell in Todos #3949
=> docs(fluttertodostutorial): fix typo

docs/gettingstarted.md, docs/pt-br/gettingstarted.md
**READY**
NO
Changes:
- updates the getting started doc (pt-br);
- adds code formatting to the `angular_bloc` term following the pattern used in the doc;
=> docs(gettingstarted): pt-br updates

docs/pt-br/recipesflutternavigation.md
**READY**
NO
Changes:
- small updates on Direct Navigation and Route Navigation;
- add Navigation 2.0;
=> docs(recipesflutternavigation): pt-br updates and add Navigation 2.0

docs/cs/README.md, docs/de-de/README.md, docs/es/README.md, docs/fr/README.md, docs/pt-br/README.md, docs/zh-cn/README.md
**READY**
YES
Remove broken link from README files.
=> docs(readme): remove broken link in README files

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.1.5
=> chore(bloc_test): v9.1.5

extensions/vscode/CHANGELOG.md, extensions/vscode/LICENSE, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.6.5
=> chore(vscode): v6.6.5

examples/flutter_todos/pubspec.lock, examples/flutter_todos/pubspec.yaml, examples/flutter_todos/test/edit_todo/view/edit_todo_page_test.dart, examples/flutter_todos/test/home/view/home_page_test.dart, examples/flutter_todos/test/stats/view/stats_page_test.dart, examples/flutter_todos/test/todos_overview/view/todos_overview_page_test.dart
**READY**
NO
- fix(flutter_todos): failing tests due to `pkg:mockingjay`
=> fix(flutter_todos): failing tests due to `pkg:mockingjay`

packages/hydrated_bloc/lib/src/hydrated_bloc.dart, packages/hydrated_bloc/test/cubits/cubits.dart, packages/hydrated_bloc/test/cubits/from_json_state_cubit.dart, packages/hydrated_bloc/test/e2e_test.dart
**READY**
NO
- fix(hydrated_bloc): `fromJson` can safely access `state`
- previously would cause a stack overflow since the `state` getter would call `fromJson`
- closes #3812 #3998
=> fix(hydrated_bloc): `fromJson` can safely access `state`

docs/_snippets/core_concepts/counter_bloc_on_error_output.sh.md, docs/_snippets/core_concepts/counter_bloc_on_transition_output.sh.md, docs/_snippets/core_concepts/simple_bloc_observer_on_event_output.sh.md, docs/_snippets/core_concepts/simple_bloc_observer_on_transition_output.sh.md
READY
NO
Docs expected output been as written as just the event name (seems it was missed in old mapEvent migration) and replaced with the actual output which is Instance of 'CounterIncrementPressed'. Replaced in possible places (as far as i searced). This issue was originally opened here [Issue](https://github.com/felangel/bloc/issues/3992)
=> docs(core_concepts): update `Increment` to `Instance of 'CounterIncrementPressed'`

packages/replay_bloc/lib/src/replay_bloc.dart
**READY**
NO
- chore(replay_bloc): fix inline doc comment macro
=> chore(replay_bloc): fix inline doc comment macro

examples/flutter_firebase_login/android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java, examples/flutter_firebase_login/ios/Podfile, examples/flutter_firebase_login/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_firebase_login/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_firebase_login/lib/theme.dart, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml
**READY**
NO
- chore(flutter_firebase_login): upgrade deps
=> chore(flutter_firebase_login): upgrade deps

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/LICENSE, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.1.3
=> chore(hydrated_bloc): v9.1.3

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/LICENSE, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.5
=> chore(replay_bloc): v0.2.5

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/LICENSE, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.2.3
=> chore(bloc_concurrency): v0.2.3

.github/actions/angular_dart_package/action.yaml, .github/actions/dart_package/action.yaml, .github/actions/flutter_package/action.yaml, examples/angular_counter/pubspec.yaml, examples/github_search/angular_github_search/pubspec.yaml, packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v10.0.0-dev.2
=> chore(angular_bloc): v10.0.0-dev.2

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.1.3
=> chore(bloc): v8.1.3

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.2.4
=> chore(bloc_concurrency): v0.2.4

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): 9.1.6
=> chore(bloc_test): 9.1.6

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.1.4
=> chore(flutter_bloc): v8.1.4

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.1.4
=> chore(hydrated_bloc): v9.1.4

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.6
=> chore(replay_bloc): v0.2.6

examples/flutter_counter/pubspec.yaml, examples/flutter_counter/pubspec_overrides.yaml, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_firebase_login/pubspec_overrides.yaml, examples/flutter_infinite_list/pubspec.yaml, examples/flutter_infinite_list/pubspec_overrides.yaml, examples/flutter_login/pubspec.yaml, examples/flutter_login/pubspec_overrides.yaml, examples/flutter_timer/pubspec.yaml, examples/flutter_timer/pubspec_overrides.yaml, examples/flutter_todos/pubspec_overrides.yaml, examples/github_search/common_github_search/pubspec.yaml, examples/github_search/common_github_search/pubspec_overrides.yaml, examples/github_search/flutter_github_search/pubspec.yaml, examples/github_search/flutter_github_search/pubspec_overrides.yaml
**READY**
NO
- chore: add `pubspec_overrides.yaml` to examples
=> chore: add `pubspec_overrides.yaml` to examples

examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_state.dart
=> chore(flutter_firebase_login): delete unused enum

packages/flutter_bloc/example/pubspec_overrides.yaml, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_consumer.dart, packages/flutter_bloc/lib/src/bloc_listener.dart, packages/flutter_bloc/lib/src/bloc_provider.dart, packages/flutter_bloc/lib/src/bloc_selector.dart, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_consumer_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/bloc_selector_test.dart, packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
- feat(flutter_bloc): override `debugFillProperties`
=> feat(flutter_bloc): override `debugFillProperties`

analysis_options.yaml, examples/flutter_firebase_login/test/app/bloc_observer_test.dart, examples/flutter_firebase_login/test/sign_up/view/sign_up_form_test.dart, packages/replay_bloc/example/lib/main.dart
**READY**
NO
- refactor: additional lint rules
=> refactor: additional lint rules

docs/astro.config.mjs, docs/src/content/docs/fil/index.mdx
**READY**
NO
Pull request for Filipino language localization. This will serve as initial docs for the Fil language. I'll be creating small PRs whenever I can contribute to add language support on other doc files.
=> docs: add fil/index.mdx

docs/src/content/docs/flutter-bloc-concepts.mdx
Fixed the positions of code snippets in the MultiRepositoryProvider section
**READY**
NO
The code snippets showing the use of MultiRepositoryProvider and how it is better than if we nested multiple RepositoryProviders were swapped.
=> docs: fix the positions of `MultiRepositoryProvider` snippets

extensions/vscode/src/utils/get-selected-text.ts
**READY**
NO
- fix(vscode): wrap with preserves `const` (closes #4071)
=> fix(vscode): wrap with preserves `const`

extensions/vscode/src/utils/wrap-with.ts
**READY**
NO
- fix(vscode): wrap with preserves escaping (closes #4071)
=> fix(vscode): wrap with preserves escaping

bricks/bloc/CHANGELOG.md, bricks/bloc/brick.yaml
**READY**
NO
- chore(bricks): bloc v0.3.1
=> chore(bricks): bloc v0.3.1

bricks/cubit/CHANGELOG.md, bricks/cubit/brick.yaml
**READY**
NO
- chore(bricks): cubit v0.2.1
=> chore(bricks): cubit v0.2.1

bricks/hydrated_bloc/CHANGELOG.md, bricks/hydrated_bloc/brick.yaml
**READY**
NO
- chore(bricks): hydrated_bloc v0.3.1
=> chore(bricks): hydrated_bloc v0.3.1

bricks/hydrated_cubit/CHANGELOG.md, bricks/hydrated_cubit/brick.yaml
**READY**
NO
- chore(bricks): hydrated_cubit v0.2.1
=> chore(bricks): hydrated_cubit v0.2.1

bricks/replay_bloc/CHANGELOG.md, bricks/replay_bloc/brick.yaml
**READY**
NO
- chore(bricks): replay_bloc v0.2.1
=> chore(bricks): replay_bloc v0.2.1

bricks/replay_cubit/CHANGELOG.md, bricks/replay_cubit/brick.yaml
**READY**
NO
- chore(bricks): replay_cubit v0.2.1
=> chore(bricks): replay_cubit v0.2.1

bricks/flutter_bloc_feature/CHANGELOG.md, bricks/flutter_bloc_feature/brick.yaml
**READY**
NO
- chore(bricks): flutter_bloc_feature v0.3.1
=> chore(bricks): flutter_bloc_feature v0.3.1

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/gradle/wrapper/gradle-wrapper.properties, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocDialog.java, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateEquatablePropsAction.kt
**READY**
NO
- chore(intellij): update dependencies
=> chore(intellij): update dependencies

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateEquatablePropsAction.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.0.0
=> chore(intellij): v4.0.0

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v10.0.0-dev.3
=> chore(angular_bloc): v10.0.0-dev.3

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.1.4
=> chore(bloc): v8.1.4

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.2.5
=> chore(bloc_concurrency): v0.2.5

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.1.7
=> chore(bloc_test): v9.1.7

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.1.5
=> chore(flutter_bloc): v8.1.5

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v9.1.5
=> chore(hydrated_bloc): v9.1.5

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.7
=> chore(replay_bloc): v0.2.7

docs/src/content/docs/pt-br/why-bloc.mdx
**READY**
NO
- docs: add `pt-br/why-bloc.mdx`
=> docs: add `pt-br/why-bloc.mdx`

.github/actions/dart_package/action.yaml, .github/actions/flutter_package/action.yaml
**READY**
NO
- ci: upgrade to `very_good_coverage@v3`
=> ci: upgrade to `very_good_coverage@v3`

docs/src/content/docs/architecture.mdx
**READY**
NO
In all places Businesses Logic Layer written similar but one written with capitalize
=> docs: fix typo in `architecture.mdx`

docs/astro.config.mjs, docs/package-lock.json, docs/package.json, docs/plugins/rehype-autolink.ts, docs/src/components/starlight/MarkdownContent.astro
**READY**
NO
- docs: add automatic header anchor links
=> docs: add automatic header anchor links

docs/src/content/docs/de/index.mdx
**READY**
NO
- docs: add `de/index.mdx`
=> docs: add `de/index.mdx`

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.0.1 (closes #4166)
=> chore(intellij): v4.0.1

docs/package-lock.json
**READY**
NO
- chore(deps): run `npm update`
=> chore(deps): run `npm update`

docs/src/components/landing/SponsorsGrid.astro
**READY**
NO
- docs: load sponsors images eagerly
=> docs: load sponsors images eagerly

docs/astro.config.mjs
READY
NO
Add RTL in persian and arabic documentation
Closes: #4176
=> docs: set text direction to `rtl` for persian and arabic

packages/flutter_bloc/README.md
**READY*
NO
I fixed the images that appeared incorrect in the documentation of [flutter_bloc](https://pub.dev/packages/flutter_bloc)
=> doc: fix gallery images

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.1.6
=> chore(flutter_bloc): v8.1.6

analysis_options.yaml
**READY**
NO
- refactor: add `missing_code_block_language_in_doc_comment` to `analysis_options.yaml`
=> refactor: add `missing_code_block_language_in_doc_comment` to `analysis_options.yaml`

packages/angular_bloc/pubspec.yaml, packages/bloc/pubspec.yaml, packages/bloc_concurrency/pubspec.yaml, packages/bloc_test/pubspec.yaml, packages/bloc_tools/pubspec.yaml, packages/flutter_bloc/pubspec.yaml, packages/hydrated_bloc/pubspec.yaml, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore: add `funding` to `pubspec.yaml`
=> chore: add `funding` to `pubspec.yaml`

examples/flutter_firebase_login/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_firebase_login/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_firebase_login/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml
**READY**
NO
I needed to make the following changes to run the example on iOS on the Flutter stable channel:
- Upgrade iOS minimum version to 13
- Remove `OTHER_LDFLAGS`
- Upgrade firebase major versions
=> chore(firebase_flutter_login): upgrade deps

packages/flutter_bloc/lib/src/bloc_listener.dart
**READY**
NO
- fix(flutter_bloc): ensure widget is mounted before invoking listener
=> fix(flutter_bloc): ensure widget is mounted before invoking listener

docs/src/content/docs/tutorials/flutter-infinite-list.mdx
**READY**
NO
- Updates tutorial to reflect the latest state of the code
=> docs(flutter_infinite_list): minor tutorial updates

examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart
**READY**
NO
- Removes `Post-` prefix from event handler name 
- Removes unnecessary branching 
- Makes `startIndex` a named parameter for clarity
=> refactor(flutter_infinite_list): simplify `PostFetched` event handler

docs/src/content/docs/zh-cn/tutorials/flutter-counter.mdx
**READY**
NO
add zh-cn translation on Flutter Counter
=> docs(zh-cn): add flutter-counter.mdx

extensions/intellij/intellij_generator_plugin/.gitignore, extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/gradle.properties, extensions/intellij/intellij_generator_plugin/gradle/wrapper/gradle-wrapper.properties, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocAction.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateCubitAction.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateEquatablePropsAction.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- feat(intellij): upgrade platform version to 2022.3/Java 17
- closes #4257
- closes #4231
=> feat(intellij): upgrade platform version to 2022.3/Java 17

docs/src/content/docs/ko/bloc-concepts.mdx
I corrected the part where I entered Korean incorrectly as English
=> docs: fix typo in ko/bloc-concepts.mdx

docs/package-lock.json, docs/package.json, docs/src/styles/landing.css
**READY**
NO
- docs(deps): upgrade astro deps
=> docs(deps): upgrade astro deps

bricks/bloc/CHANGELOG.md, bricks/bloc/brick.yaml, bricks/bloc/hooks/pubspec.yaml
**READY**
NO
- chore(bricks): bloc v0.4.0
=> chore(bricks): bloc v0.4.0

bricks/hydrated_bloc/CHANGELOG.md, bricks/hydrated_bloc/brick.yaml, bricks/hydrated_bloc/hooks/pubspec.yaml
**READY**
NO
- chore(bricks): hydrated_bloc v0.4.0
=> chore(bricks): hydrated_bloc v0.4.0

bricks/replay_bloc/CHANGELOG.md, bricks/replay_bloc/brick.yaml, bricks/replay_bloc/hooks/pubspec.yaml
**READY**
NO
- chore(bricks): replay_cubit v0.3.0
=> chore(bricks): replay_cubit v0.3.0

bricks/flutter_bloc_feature/CHANGELOG.md, bricks/flutter_bloc_feature/brick.yaml, bricks/flutter_bloc_feature/hooks/pre_gen.dart, bricks/flutter_bloc_feature/hooks/pubspec.yaml
**READY**
NO
- chore(bricks): flutter_bloc_feature v0.4.0
=> chore(bricks): flutter_bloc_feature v0.4.0

packages/hydrated_bloc/example/.metadata, packages/hydrated_bloc/example/web/index.html
**READY**
NO
- chore(hydrated_bloc): upgrade example web platform
=> chore(hydrated_bloc): upgrade example web platform

extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): upgrade vscode engine
=> chore(vscode): upgrade vscode engine

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.7.0
=> chore(vscode): v6.7.0

.github/actions/dart_package/action.yaml
**READY**
NO
- ci: upgrade `pana` to `0.22.17`
- uses dartdoc 8.3.0 (see https://github.com/dart-lang/dartdoc/issues/3947)
=> ci: upgrade `pana` to `0.22.17`

docs/src/components/landing/SponsorsGrid.astro
**READY**
NO
- docs: adjust sponsor grid columns
=> docs: adjust sponsor grid columns

examples/flutter_todos/pubspec.lock
**READY**
NO
- chore(flutter_todos): bump deps
=> chore(flutter_todos): bump deps

.github/actions/dart_package/action.yaml, .github/actions/flutter_package/action.yaml
**READY**
NO
- ci: use latest pana and dartdoc
- https://github.com/dart-lang/dartdoc/issues/3947
=> ci: use latest pana and dartdoc

packages/hydrated_bloc/lib/src/hydrated_bloc.dart, packages/hydrated_bloc/test/hydrated_bloc_test.dart
**READY**
NO
- feat(hydrated_bloc): allow overriding storage (closes https://github.com/felangel/bloc/issues/1421)
=> feat(hydrated_bloc): allow overriding storage

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
-  chore(bloc): v9.0.0
=> chore(bloc): v9.0.0

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/README.md, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.3.0
=> chore(bloc_concurrency): v0.3.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v10.0.0
=> chore(bloc_test): v10.0.0

docs/package-lock.json, docs/package.json, docs/src/content/config.ts, docs/src/content/docs/tutorials/ngdart-counter.mdx
**READY**
NO
- docs: upgrade to astro 5
=> docs: upgrade to astro 5

docs/src/content/docs/bloc-concepts.mdx, docs/src/content/docs/ko/bloc-concepts.mdx, docs/src/content/docs/pt-br/bloc-concepts.mdx, docs/src/content/docs/zh-cn/bloc-concepts.mdx
**READY**
NO
- docs: remove confusing note from core concepts
- closes https://github.com/felangel/bloc/issues/4296
=> docs: remove confusing note from core concepts

docs/src/content/docs/tutorials/flutter-login.mdx
**READY**
NO
- Update tutorial to reflect latest code
=> docs(flutter_login): update tutorial to reflect latest code

docs/src/content/docs/tutorials/flutter-weather.mdx
Current link is no longer available, change to the new available link
**READY**
NO
Current 'part' link is not available, change to the new available link.
=> docs: update 'part' keyword link

packages/bloc_tools/lib/src/command_runner.dart, packages/bloc_tools/pubspec.yaml, packages/bloc_tools/test/src/command_runner_test.dart
**READY**
NO
- chore(bloc_tools): upgrade dependencies
=> chore(bloc_tools): upgrade dependencies

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v9.1.0
=> chore(flutter_bloc): v9.1.0

examples/flutter_todos/lib/app/app.dart, examples/flutter_todos/lib/bootstrap.dart, examples/flutter_todos/packages/todos_repository/lib/src/todos_repository.dart, examples/flutter_todos/packages/todos_repository/test/todos_repository_test.dart, examples/flutter_todos/pubspec.lock, examples/flutter_todos/test/app_test.dart, examples/flutter_weather/lib/app.dart, examples/flutter_weather/lib/main.dart, examples/flutter_weather/packages/open_meteo_api/lib/src/open_meteo_api_client.dart, examples/flutter_weather/packages/open_meteo_api/test/open_meteo_api_client_test.dart, examples/flutter_weather/packages/weather_repository/lib/src/weather_repository.dart, examples/flutter_weather/packages/weather_repository/test/weather_repository_test.dart, examples/flutter_weather/test/app_test.dart, examples/github_search/angular_github_search/lib/app_component.dart, examples/github_search/common_github_search/lib/src/github_cache.dart, examples/github_search/common_github_search/lib/src/github_client.dart, examples/github_search/common_github_search/lib/src/github_repository.dart, examples/github_search/flutter_github_search/lib/main.dart, packages/flutter_bloc/README.md, packages/flutter_bloc/lib/src/repository_provider.dart
**READY**
NO
- refactor: update examples to use `RepositoryProvider` new `dispose` API
=> refactor: update examples to use `RepositoryProvider` new `dispose` API

docs/src/content/docs/ar/index.mdx, docs/src/content/docs/de/index.mdx, docs/src/content/docs/es/index.mdx, docs/src/content/docs/fa/index.mdx, docs/src/content/docs/fil/index.mdx, docs/src/content/docs/fr/index.mdx, docs/src/content/docs/index.mdx, docs/src/content/docs/ko/index.mdx, docs/src/content/docs/pt-br/index.mdx, docs/src/content/docs/zh-cn/index.mdx
**READY**
NO
I’m the author of the unofficial[ flutter-bloc.nvim](https://github.com/wa11breaker/flutter-bloc.nvim) plugin for Neovim. This PR adds the integration guide for the plugin to the official Bloc website, helping users to discover, install and configure the plugin in Neovim.
=> docs: add `neovim` integration to `index.mdx`

CONTRIBUTING.md, docs/src/components/tutorials/FlutterPubGetSnippet.astro, docs/src/components/tutorials/flutter-firebase-login/FlutterPackagesGetSnippet.astro, docs/src/components/tutorials/flutter-login/FlutterPackagesGetSnippet.astro, docs/src/components/tutorials/github-search/FlutterPackagesGetSnippet.astro, docs/src/content/docs/tutorials/flutter-counter.mdx, docs/src/content/docs/tutorials/flutter-firebase-login.mdx, docs/src/content/docs/tutorials/flutter-login.mdx, docs/src/content/docs/tutorials/flutter-timer.mdx, docs/src/content/docs/tutorials/flutter-weather.mdx, docs/src/content/docs/tutorials/github-search.mdx, docs/src/content/docs/zh-cn/tutorials/flutter-counter.mdx, examples/github_search/README.md
**READY**
NO
- replace example tutorial snippets with `flutter pub get`
- use a common `FlutterPubSnippet` because it's the same for multiple tutorials
- replace in `CONTRIBUTING.md`
Fixes #4370
=> docs: replace `flutter packages get` with `flutter pub get`

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/LICENSE, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.8
=> chore(bloc_tools): v0.1.0-dev.8

.github/workflows/main.yaml, packages/bloc_lint/analysis_options.yaml, packages/bloc_lint/lib/bloc_lint.dart, packages/bloc_lint/lib/src/diagnostic.dart, packages/bloc_lint/lib/src/lint_rule.dart, packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/rules/avoid_depending_on_flutter.dart, packages/bloc_lint/lib/src/rules/avoid_public_bloc_methods.dart, packages/bloc_lint/lib/src/rules/prefer_bloc_lint.dart, packages/bloc_lint/lib/src/rules/prefer_cubit_lint.dart, packages/bloc_lint/lib/src/rules/rules.dart, packages/bloc_lint/lib/src/text_document.dart, packages/bloc_lint/pubspec.yaml, packages/bloc_lint/test/src/diagnostic_test.dart, packages/bloc_lint/test/src/lint_test_helper.dart, packages/bloc_lint/test/src/linter_test.dart, packages/bloc_lint/test/src/rules/avoid_depending_on_flutter_test.dart, packages/bloc_lint/test/src/rules/avoid_public_bloc_methods_test.dart, packages/bloc_lint/test/src/rules/prefer_bloc_lint_test.dart, packages/bloc_lint/test/src/rules/prefer_cubit_lint_test.dart, packages/bloc_lint/test/src/text_document_test.dart
**READY**
YES
- refactor(bloc_lint)!: migrate away from `pkg:custom_lint`
=> refactor(bloc_lint)!: migrate away from `pkg:custom_lint`

packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/rules/avoid_public_bloc_methods.dart
**READY**
NO
- refactor(bloc_lint): minor cleanup update `allowedMembers`
=> refactor(bloc_lint): minor cleanup update `allowedMembers`

packages/bloc_lint/lib/src/rules/avoid_public_bloc_methods.dart, packages/bloc_lint/pubspec.yaml, packages/bloc_lint/test/src/rules/avoid_public_bloc_methods_test.dart
**READY**
NO
- fix(bloc_lint): `avoid_public_bloc_methods` allows `@override`
=> fix(bloc_lint): `avoid_public_bloc_methods` allows `@override`

examples/flutter_firebase_login/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter_firebase_login/lib/login/cubit/login_cubit.dart, examples/flutter_firebase_login/lib/login/cubit/login_state.dart, examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart, examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_state.dart, examples/flutter_firebase_login/test/login/cubit/login_cubit_test.dart, examples/flutter_firebase_login/test/login/cubit/login_state_test.dart, examples/flutter_firebase_login/test/login/view/login_form_test.dart, examples/flutter_firebase_login/test/sign_up/cubit/sign_up_cubit_test.dart, examples/flutter_firebase_login/test/sign_up/cubit/sign_up_state_test.dart, examples/flutter_firebase_login/test/sign_up/view/sign_up_form_test.dart
**READY**
NO
- fix(flutter_firebase_login): repeated error snackbar
- closes #4399 
- closes #4073
=> fix(flutter_firebase_login): repeated error snackbar

packages/bloc_lint/lib/src/lint_rule.dart, packages/bloc_lint/lib/src/rules/avoid_flutter_imports.dart, packages/bloc_lint/lib/src/rules/avoid_mutable_fields.dart, packages/bloc_lint/lib/src/rules/avoid_public_bloc_methods.dart, packages/bloc_lint/lib/src/rules/prefer_bloc_lint.dart, packages/bloc_lint/lib/src/rules/prefer_cubit_lint.dart, packages/bloc_lint/test/src/rules/avoid_mutable_fields_test.dart
**READY**
NO
- fix(bloc_lint): `avoid_mutable_fields` with explicit type
- chore(bloc_lint): change default severity to warning for all rules
=> fix(bloc_lint): `avoid_mutable_fields` with explicit type

docs/src/content/docs/tutorials/flutter-login.mdx
**READY**
NO
Replaced a missed occurrence of `AuthenticationLogoutRequested` with `AuthenticationLogoutPressed` to align with the app's implementation.
=> docs(flutter_login): update `AuthenticationLogoutRequested` to `AuthenticationLogoutPressed`

packages/bloc_tools/lib/src/command_runner.dart, packages/bloc_tools/lib/src/commands/commands.dart, packages/bloc_tools/lib/src/commands/language_server/language_server_command.dart, packages/bloc_tools/lib/src/lsp/language_server.dart, packages/bloc_tools/lib/src/lsp/text_document.dart, packages/bloc_tools/lib/src/lsp/text_documents.dart, packages/bloc_tools/pubspec.yaml, packages/bloc_tools/test/src/command_runner_test.dart, packages/bloc_tools/test/src/commands/language_server/language_server_command_test.dart, packages/bloc_tools/test/src/lsp/language_server_test.dart, packages/bloc_tools/test/src/lsp/text_document_test.dart
**READY**
NO
- feat(bloc_tools): add `language-server` command
=> feat(bloc_tools): add `language-server` command

packages/bloc_tools/lib/src/commands/language_server/language_server_command.dart, packages/bloc_tools/test/src/command_runner_test.dart, packages/bloc_tools/test/src/commands/language_server/language_server_command_test.dart
**READY**
NO
- chore(bloc_tools): hide `language-server` command
=> chore(bloc_tools): hide `language-server` command

packages/bloc_tools/README.md, packages/bloc_tools/lib/src/command_runner.dart, packages/bloc_tools/lib/src/commands/language_server/language_server_command.dart, packages/bloc_tools/lib/src/commands/lint/lint_command.dart, packages/bloc_tools/test/src/command_runner_test.dart
**READY**
NO
- feat(bloc_tools): simplify language-server and skip update checks
=> feat(bloc_tools): simplify language-server and skip update checks

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/LICENSE, packages/bloc_lint/README.md, packages/bloc_lint/example/main.dart, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.0-dev.0
=> chore(bloc_lint): v0.2.0-dev.0

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.9
=> chore(bloc_tools): v0.1.0-dev.9

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/extension.ts, extensions/vscode/src/language-server/index.ts, extensions/vscode/src/language-server/language-server.ts, extensions/vscode/src/language-server/selectors.ts, extensions/vscode/src/utils/are-bloc-tools-installed.ts, extensions/vscode/src/utils/exec.ts, extensions/vscode/src/utils/index.ts, extensions/vscode/src/utils/install-bloc-tools.ts, extensions/vscode/src/utils/is-dart-installed.ts
**READY**
NO
- feat(vscode): add language server
=> feat(vscode): add language server

extensions/vscode/LICENSE, extensions/vscode/README.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.8.0
=> chore(vscode): v6.8.0

packages/bloc_lint/lib/src/analysis_options.dart, packages/bloc_lint/lib/src/linter.dart, packages/bloc_tools/lib/src/lsp/language_server.dart, packages/bloc_tools/test/src/lsp/language_server_test.dart
**IN DEVELOPMENT**
NO
- fix(bloc_tools): language server on windows (closes #4428)
=> fix(bloc_tools): language server on windows

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/README.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.0-dev.1
=> chore(bloc_lint): v0.2.0-dev.1

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.10
=> chore(bloc_tools): v0.1.0-dev.10

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/language-server/language-server.ts, extensions/vscode/src/utils/are-bloc-tools-installed.ts, extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): v6.8.1
=> chore(vscode): v6.8.1

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/LICENSE, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v9.1.1
=> chore(flutter_bloc): v9.1.1

README.md
**READY**
NO
- chore: minor README updates
=> chore: minor README updates

packages/bloc_lint/lib/all.yaml, packages/bloc_lint/lib/bloc_lint.dart, packages/bloc_lint/lib/recommended.yaml, packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/rules/prefer_void_public_cubit_methods.dart, packages/bloc_lint/lib/src/rules/rules.dart, packages/bloc_lint/test/src/rules/prefer_void_public_cubit_methods_test.dart
**READY**
NO
- feat(bloc_lint): `prefer_void_public_cubit_methods`
=> feat(bloc_lint): `prefer_void_public_cubit_methods`

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/README.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.0-dev.2
=> chore(bloc_lint): v0.2.0-dev.2

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.11
=> chore(bloc_tools): v0.1.0-dev.11

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/gradle.properties, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
Add support for bloc_lint inside of the BLoC IntelliJ Plugin.
=> feat(intellij): add bloc_lint support in IntelliJ BLoC Plugin

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.0
=> chore(intellij): v4.1.0

docs/src/components/lint/BlocLintMultipleRecommendedAnalysisOptionsSnippet.astro, docs/src/components/lint/InstallBlocLintSnippet.astro, docs/src/content/docs/lint/installation.mdx
**READY**
NO
- correct the inconsistencies between singular and plural forms of the term 'rule set'.
- use 'recommanded' instead of 'preconfigured'.
- add example for multiple include on analysis_options.
- add minimal version of IntelliJ plugin.
To merge when new version of IntelliJ plugin gonna be released
=> docs(lint): upgrade installation documentation

extensions/vscode/src/language-server/language-server.ts, extensions/vscode/src/utils/get-dart-version.ts, extensions/vscode/src/utils/index.ts, extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- fix(vscode): add dart sdk constraint for language server (closes #4468)
=> fix(vscode): add dart sdk constraint for language server

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.8.3
=> chore(vscode): v6.8.3

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.1
=> chore(intellij): v4.1.1

.github/actions/angular_dart_package/action.yaml, .github/actions/dart_package/action.yaml, .github/actions/flutter_package/action.yaml, .github/workflows/main.yaml
**READY**
NO
- ci: use `setup-bloc-tools` action
=> ci: use `setup-bloc-tools` action

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/util/CommandLineHelper.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/util/MultiplatformCommandLine.kt
=> fix(intellij): add .bat at the end of exe for windows users

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/BlocGenerator.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/CubitGenerator.kt
**READY**
NO
- fix(intellij): new bloc/cubit invalid newline characters
=> fix(intellij): new bloc/cubit invalid newline characters

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.2
=> chore(intellij): v4.1.2

docs/src/content/docs/fr/lint/index.mdx, docs/src/content/docs/fr/lint/installation.mdx
**READY**
NO
Add french translation for the lint/overview.mdx page of the documentation.
=> docs(lint): french translations

packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/text_document.dart, packages/bloc_lint/test/src/linter_test.dart, packages/bloc_lint/test/src/text_document_test.dart
**READY**
NO
- feat(bloc_lint): support `// ignore_for_file`
- part of #4467
=> feat(bloc_lint): support `// ignore_for_file`

packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/text_document.dart, packages/bloc_lint/test/src/linter_test.dart, packages/bloc_lint/test/src/text_document_test.dart
**READY**
NO
- feat(bloc_lint): support `// ignore` (closes #4467)
=> feat(bloc_lint): support `// ignore`

packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/text_document.dart, packages/bloc_lint/test/src/linter_test.dart, packages/bloc_lint/test/src/text_document_test.dart
**READY**
NO
- feat(bloc_lint): support `// ignore type=lint` (related to #4467)
=> feat(bloc_lint): support `// ignore type=lint`

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.0-dev.3
=> chore(bloc_lint): v0.2.0-dev.3

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.12
=> chore(bloc_tools): v0.1.0-dev.12

extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): upgrade to bloc_tools 0.1.0-dev.12
=> chore(vscode): upgrade to bloc_tools 0.1.0-dev.12

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.8.4
=> chore(vscode): v6.8.4

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt
**READY**
NO
- chore(intellij): upgrade to bloc_tools 0.1.0-dev.12
=> chore(intellij): upgrade to bloc_tools 0.1.0-dev.12

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.3
=> chore(intellij): v4.1.3

.github/workflows/main.yaml
**READY**
NO
- ci: collect scores in dart package checks
=> ci: collect scores in dart package checks

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/util/CommandLineHelper.kt
**READY**
NO
- fix(intellij): include environment during command execution (closes #4497)
=> fix(intellij): include environment during command execution

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.4
=> chore(intellij): v4.1.4

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.13
=> chore(bloc_tools): v0.1.0-dev.13

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): v6.8.5
=> chore(vscode): v6.8.5

.github/actions/dart_compile/action.yaml, .github/workflows/main.yaml
**READY**
NO
- feat(bloc_tools): cross compile for arm64 and x64
=> feat(bloc_tools): cross compile for arm64 and x64

extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- fix(vscode): support for x64 bloc_tools (closes #4512)
=> fix(vscode): support for x64 bloc_tools

packages/bloc_lint/lib/bloc_lint.dart, packages/bloc_lint/lib/src/rules/avoid_public_bloc_methods.dart, packages/bloc_lint/test/src/rules/avoid_public_bloc_methods_test.dart
**READY**
NO
- fix(bloc_lint): `avoid_public_bloc_methods` false positive (closes #4519)
=> fix(bloc_lint): `avoid_public_bloc_methods` false positive

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.0-dev.5
=> chore(bloc_lint): v0.2.0-dev.5

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.14
=> chore(bloc_tools): v0.1.0-dev.14

extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): upgrade to bloc_tools 0.1.0-dev.14
=> chore(vscode): upgrade to bloc_tools 0.1.0-dev.14

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.15
=> chore(bloc_tools): v0.1.0-dev.15

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.8.7
=> chore(vscode): v6.8.7

.github/actions/dart_compile/action.yaml
**READY**
NO
- ci(dart_compile): adjust the generated executable name
=> ci(dart_compile): adjust the generated executable name

analysis_options.yaml, examples/flutter_firebase_login/test/app/bloc_observer_test.dart, examples/flutter_shopping_cart/lib/cart/view/cart_page.dart, examples/flutter_todos/lib/stats/bloc/stats_bloc.dart, examples/flutter_todos/lib/todos_overview/bloc/todos_overview_bloc.dart, packages/bloc_tools/test/src/command_runner_test.dart
**READY**
NO
- refactor: update `analysis_options.yaml`
=> refactor: update `analysis_options.yaml`

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerInstaller.kt
**READY**
NO
- refactor(intellij): use installer api
=> refactor(intellij): use installer api

packages/bloc_lint/lib/src/linter.dart
**READY**
NO
- fix(bloc_lint): ignore `.fvm`
- this is just a quick fix but will open a PR to make the generic fix (exclude .gitignored content from analysis)
=> fix(bloc_lint): ignore `.fvm`

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.0
=> chore(bloc_lint): v0.2.0

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.16
=> chore(bloc_tools): v0.1.0-dev.16

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.8.8 (closes #4539)
=> chore(vscode): v6.8.8

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.6
=> chore(intellij): v4.1.6

docs/src/content/docs/ko/modeling-state.mdx
**READY**
NO
docs: add `ko/modeling-state.mdx`
=> docs(modeling-state): add korean translation

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v10.1.0
=> chore(hydrated_bloc): v10.1.0

packages/bloc_lint/lib/src/rules/avoid_public_bloc_methods.dart, packages/bloc_lint/lib/src/rules/avoid_public_fields.dart, packages/bloc_lint/lib/src/rules/prefer_void_public_cubit_methods.dart, packages/bloc_lint/test/src/rules/avoid_public_bloc_methods_test.dart, packages/bloc_lint/test/src/rules/avoid_public_fields_test.dart, packages/bloc_lint/test/src/rules/prefer_void_public_cubit_methods_test.dart
**READY**
NO
- fix(bloc_lint): include bloc/cubit instances declared in any file (closes #4564)
=> fix(bloc_lint): include bloc/cubit instances declared in any file

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.2.1
=> chore(bloc_lint): v0.2.1

packages/bloc_tools/README.md
**READY**
NO
- docs(bloc_tools): `README.md` improvements
=> docs(bloc_tools): `README.md` improvements

packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml
**READY**
NO
- chore(bloc_tools): v0.1.0-dev.17
=> chore(bloc_tools): v0.1.0-dev.17

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): v6.8.9
=> chore(vscode): v6.8.9

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.7
=> chore(intellij): v4.1.7

packages/bloc_lint/README.md, packages/bloc_lint/lib/all.yaml, packages/bloc_lint/lib/bloc_lint.dart, packages/bloc_lint/lib/recommended.yaml, packages/bloc_lint/lib/src/linter.dart, packages/bloc_lint/lib/src/rules/prefer_bloc.dart, packages/bloc_lint/lib/src/rules/prefer_cubit.dart, packages/bloc_lint/lib/src/rules/prefer_file_naming_conventions.dart, packages/bloc_lint/lib/src/rules/rules.dart, packages/bloc_lint/lib/src/string_case.dart, packages/bloc_lint/test/src/rules/prefer_bloc_test.dart, packages/bloc_lint/test/src/rules/prefer_cubit_test.dart, packages/bloc_lint/test/src/rules/prefer_file_naming_conventions_test.dart, packages/bloc_lint/test/src/text_document_test.dart
**READY**
NO
- feat(bloc_lint): add `prefer_file_naming_conventions` lint
- feat(bloc_lint): rename `PreferBlocLint` -> `PreferBloc` for consistency
- feat(bloc_lint): rename `PreferCubitLint` -> `PreferCubit` for consistency
=> feat(bloc_lint): add `prefer_file_naming_conventions` lint

docs/src/components/lint/BlocLintMultipleRecommendedAnalysisOptionsSnippet.astro, docs/src/components/lint/InstallBlocLintSnippet.astro
**READY**
NO
- docs(linter): update installation snippet
=> docs(linter): update installation snippets

extensions/vscode/README.md
**READY**
NO
- docs(vscode): fix broken link in README
=> docs(vscode): fix broken link in README

docs/src/components/lint-rules/prefer_file_naming_conventions/BadSnippet.mdx, docs/src/components/lint-rules/prefer_file_naming_conventions/GoodSnippet.astro, docs/src/content/docs/lint-rules/prefer_file_naming_conventions.mdx
**READY**
NO
- docs(linter): add `prefer_file_naming_conventions`
=> docs(linter): add `prefer_file_naming_conventions`

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/README.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.3.0
=> chore(bloc_lint): v0.3.0

packages/bloc_tools/lib/src/lsp/language_server.dart, packages/bloc_tools/lib/src/lsp/text_document.dart, packages/bloc_tools/lib/src/lsp/text_documents.dart, packages/bloc_tools/pubspec.yaml, packages/bloc_tools/test/src/lsp/language_server_test.dart, packages/bloc_tools/test/src/lsp/text_document_test.dart
**READY**
NO
- chore(bloc_tools): use `pkg:lsp_server_ce`
=> chore(bloc_tools): use `pkg:lsp_server_ce`

extensions/vscode/package-lock.json
**READY**
NO
- chore(vscode): `npm audit fix`
=> chore(vscode): `npm audit fix`

extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): bump `bloc_tools` version
=> chore(vscode): bump `bloc_tools` version

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.8.10
=> chore(vscode): v6.8.10

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt
**READY**
NO
- chore(intellij): bump `bloc_tools` to `0.1.0-dev.18`
=> chore(intellij): bump `bloc_tools` to `0.1.0-dev.18`

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.8
=> chore(intellij): v4.1.8

docs/package-lock.json
**READY**
NO
- docs(deps): `npm audit fix`
=> docs(deps): `npm audit fix`

.github/actions/angular_dart_package/action.yaml, examples/angular_counter/analysis_options.yaml, examples/angular_counter/pubspec.yaml, examples/angular_counter/pubspec_overrides.yaml, examples/bloc_concurrency_visualizer/pubspec.yaml, examples/flutter_bloc_with_stream/pubspec.yaml, examples/flutter_complex_list/pubspec.yaml, examples/flutter_counter/pubspec.yaml, examples/flutter_dynamic_form/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_form_validation/pubspec.yaml, examples/flutter_infinite_list/pubspec.yaml, examples/flutter_login/pubspec.yaml, examples/flutter_shopping_cart/pubspec.yaml, examples/flutter_timer/pubspec.yaml, examples/flutter_todos/pubspec.lock, examples/flutter_todos/pubspec.yaml, examples/flutter_weather/pubspec.yaml, examples/flutter_wizard/pubspec.yaml, examples/github_search/angular_github_search/analysis_options.yaml, examples/github_search/angular_github_search/pubspec.yaml, examples/github_search/angular_github_search/pubspec_overrides.yaml, examples/github_search/common_github_search/pubspec.yaml, examples/github_search/flutter_github_search/pubspec.yaml
**READY**
NO
- chore(examples): upgrade to `bloc_lint: ^0.3.0`
=> chore(examples): upgrade to `bloc_lint: ^0.3.0`

docs/src/content/docs/flutter-bloc-concepts.mdx
**READY**
NO
- closes https://github.com/felangel/bloc/issues/4592
=> docs(flutter_bloc_concepts): include warnings about `Multi` widgets

packages/bloc_lint/CHANGELOG.md, packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): v0.3.2
=> chore(bloc_lint): v0.3.2

packages/bloc_lint/pubspec.yaml
**READY**
NO
- chore(bloc_lint): support latest version of `_fe_analyzer_shared`
=> chore(bloc_lint): support latest version of `_fe_analyzer_shared`

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/utils/install-bloc-tools.ts
**READY**
NO
- chore(vscode): v6.8.11
=> chore(vscode): v6.8.11

extensions/intellij/intellij_generator_plugin/build.gradle.kts, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intellij): v4.1.9
=> chore(intellij): v4.1.9

docs/src/components/lint-rules/prefer_build_context_extensions/BadSnippet.mdx, docs/src/components/lint-rules/prefer_build_context_extensions/GoodSnippet.astro
**READY**
NO
- docs: update `prefer_build_context_extensions` snippets
=> docs: update `prefer_build_context_extensions` snippets

analysis_options.yaml, examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart, examples/flutter_firebase_login/test/app/bloc/app_bloc_test.dart, examples/flutter_infinite_list/test/posts/bloc/post_event_test.dart, examples/flutter_shopping_cart/test/cart/bloc/cart_event_test.dart, examples/flutter_shopping_cart/test/cart/bloc/cart_state_test.dart, examples/flutter_shopping_cart/test/catalog/bloc/catalog_event_test.dart, examples/flutter_todos/packages/local_storage_todos_api/test/local_storage_todos_api_test.dart, examples/flutter_todos/packages/todos_repository/test/todos_repository_test.dart, examples/flutter_todos/test/edit_todo/bloc/edit_todo_state_test.dart, examples/flutter_todos/test/stats/bloc/stats_state_test.dart, examples/flutter_todos/test/todos_overview/bloc/todos_overview_state_test.dart, examples/flutter_weather/packages/open_meteo_api/test/open_meteo_api_client_test.dart, examples/flutter_weather/test/settings/view/settings_page_test.dart, packages/bloc/test/bloc_event_transformer_test_legacy.dart, packages/bloc/test/blocs/seeded/seeded_bloc.dart, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_tools/e2e/main.dart, packages/bloc_tools/test/src/lsp/text_document_test.dart, packages/hydrated_bloc/test/hive_interference_test.dart, packages/hydrated_bloc/test/hydrated_bloc_test.dart, packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
NO
- refactor: analysis options updates
=> refactor: analysis options updates

packages/bloc/CHANGELOG.md, packages/bloc/LICENSE, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v9.0.1
=> chore(bloc): v9.0.1

packages/angular_bloc/README.md, packages/angular_bloc/analysis_options.yaml, packages/angular_bloc/example/example.dart, packages/angular_bloc/pubspec.yaml, packages/angular_bloc/test/bloc_pipe_test.dart
**READY**
NO
- feat(angular_bloc): add `pkg:bloc_lint`
=> refactor(angular_bloc): add `pkg:bloc_lint`

packages/bloc/README.md, packages/bloc/analysis_options.yaml, packages/bloc/pubspec.yaml
**READY**
NO
- refactor(bloc): add `pkg:bloc_lint`
=> refactor(bloc): add `pkg:bloc_lint`

packages/bloc_concurrency/README.md, packages/bloc_concurrency/analysis_options.yaml, packages/bloc_concurrency/pubspec.yaml, packages/bloc_concurrency/test/src/helpers.dart
**READY**
NO
- refactor(bloc_concurrency): add `pkg:bloc_lint`
=> refactor(bloc_concurrency): add `pkg:bloc_lint`

packages/flutter_bloc/README.md, packages/flutter_bloc/analysis_options.yaml, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_consumer_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/bloc_selector_test.dart, packages/flutter_bloc/test/multi_bloc_listener_test.dart, packages/flutter_bloc/test/multi_bloc_provider_test.dart
**READY**
NO
- refactor(flutter_bloc): add `pkg:bloc_lint`
=> refactor(flutter_bloc): add `pkg:bloc_lint`
