felangel/bloc

examples/angular_counter/lib/src/counter_page/counter_bloc.dart, examples/angular_github_search/lib/src/github_search/bloc/github_search_bloc.dart, examples/flutter_infinite_list/lib/bloc/post_bloc.dart, examples/flutter_login/lib/authentication/authentication_bloc.dart, examples/flutter_login/lib/login/login_bloc.dart, packages/angular_bloc/example/example.dart, packages/angular_bloc/test/bloc_pipe_test.dart, packages/bloc/README.md, packages/bloc/example/main.dart, packages/bloc/lib/src/bloc.dart, packages/bloc/test/helpers/async/async_bloc.dart, packages/bloc/test/helpers/complex/complex_bloc.dart, packages/bloc/test/helpers/counter/counter_bloc.dart, packages/bloc/test/helpers/simple/simple_bloc.dart, packages/flutter_bloc/example/lib/main.dart, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, performance_tests/flutter_bloc/bloc_builder/test_driver/counter_bloc.dart, performance_tests/flutter_bloc/bloc_provider/test_driver/counter_bloc.dart
**READY**
NO
- mapEventToState `state` parameter renamed to `currentState` (#28)
None
=> Update mapEventToState parameter name

packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/transition.dart, packages/bloc/test/bloc_test.dart, packages/bloc/test/helpers/complex/complex_event.dart
**READY**
NO
* Expose `currentState` in Bloc.
* Documentation updates/enhancements in `Bloc` and `Transition`
None
=> Expose currentState in Bloc + Update documentation

docs/logintutorial.md, examples/flutter_login/lib/authentication/authentication_bloc.dart, examples/flutter_login/lib/authentication/authentication_state.dart, examples/flutter_login/lib/main.dart, examples/flutter_login/test/authentication/authentication_bloc_test.dart
**READY**
NO
Updated `AuthenticationState` in flutter_login example to better portray and/or relationships within the state as described by #45 
None
=> update AuthenticationState to better portray and/or relationships of the state

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
Upgrade to bloc `^0.8.0`
None
=> flutter_bloc v0.5.0

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
Updated to `bloc: ^0.8.0`
None
=> angular_bloc v0.3.0

docs/infinitelisttutorial.md, docs/logintutorial.md, examples/flutter_infinite_list/lib/bloc/post_state.dart, examples/flutter_infinite_list/pubspec.yaml, examples/flutter_login/lib/authentication/authentication_bloc.dart, examples/flutter_login/lib/authentication/authentication_event.dart, examples/flutter_login/lib/authentication/authentication_state.dart, examples/flutter_login/lib/common/loading_indicator.dart, examples/flutter_login/lib/home/home_page.dart, examples/flutter_login/lib/login/login_bloc.dart, examples/flutter_login/lib/login/login_event.dart, examples/flutter_login/lib/login/login_form.dart, examples/flutter_login/lib/login/login_page.dart, examples/flutter_login/lib/login/login_state.dart, examples/flutter_login/lib/main.dart, examples/flutter_login/pubspec.yaml, examples/flutter_login/test/authentication/authentication_bloc_test.dart, examples/flutter_login/test/login/login_bloc_test.dart
**READY**
NO
examples/flutter_login enhancements
- Simplified States/Events
None
=> Flutter login Enhancements

docs/infinitelisttutorial.md, examples/flutter_infinite_list/lib/bloc/post_bloc.dart, examples/flutter_infinite_list/lib/bloc/post_state.dart, examples/flutter_infinite_list/lib/main.dart
**READY**
NO
Enhanced examples/flutter_infinite_list
- Simplified States/Events
None
=> Enhance Flutter Infinite List

examples/github_search/README.md, examples/github_search/common_github_search/pubspec.yaml
**READY**
NO
Address comments in #66 (parts 1 & 2).
None
=> examples/github_search improvements (addresses #66)

packages/flutter_bloc/README.md, packages/flutter_bloc/example/lib/main.dart, packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
updated flutter_bloc package documentation/examples to use enum `CounterEvent`
None
=> update flutter_bloc package documentation/examples

packages/angular_bloc/README.md, packages/angular_bloc/example/example.dart, packages/angular_bloc/test/bloc_pipe_test.dart
**READY**
NO
update angular_bloc package documentation/examples to use enum for `CounterEvent`
None
=> update angular_bloc package documentation/examples

examples/angular_counter/lib/src/counter_page/counter_bloc.dart, examples/angular_counter/lib/src/counter_page/counter_page_component.dart, examples/angular_counter/web/main.dart, examples/flutter_infinite_list/lib/bloc/simple_bloc_delegate.dart, examples/flutter_login/lib/main.dart, examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart, performance_tests/flutter_bloc/bloc_builder/test_driver/counter_bloc.dart, performance_tests/flutter_bloc/bloc_builder/test_driver/main.dart, performance_tests/flutter_bloc/bloc_provider/test_driver/counter_bloc.dart, performance_tests/flutter_bloc/bloc_provider/test_driver/main.dart
**READY**
NO
Update example projects + performance tests for minor improvements and to use enum for `CounterEvent`
None
=> update example projects + performance tests

docs/flutterinfinitelisttutorial.md
**READY**
NO
Address #76 
None
=> update const constructor in flutter infinite list tutorial

docs/flutterinfinitelisttutorial.md
**READY**
NO
Addresses #77 
None
=> updated flutter infinite list tutorial to include barrel file

docs/fluttercountertutorial.md
**READY**
NO
Address #81 
None
=> Fix Flutter Infinite List Tutorial

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
=> bloc v0.8.3

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
flutter_bloc v0.5.4 release candidate
None
=> flutter_bloc v0.5.4

docs/flutterangulargithubsearch.md, docs/fluttercountertutorial.md, docs/flutterlogintutorial.md, docs/gettingstarted.md, examples/flutter_infinite_list/lib/bloc/simple_bloc_delegate.dart, examples/flutter_login/lib/main.dart, examples/flutter_weather/lib/main.dart, packages/angular_bloc/pubspec.yaml, packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/example/lib/main.dart, packages/flutter_bloc/pubspec.yaml
**READY**
NO
Update flutter_bloc to use `bloc` v0.6.0
#99 
None
=> flutter_bloc v0.6.0 rc

docs/angularcountertutorial.md, docs/flutterangulargithubsearch.md, docs/fluttercountertutorial.md, docs/flutterinfinitelisttutorial.md, docs/flutterlogintutorial.md, docs/flutterweathertutorial.md, docs/gettingstarted.md, examples/angular_counter/web/main.dart, examples/github_search/angular_github_search/pubspec.yaml, examples/github_search/common_github_search/pubspec.yaml, examples/github_search/flutter_github_search/pubspec.yaml, packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
Update to `bloc` v0.9.0
#99 
None
=> angular_bloc v0.4.0 rc

packages/bloc/CHANGELOG.md
To get the changelog information more quickly.
****READY**/IN DEVELOPMENT/HOLD**
YES | **NO**
To get the changelog information more quickly.
=> From the most recent to the oldest version.

docs/flutterweathertutorial.md
at this part of the tutorial the developer that is following the text doesn't know anything about this Settings Widget
**READY**
NO
Update weather tutorial docs to remove snippets that haven't yet been discussed.
None
=> Removes Settings Widget

docs/_sidebar.md, docs/fluttertodostutorial.md, examples/flutter_todos/lib/blocs/blocs.dart, examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_bloc.dart, examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_event.dart, examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_state.dart, examples/flutter_todos/lib/blocs/stats/stats.dart, examples/flutter_todos/lib/blocs/stats/stats_bloc.dart, examples/flutter_todos/lib/blocs/stats/stats_event.dart, examples/flutter_todos/lib/blocs/stats/stats_state.dart, examples/flutter_todos/lib/blocs/tab/tab.dart, examples/flutter_todos/lib/blocs/tab/tab_event.dart, examples/flutter_todos/lib/blocs/todos/todos.dart, examples/flutter_todos/lib/blocs/todos/todos_event.dart, examples/flutter_todos/lib/blocs/todos/todos_state.dart, examples/flutter_todos/lib/main.dart, examples/flutter_todos/lib/models/todo.dart, examples/flutter_todos/lib/screens/home_screen.dart, examples/flutter_todos/lib/widgets/filter_button.dart, examples/flutter_todos/lib/widgets/filtered_todos.dart, examples/flutter_todos/lib/widgets/stats.dart, packages/angular_bloc/pubspec.yaml
**READY**
NO
New Flutter Todos Tutorial
None
=> Add Flutter Todos Tutorial

packages/bloc/lib/src/bloc.dart, packages/bloc/pubspec.yaml
**READY**
NO
Update RxDart to 0.21.0
=> update rxdart to 0.21.0

extensions/intellij/intellij_generator_plugin/build.gradle
**READY**
YES
Updating the version of the IntelliJ plugin
=> Updated IntelliJ plugin version

extensions/vscode/snippets/snippets.json
**READY**
NO
I've added two snippets in the vs code extension for state class and event class.
=> add snippets for state and event class in vs code extension

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/lib/flutter_bloc.dart, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_listener.dart, packages/flutter_bloc/lib/src/bloc_provider.dart, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_listener_test.dart
**READY**
NO
- Added `BlocListener` to `flutter_bloc` (#201)
None
=> add BlocListener to flutter_bloc

packages/flutter_bloc/lib/src/bloc_listener.dart, packages/flutter_bloc/test/bloc_listener_test.dart
=> Bug fix where BlocListener skips initialState

packages/bloc/README.md, packages/bloc/lib/src/bloc.dart, packages/bloc/test/helpers/complex/complex_bloc.dart
=> Enable Advanced Control/Usage with updated transform

docs/flutterweathertutorial.md
=> Updating flutter_tutorial docs

extensions/vscode/README.md
**READY**
NO
Tiny changes to some text. I find it easier to read for newbies like me.
=> Tiny changes to text in vscode extension README

packages/bloc/pubspec.yaml
**READY**
NO
- Update rxdart to `^0.22.0` (#265)
None
=> update rxdart to ^0.22.0

packages/bloc/README.md, packages/bloc/example/main.dart, packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/bloc_delegate.dart, packages/bloc/test/bloc_delegate_test.dart, packages/bloc/test/bloc_test.dart, packages/bloc/test/helpers/counter/counter_bloc.dart
**READY**
NO
Add `onEvent` to Bloc and BlocDelegate (#259)
None
=> Add onEvent to Bloc and BlocDelegate

extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocDialog.java
**READY**
NO
- Add Autofocus on BlocName Input to IntelliJ Plugin (#298)
None
=> Add Autofocus on BlocName Input to IntelliJ Plugin

packages/bloc/CHANGELOG.md, packages/bloc/example/main.dart, packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/bloc_supervisor.dart, packages/bloc/pubspec.yaml, packages/bloc/test/bloc_delegate_test.dart, packages/bloc/test/bloc_supervisor_test.dart, packages/bloc/test/bloc_test.dart
**READY**
YES
Addresses #304 
- Breaking change which requires a version bump to bloc v0.14.0
=> Improve BlocDelegate Initialization

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/Generator.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_event.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_state.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_event.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc_state.dart.template
**READY**
NO
Addresses #300 
None
=> Fix IntelliJ Bloc Generator Name Casing

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_builder_test.dart
**READY**
NO
- Added optional `condition` to `BlocBuilder` (#315)
None
=> Add optional condition to BlocBuilder

docs/recipesflutterblocaccess.md
- Added informations about `BlocProvider` use with new `BuildContext` provided by a route
**READY**
NO
=> [DOC] Added Route Access informations

examples/flutter_firestore_todos/android/app/google-services.json, examples/flutter_firestore_todos/ios/Runner/GoogleService-Info.plist, examples/flutter_firestore_todos/lib/main.dart, examples/flutter_firestore_todos/lib/models/todo.dart, examples/flutter_firestore_todos/todos_repository/lib/src/todo_entity.dart, examples/flutter_firestore_todos/todos_repository/lib/src/todos_repository.dart, examples/flutter_firestore_todos/todos_repository/lib/src/todos_repository_firebase.dart, examples/flutter_firestore_todos/todos_repository/lib/todos_repository.dart, examples/flutter_firestore_todos/todos_repository/pubspec.yaml
Development
YES | NO
A few sentences describing the overall goals of the pull request's commits.
branch | PR
other_pr_production | [link]()
other_pr_master | [link]()
Outline the steps to test or reproduce the PR here.
```
```
*
=> firestore repo

docs/fluttercountertutorial.md
**READY**
NO
Corrected documentation
branch | PR
other_pr_production | [link]()
other_pr_master | [link]()
Outline the steps to test or reproduce the PR here.
```
```
*
=> corrected CounterEvent to CounterBloc

docs/fluttercountertutorial.md
doc change APP to MyApp
**READY**
NO
when i start the tutorial find this error.
the main function run Widget name is MyApp not APP.
none
=> change Widget Class name

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/action/GenerateBlocAction.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_event.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc_state.dart.template
**READY**
NO
- Append instead of overwrite when existing barrel file exists (#299)
- Minor `Equatable` template updates
None
=> Fix File Overwrites

docs/flutterinfinitelisttutorial.md
YES | NO
A few sentences describing the overall goals of the pull request's commits.
branch | PR
other_pr_production | [link]()
other_pr_master | [link]()
Outline the steps to test or reproduce the PR here.
```
```
*
=> fix grammatical errors 

docs/flutterfirebaselogintutorial.md
**READY**
NO
I am new to flutter universe, this warning in the tutorial seems wrong to me.
N/A
N/A
N/A
NO Impact
=> BlocProvider handles disposing of bloc

docs/flutterangulargithubsearch.md
**READY**
NO
Fix bug in the flutter github example code
=> Fix BlocBuilder in flutter github example

docs/flutterfirestoretodostutorial.md
=> Fix typo in flutterfirestoretodostutorial.md

docs/flutterfirestoretodostutorial.md
Remove files that don't exist anymore
https://github.com/felangel/bloc/tree/master/examples/flutter_firestore_todos/todos_repository/lib
**READY**
NO
=> Update file structure in flutter firestore todos example

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/example/lib/main.dart, packages/flutter_bloc/example/pubspec.yaml, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_listener.dart, packages/flutter_bloc/lib/src/bloc_provider.dart, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/multi_bloc_listener_test.dart, packages/flutter_bloc/test/multi_bloc_provider_test.dart
**READY**
YES
- Update `flutter_bloc` to use `bloc ^v0.16.0`
- Breaking changes to be published in `flutter_bloc v0.22.0`
=> update flutter_bloc to use bloc v0.16.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
YES
- Update to use `bloc ^1.0.0`
Breaking change that will be included in flutter_bloc v1.0.0
=> flutter_bloc v1.0.0

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
YES
- Update to use `bloc ^1.0.0`
- Breaking changes included in `angular_bloc v1.0.0`
=> angular_bloc v1.0.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- Update to bloc v1.0.0
None
=> bloc_test v1.0.0

CONTRIBUTING.md
**READY**
NO
For contributing a translation might be helpful to provide a default set of TODOs people can copy to their PRs.
=> Add tips into contributing

README.md
Removed outdated tutorials and added a new one dealing with the newest package version.
**READY**
NO
Updated the community tutorials section to include the ones dealing with the latest package version.
=> Updated the community tutorials section

packages/bloc/README.md, packages/bloc/analysis_options.yaml, packages/bloc/lib/bloc.dart, packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/bloc_delegate.dart, packages/bloc/lib/src/transition.dart, packages/bloc/pubspec.yaml, packages/bloc/test/bloc_delegate_test.dart, packages/bloc/test/bloc_test.dart, packages/bloc/test/helpers/complex/complex_bloc.dart, packages/bloc/test/helpers/counter/counter.dart, packages/bloc/test/helpers/helpers.dart, packages/bloc/test/transition_test.dart
**READY**
NO
- Adhere to [Effective Dart](https://github.com/tenhobi/effective_dart) (#561)
None
=> apply effective-dart style to bloc package

.gitignore, packages/flutter_bloc/README.md, packages/flutter_bloc/analysis_options.yaml, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_listener.dart, packages/flutter_bloc/lib/src/bloc_provider.dart, packages/flutter_bloc/lib/src/multi_bloc_listener.dart, packages/flutter_bloc/lib/src/multi_bloc_provider.dart, packages/flutter_bloc/lib/src/multi_repository_provider.dart, packages/flutter_bloc/lib/src/repository_provider.dart, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/multi_bloc_listener_test.dart, packages/flutter_bloc/test/multi_bloc_provider_test.dart, packages/flutter_bloc/test/multi_repository_provider_test.dart, packages/flutter_bloc/test/repository_provider_test.dart
**READY**
NO
- Adhere to [Effective Dart](https://github.com/tenhobi/effective_dart) (#561)
None
=> apply effective-dart style to flutter_bloc package

packages/bloc/analysis_options.yaml, packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/bloc_delegate.dart, packages/bloc/lib/src/bloc_supervisor.dart, packages/bloc/lib/src/transition.dart, packages/bloc/pubspec.yaml
**READY**
NO
- Adhere to [Effective Dart](https://github.com/tenhobi/effective_dart) v1.1.0 (#561)
None
=> update effective_dart to v1.1.0

packages/angular_bloc/README.md, packages/angular_bloc/analysis_options.yaml, packages/angular_bloc/lib/src/pipes/bloc_pipe.dart, packages/angular_bloc/pubspec.yaml
**READY**
NO
- Adhere to [Effective Dart](https://github.com/tenhobi/effective_dart) (#561)
None
=> apply effective-dart style to angular_bloc package

packages/bloc_test/README.md, packages/bloc_test/analysis_options.yaml, packages/bloc_test/pubspec.yaml
**READY**
NO
- Adhere to [Effective Dart](https://github.com/tenhobi/effective_dart) (#561)
None
=> apply effective-dart style to bloc_test package

packages/bloc_test/example/main.dart, packages/bloc_test/lib/bloc_test.dart, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/lib/src/emits_exactly.dart, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/bloc_test_test.dart, packages/bloc_test/test/emits_exactly_test.dart, packages/bloc_test/test/helpers/async_counter_bloc.dart, packages/bloc_test/test/helpers/helpers.dart, packages/bloc_test/test/helpers/multi_counter_bloc.dart, packages/bloc_test/test/helpers/sum_bloc.dart
**READY**
NO
- Add `blocTest` (addresses #611)
- Add `emitsExactly` (addresses #611)
None
=> add blocTest and emitsExactly

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- bloc v2.0.0
- new major version of bloc
=> bloc v2.0.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/multi_bloc_provider_test.dart
**READY**
YES
- Update to bloc v2.0.0
Breaking change published in flutter_bloc v2.0.0
=> flutter_bloc v2.0.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/pubspec.yaml
**READY**
YES
- Update to bloc v2.0.0
- Breaking changes published in bloc_test v2.0.0
=> bloc_test v2.0.0

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/README.md, packages/angular_bloc/pubspec.yaml
**READY**
YES
- Update to bloc v2.0.0
- Breaking change published in angular_bloc v2.0.0
=> angular_bloc v2.0.0

extensions/vscode/snippets/snippets.json
**READY**
NO
Update vs code extension snippets. Change `builder` to `create` in providers.
=> Change `builder` to `create` in providers snippets

CONTRIBUTING.md, README.md, docs/_coverpage.md, docs/blocvscodeextension.md, docs/cs/README.md, docs/cs/_coverpage.md, docs/cs/blocvscodeextension.md, docs/fr/README.md, docs/fr/_coverpage.md, docs/ko-kr/README.md, docs/ko-kr/_coverpage.md, docs/pt-br/README.md, docs/pt-br/_coverpage.md, extensions/vscode/README.md, packages/angular_bloc/README.md, packages/bloc/README.md, packages/bloc_test/README.md, packages/flutter_bloc/README.md
**READY**
NO
Replaces all occurrences of Gitter to Discord.
This PR will affect: nothing
=> Replace Gitter with Discord

docs/pt-br/whybloc.md
From: Desenvolvedor apps rápidos e reativos.
to: Desenvolver apps rápidos e reativos.
**READY**
NO
=> fix word in the docs pt-br whybloc.md

docs/flutterbloccoreconcepts.md, packages/flutter_bloc/README.md, packages/flutter_bloc/lib/src/bloc_consumer.dart, packages/flutter_bloc/test/bloc_consumer_test.dart
**READY**
NO
Add `BlocConsumer` to `flutter_bloc` (https://github.com/felangel/bloc/issues/545)
- New Feature which will be included in `flutter_bloc v3.1.0`
=> Add BlocConsumer

CONTRIBUTING.md
**READY**
NO
Updates Contributing so the checklist contains `Naming Conventions` and changes list style from `*` to `-` to keep it in sync with the rest of the markdowns.
Also, we might want to ping people so they can translate this page. :-)
=> Add Naming Conventions to Contributing list

docs/cs/README.md
**READY**
NO
In docs, there were some things not up to date with the English version. Please, also ping translators when changes to README.md occurs. :-)
=> Make czech docs readme up to date

docs/_sidebar.md, docs/faqs.md
**READY**
NO
- Add FAQs section to documentation (#789)
- None
=> Add FAQs to Docs

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/bloc_test_test.dart, packages/bloc_test/test/helpers/helpers.dart, packages/bloc_test/test/helpers/side_effect_counter_bloc.dart
**READY**
NO
- Add `verify` to `blocTest` (#781)
- Non-breaking change which will be included in `bloc_test v3.1.0`
=> Add verify to blocTest

.github/workflows/main.yaml
**READY**
NO
- update ci to use latest stable version (1.12.13+hotfix.7)
=> update ci to use v1.12.13+hotfix.7

docs/cs/flutterangulargithubsearch.md, docs/cs/flutterfirebaselogintutorial.md, docs/cs/flutterfirestoretodostutorial.md, docs/cs/flutterinfinitelisttutorial.md, docs/cs/flutterlogintutorial.md, docs/cs/fluttertimertutorial.md, docs/cs/fluttertodostutorial.md, docs/cs/flutterweathertutorial.md, docs/fr/flutterinfinitelisttutorial.md, docs/fr/flutterlogintutorial.md, docs/fr/fluttertimertutorial.md
**READY**
NO
This PR updates the equatable dependencies which had not been updated in some translated docs.
=> Update docs equatable dependencies to 1.0.0

docs/cs/fluttertodostutorial.md, docs/faqs.md, docs/flutterbloccoreconcepts.md, docs/fluttertodostutorial.md, docs/fr/flutterinfinitelisttutorial.md
=> Docs spelling fixes

docs/cs/fluttertimertutorial.md, docs/fluttertimertutorial.md, docs/fr/fluttertimertutorial.md, docs/ru/fluttertimertutorial.md, examples/flutter_timer/lib/bloc/timer_bloc.dart
**READY**
NO
#831 did not fully fix the issue.
=> Replace incorrect pause with resume in timer tutorial

examples/angular_counter/pubspec.yaml
=> Format pubspec.yaml

docs/es/testing.md
**READY**
NO
Provide spanish translation to `testing.md`.
=> Provide spanish translation to testing.md

docs/es/architecture.md
**READY**
NO
Provide spanish translation to `architecture.md`.
=> Provide spanish translation to architecture.md

docs/es/blocnamingconventions.md
**READY**
NO
Provide spanish translation to `blocnamingconventions.md`.
=> Provide Spanish translation for blocnamingconventions.md

docs/flutterweathertutorial.md, docs/zh-cn/flutterweathertutorial.md, examples/flutter_weather/lib/widgets/weather.dart
**READY**
NO
- Cover `Completer` completing in `examples/flutter_weather`.
=> Update examples/flutter_weather to cover completing the Completer

docs/ru/flutterweathertutorial.md
**READY**
NO
Russian docs translation to include #887
=> Update RU translations to include #887

.github/DOCS_ISSUE_TEMPLATE.md, CONTRIBUTING.md
**READY**
You did merge the last PR too soon. Anyway, We found in https://github.com/JasonEtco/create-an-issue/issues/41 that you cannot assign anyone. So I removed assignees and kept the translators only in the docs. Otherwise, an error will be raised.
=> Enhance docs workflow

docs/cs/blocnamingconventions.md, docs/cs/flutterweathertutorial.md
**READY**
Translated naming conventions + updated weather example (https://github.com/felangel/bloc/issues/888). It is not translated yet, as the examples are very long, so I just updated it. I will translate them in the summer, possibly. :-)
=> Translate naming conventions

packages/bloc/test/bloc_delegate_test.dart, packages/bloc/test/bloc_test.dart
=> Remove type from unused parameters

extensions/intellij/intellij_generator_plugin/src/main/resources/templates/with_equatable/bloc.dart.template, extensions/intellij/intellij_generator_plugin/src/main/resources/templates/without_equatable/bloc.dart.template, extensions/vscode/src/templates/bloc.template.ts
=> Make templates comments consistent with snippets

.github/workflows/main.yaml
**READY**
NO
Upgrade CI to use Flutter Stable 1.12.13+hotfix.8
None
=> Upgrade CI to use Flutter Stable 1.12.13+hotfix.8

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/utils/analyze-dependencies.ts
**READY**
NO
Update latest package versions:
- bloc_test -> ^4.0.0
- equatable -> ^1.1.0
- flutter_bloc -> ^3.2.0
None
=> Update VSCode Bloc to v3.3.0

docs/ru/recipesflutterblocaccess.md
…cs for 46d81c4
**READY**
NO
Add Named Route Access Recipe to docs/recipesflutterblocaccess: ru docs translations for 46d81c4
*
=> Add Named Route Access Recipe to docs/recipesflutterblocaccess: ru docs for 46d81c4

docs/pt-br/recipesflutterblocaccess.md, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_listener.dart
READY
NO
It may not be a big deal but i think calling these variables blocs gives more meaning to the code, because in fact, they're blocs.
=> renaming variables

.github/workflows/main.yaml
**READY**
NO
Update CI to Flutter v1.12.13+hotfix.9
None
=> Update CI to Flutter v1.12.13+hotfix.9

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
YES
- v4.0.0-dev.1 release
=> package:bloc v4.0.0-dev.1

docs/flutterfirebaselogintutorial.md, docs/flutterinfinitelisttutorial.md, examples/flutter_firebase_login/lib/login/bloc/login_bloc.dart, examples/flutter_firebase_login/lib/register/bloc/register_bloc.dart, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_infinite_list/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_infinite_list/lib/bloc/post_bloc.dart, examples/flutter_infinite_list/lib/bloc/simple_bloc_delegate.dart, examples/flutter_infinite_list/pubspec.yaml, packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/helpers/debounce_counter_bloc.dart, packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**IN PROGRESS**
YES
- `flutter_bloc v4.0.0-dev.1`
- `bloc_test v5.0.0-dev.1`
=> package:flutter_bloc v4.0.0-dev.1, package:bloc_test v5.0.0-dev.1

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
YES
- Update to `bloc ^4.0.0-dev.1`
=> package:angular_bloc v4.0.0-dev.1

packages/bloc/lib/src/bloc.dart
Code for [my comment](https://github.com/felangel/bloc/pull/1017#issuecomment-612026137)
Status: **IN DEVELOPMENT**
=> mv distinct, rm where(til opposite proven)

.github/workflows/main.yaml
**HOLD**
NO
actions/cache has been a big bottleneck for the ci so trying without it to see the diff.
None
=> remove actions/cache step from ci

README.md, docs/jp/README.md, docs/pt-br/README.md
**READY**
NO
Added 2 new written recourses to the docs:
- [Using Google´s Flutter Framework for the Development of a Large-Scale Reference Application
](https://epb.bibl.th-koeln.de/frontdoor/index/index/docId/1498)
- [DevonFw Flutter Guide](https://github.com/devonfw-forge/devonfw4flutter)
NONE
NONE
NONE
NONE
=> Add Written Resources to docs/README.md

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/example/example.dart, packages/angular_bloc/pubspec.yaml, packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml, packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- update angular_bloc, bloc_test, and flutter_bloc to bloc v4.0.0-dev.3
=> update angular_bloc, bloc_test, and flutter_bloc to bloc v4.0.0-dev.3

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/example/example.dart, packages/angular_bloc/pubspec.yaml, packages/bloc/CHANGELOG.md, packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml, packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/example/ios/Runner.xcodeproj/project.pbxproj, packages/flutter_bloc/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, packages/flutter_bloc/example/lib/main.dart, packages/flutter_bloc/pubspec.yaml
**READY**
YES
- update `angular_bloc`, `bloc_test`, and `flutter_bloc` to use `bloc v4.0.0-dev.4`
=> update angular_bloc, bloc_test, and flutter_bloc to bloc v4.0.0-dev.4

packages/bloc/CHANGELOG.md, packages/bloc/README.md, packages/bloc/example/pubspec.yaml, packages/bloc/lib/src/bloc.dart, packages/bloc/pubspec.yaml
**READY**
YES
`package:bloc` -> v4.0.0
- Changes to be published in v4.0.0 of bloc.
=> bloc v4.0.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
YES
- Upgrade to `bloc ^4.0.0`
=> bloc_test v5.0.0

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
YES
- Update to `bloc ^4.0.0`
=> angular_bloc v4.0.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/example/analysis_options.yaml, packages/flutter_bloc/example/pubspec.yaml, packages/flutter_bloc/pubspec.yaml
**READY**
YES
- Update to `bloc: ^4.0.0`
- Update to `provider: ^4.0.5`
=> flutter_bloc v4.0.0

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/utils/analyze-dependencies.ts
**READY**
NO
- Update VSCode extension to use latest versions of:
- `equatable`
- `bloc`
- `flutter_bloc`
- `angular_bloc`
=> vscode-bloc v3.5.0

docs/es/README.md
**READY**
NO
Just a minor spanish translation on the readme docs.
References #1135
=> docs: es translation bloc library basics and beyond

docs/zh-cn/README.md
**READY**
NO
Translated latest additions -> #1135, revised a word on line 145.
```
```
=> Translated the addition, revised a word

.github/workflows/main.yaml, docs/cs/fluttertodostutorial.md, docs/fluttertodostutorial.md, docs/fr/fluttertodostutorial.md, docs/jp/fluttertodostutorial.md, docs/pt-br/fluttertodostutorial.md, docs/ru/fluttertodostutorial.md, docs/zh-cn/fluttertodostutorial.md, examples/flutter_firestore_todos/lib/screens/add_edit_screen.dart, examples/flutter_firestore_todos/lib/screens/details_screen.dart, examples/flutter_firestore_todos/lib/widgets/filter_button.dart, examples/flutter_firestore_todos/lib/widgets/stats.dart, examples/flutter_firestore_todos/lib/widgets/todo_item.dart, examples/flutter_shopping_cart/lib/cart/my_cart.dart, examples/flutter_shopping_cart/lib/catalog/my_catalog.dart, examples/flutter_todos/lib/screens/add_edit_screen.dart, examples/flutter_todos/lib/screens/details_screen.dart, examples/flutter_todos/lib/widgets/filter_button.dart, examples/flutter_todos/lib/widgets/stats.dart, examples/flutter_todos/lib/widgets/todo_item.dart
**READY**
NO
- Upgrade ci to latest stable version of Flutter (v1.17.0)
=> ci: upgrade to flutter v1.17.0

docs/fr/faqs.md, docs/fr/flutterbloccoreconcepts.md
=> Stefan yyc/master

docs/zh-cn/faqs.md
**READY**
NO
Included the change from #1169
=> included the latest update

.github/workflows/main.yaml
**READY**
NO
Upgrade ci to v1.17.1
=> ci: upgrade to flutter v1.17.1

docs/fr/blocintellijextension.md, docs/fr/blocnamingconventions.md, docs/fr/blocvscodeextension.md, docs/fr/faqs.md
**READY**
NO
Added the translation from this issue [1169](https://github.com/felangel/bloc/issues/1169)
=> Update translation to french

.github/workflows/angular_bloc.yaml, .github/workflows/bloc.yaml, .github/workflows/bloc_test.yaml, .github/workflows/flutter_bloc.yaml
**READY**
NO
- Upload coverage to codecov with new smart pipeline
=> ci: upload coverage to codecov

.github/workflows/angular_dart_examples.yaml, .github/workflows/ci.yaml, .github/workflows/dart_examples.yaml, .github/workflows/flutter_examples.yaml
**READY**
NO
- fix optional test command in ci
=> ci: fix optional test command

examples/flutter_form_validation/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_form_validation/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, examples/flutter_form_validation/lib/bloc/my_form_bloc.dart, examples/flutter_form_validation/lib/bloc/my_form_event.dart, examples/flutter_form_validation/lib/bloc/my_form_state.dart, examples/flutter_form_validation/lib/main.dart, examples/flutter_form_validation/lib/models/email.dart, examples/flutter_form_validation/lib/models/models.dart, examples/flutter_form_validation/lib/models/password.dart, examples/flutter_form_validation/pubspec.yaml
**READY**
NO
improve flutter_form_validation example to use formz package
=> docs: improve flutter_form_validation example to use formz

docs/es/README.md, docs/es/blocvscodeextension.md
**READY**
NO
Provide `blocvscodeextension.md` spanish translation and the flutter tutorials at the readme with a better rephrasing to avoid repeating words (which makes reading boring IMO).
References #1196
=> Spanish docs update

packages/flutter_bloc/lib/src/multi_bloc_listener.dart
READY
NO
Documentation spelling modification
=> fix: documentation spelling

docs/ru/flutterbloccoreconcepts.md
**READY**
NO
Removed duplicate text
=> Removed duplicate text (Documentation Russian translation)

docs/ru/flutterbloccoreconcepts.md
**READY**
YES
Added missing letter (Russian translation mistake)
=> Added missing letter (Russian translation mistake)

docs/ru/fluttertimertutorial.md
**READY**
NO
Removed duplicated text in English for the Russian version of the documentation
=> Removed duplicated text in English for the Russian documentation

docs/ru/flutterinfinitelisttutorial.md
**READY**
YES
Updated Russian documentation for flutter infinite list tutorial
=> Updated Russian documentation

docs/ru/flutterlogintutorial.md
**READY**
NO
Removed duplicated text which is translated
=> Removed duplicated text which is translated (Russian translation)

docs/es/flutterbloccoreconcepts.md
=> Repeated traduction in BlocProvider  pharagrap.

docs/zh-cn/recipesfluttershowsnackbar.md
**READY**
NO
Translate `recipesfluttershowsnackbar.md` to zh-cn.
=> Translation to zh-cn: recipesfluttershowsnackbar.md

docs/zh-cn/recipesflutterblocaccess.md, docs/zh-cn/recipesflutternavigation.md
**READY**
NO
Translate recipesflutternavigation.md to zh-cn.
=> Translation to zh-cn: recipesflutternavigation.md

docs/fr/README.md
=> Fully translated Readme.md to french

examples/flutter_form_validation/lib/main.dart
=> Correct the condition for the form_validation

docs/_snippets/flutter_firestore_todos_tutorial/authentication_bloc.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/authentication_event.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/authentication_state.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/entities_barrel.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/firebase_todos_repository.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/firebase_user_repository.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/main.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/map_load_todos_to_state.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/map_todos_updated_to_state.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/pubspec.yaml.md, docs/_snippets/flutter_firestore_todos_tutorial/todo.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/todo_entity.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/todos_bloc.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/todos_repository.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/todos_repository_dir.sh.md, docs/_snippets/flutter_firestore_todos_tutorial/todos_repository_library.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/todos_repository_pubspec.yaml.md, docs/_snippets/flutter_firestore_todos_tutorial/user_repository.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/user_repository_dir.sh.md, docs/_snippets/flutter_firestore_todos_tutorial/user_repository_library.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/user_repository_pubspec.yaml.md, docs/cs/flutterfirestoretodostutorial.md, docs/flutterfirestoretodostutorial.md, docs/jp/flutterfirestoretodostutorial.md, docs/pt-br/flutterfirestoretodostutorial.md, docs/ru/flutterfirestoretodostutorial.md, docs/zh-cn/flutterfirestoretodostutorial.md
**READY**
NO
- reuse snippets for flutterfirestoretodos
=> docs: reuse snippets for flutterfirestoretodos

docs/_snippets/flutter_login_tutorial/authentication_bloc.dart.md, docs/_snippets/flutter_login_tutorial/authentication_bloc_constructor.dart.md, docs/_snippets/flutter_login_tutorial/authentication_bloc_initial_state.dart.md, docs/_snippets/flutter_login_tutorial/authentication_bloc_map_event_to_state.dart.md, docs/_snippets/flutter_login_tutorial/authentication_event.dart.md, docs/_snippets/flutter_login_tutorial/authentication_state.dart.md, docs/_snippets/flutter_login_tutorial/flutter_create.sh.md, docs/_snippets/flutter_login_tutorial/flutter_packages_get.sh.md, docs/_snippets/flutter_login_tutorial/home_page.dart.md, docs/_snippets/flutter_login_tutorial/loading_indicator.dart.md, docs/_snippets/flutter_login_tutorial/login_bloc.dart.md, docs/_snippets/flutter_login_tutorial/login_event.dart.md, docs/_snippets/flutter_login_tutorial/login_form.dart.md, docs/_snippets/flutter_login_tutorial/login_page.dart.md, docs/_snippets/flutter_login_tutorial/login_state.dart.md, docs/_snippets/flutter_login_tutorial/main.dart.md, docs/_snippets/flutter_login_tutorial/pubspec.yaml.md, docs/_snippets/flutter_login_tutorial/splash_page.dart.md, docs/_snippets/flutter_login_tutorial/user_repository.dart.md, docs/cs/flutterlogintutorial.md, docs/es/flutterlogintutorial.md, docs/flutterlogintutorial.md, docs/fr/flutterlogintutorial.md, docs/jp/flutterlogintutorial.md, docs/pt-br/flutterlogintutorial.md, docs/ru/flutterlogintutorial.md, docs/zh-cn/flutterlogintutorial.md
**READY**
NO
- reuse snippets for flutterlogintutorial
=> docs: reuse snippets for flutterlogintutorial

docs/_snippets/flutter_timer_tutorial/actions.dart.md, docs/_snippets/flutter_timer_tutorial/background.dart.md, docs/_snippets/flutter_timer_tutorial/flutter_create.sh.md, docs/_snippets/flutter_timer_tutorial/main1.dart.md, docs/_snippets/flutter_timer_tutorial/main2.dart.md, docs/_snippets/flutter_timer_tutorial/pubspec.yaml.md, docs/_snippets/flutter_timer_tutorial/ticker.dart.md, docs/_snippets/flutter_timer_tutorial/timer1.dart.md, docs/_snippets/flutter_timer_tutorial/timer2.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_barrel.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_empty.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_initial_state.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_pause.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_resume.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_start.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_tick.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_ticker.dart.md, docs/_snippets/flutter_timer_tutorial/timer_event.dart.md, docs/_snippets/flutter_timer_tutorial/timer_state.dart.md, docs/cs/fluttertimertutorial.md, docs/es/fluttertimertutorial.md, docs/fluttertimertutorial.md, docs/fr/fluttertimertutorial.md, docs/jp/fluttertimertutorial.md, docs/pt-br/fluttertimertutorial.md, docs/ru/fluttertimertutorial.md, docs/zh-cn/fluttertimertutorial.md
**READY**
NO
- reuse snippets for fluttertimertutorial
=> docs: reuse snippets for fluttertimertutorial

docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc.dart.md, docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_initial_state.dart.md, docs/_snippets/flutter_firebase_login_tutorial/authentication_bloc_map_event_to_state.dart.md, docs/_snippets/flutter_firebase_login_tutorial/authentication_event.dart.md, docs/_snippets/flutter_firebase_login_tutorial/authentication_state.dart.md, docs/_snippets/flutter_firebase_login_tutorial/home_screen.dart.md, docs/_snippets/flutter_firebase_login_tutorial/login_bloc.dart.md, docs/_snippets/flutter_firebase_login_tutorial/login_event.dart.md, docs/_snippets/flutter_firebase_login_tutorial/login_form.dart.md, docs/_snippets/flutter_firebase_login_tutorial/login_state.dart.md, docs/_snippets/flutter_firebase_login_tutorial/main1.dart.md, docs/_snippets/flutter_firebase_login_tutorial/main2.dart.md, docs/_snippets/flutter_firebase_login_tutorial/main3.dart.md, docs/_snippets/flutter_firebase_login_tutorial/main4.dart.md, docs/_snippets/flutter_firebase_login_tutorial/main5.dart.md, docs/_snippets/flutter_firebase_login_tutorial/main6.dart.md, docs/_snippets/flutter_firebase_login_tutorial/register_bloc.dart.md, docs/_snippets/flutter_firebase_login_tutorial/register_event.dart.md, docs/_snippets/flutter_firebase_login_tutorial/register_form.dart.md, docs/_snippets/flutter_firebase_login_tutorial/register_state.dart.md, docs/cs/flutterfirebaselogintutorial.md, docs/flutterfirebaselogintutorial.md, docs/fr/flutterfirebaselogintutorial.md, docs/jp/flutterfirebaselogintutorial.md, docs/pt-br/flutterfirebaselogintutorial.md, docs/ru/flutterfirebaselogintutorial.md, docs/zh-cn/flutterfirebaselogintutorial.md
**READY**
NO
Update Flutter Firebase Login Tutorial to adhere to naming conventions (#1248)
=> docs: update flutterfirebaselogintutorial to adhere to naming conventions

docs/_snippets/flutter_login_tutorial/authentication_bloc.dart.md, docs/_snippets/flutter_login_tutorial/authentication_bloc_initial_state.dart.md, docs/_snippets/flutter_login_tutorial/authentication_bloc_map_event_to_state.dart.md, docs/_snippets/flutter_login_tutorial/authentication_event.dart.md, docs/_snippets/flutter_login_tutorial/authentication_state.dart.md, docs/_snippets/flutter_login_tutorial/home_page.dart.md, docs/_snippets/flutter_login_tutorial/login_bloc.dart.md, docs/_snippets/flutter_login_tutorial/login_form.dart.md, docs/_snippets/flutter_login_tutorial/login_state.dart.md, docs/_snippets/flutter_login_tutorial/main.dart.md, docs/cs/flutterlogintutorial.md, docs/es/flutterlogintutorial.md, docs/flutterlogintutorial.md, docs/fr/flutterlogintutorial.md, docs/jp/flutterlogintutorial.md, docs/pt-br/flutterlogintutorial.md, docs/ru/flutterlogintutorial.md, docs/zh-cn/flutterlogintutorial.md
**READY**
NO
- Update Flutter Login Tutorial to adhere to naming conventions (#1248)
=> docs: update flutterlogintutorial to adhere to naming conventions

docs/_snippets/flutter_timer_tutorial/actions.dart.md, docs/_snippets/flutter_timer_tutorial/main1.dart.md, docs/_snippets/flutter_timer_tutorial/main2.dart.md, docs/_snippets/flutter_timer_tutorial/ticker.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_initial_state.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_pause.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_resume.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_start.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_tick.dart.md, docs/_snippets/flutter_timer_tutorial/timer_bloc_ticker.dart.md, docs/_snippets/flutter_timer_tutorial/timer_event.dart.md, docs/_snippets/flutter_timer_tutorial/timer_state.dart.md, docs/cs/fluttertimertutorial.md, docs/es/fluttertimertutorial.md, docs/fluttertimertutorial.md, docs/fr/fluttertimertutorial.md, docs/jp/fluttertimertutorial.md, docs/pt-br/fluttertimertutorial.md, docs/ru/fluttertimertutorial.md, docs/zh-cn/fluttertimertutorial.md, examples/flutter_timer/lib/bloc/timer_event.dart, examples/flutter_timer/lib/bloc/timer_state.dart
**READY**
NO
- Update Flutter Timer Tutorial to adhere to naming conventions (#1248)
=> docs: update fluttertimertutorial to adhere to naming conventions

docs/cs/flutterinfinitelisttutorial.md, docs/es/flutterinfinitelisttutorial.md, docs/flutterinfinitelisttutorial.md, docs/fr/flutterinfinitelisttutorial.md, docs/jp/flutterinfinitelisttutorial.md, docs/pt-br/flutterinfinitelisttutorial.md, docs/ru/flutterinfinitelisttutorial.md, docs/zh-cn/flutterinfinitelisttutorial.md
=> docs: update docs/flutterinfinitelist to match code

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- flutter_bloc v4.0.1 release candidate which includes patch from #1286
- changes will be published in v4.0.1 of flutter_bloc pending merge.
=> rc(flutter_bloc): v4.0.1

packages/bloc/pubspec.yaml
**READY**
NO
I face dependencies conflicts.  Other dependencies I use use latest version of rxdart.
=> update rxdart to 0.24.0

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/utils/analyze-dependencies.ts, extensions/vscode/src/utils/update-pubspec-dependency.ts
**READY**
NO
- fix: package version analysis on dev_dependencies
=> fix(vscode): include dev_dependencies in package analysis

docs/_snippets/flutter_bloc_core_concepts/bloc_provider_lazy.dart.md, docs/flutterbloccoreconcepts.md, packages/flutter_bloc/README.md
**READY**
NO
- closes https://github.com/felangel/bloc/issues/1308
=> docs: document lazy parameter on BlocProvider

docs/fr/migration.md
=> Traduction migration.md to french

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/generator/Generator.kt
=> fix(intelliJ): handle trailing _bloc in name

packages/bloc/CHANGELOG.md, packages/bloc/README.md, packages/bloc/pubspec.yaml
**READY**
NO
- fix: bump cubit to ^0.1.2
- docs: minor updates to documentation for improved package score
=> fix(bloc): bump cubit to ^0.1.2

packages/bloc/CHANGELOG.md, packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- fix upgrade to `bloc ^5.0.1`
=> fix(flutter_bloc): upgrade to bloc 5.0.1

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- fix: upgrade to `bloc ^5.0.1`
- fix: upgrade to cubit_test ^0.1.1'
- fix: support breaking `StreamQueue` change in `async: 2.4.2`
- https://github.com/dart-lang/async/issues/122
- https://github.com/dart-lang/async/pull/123
- docs: minor documentation updates
=> fix(bloc_test): upgrade to bloc 5.0.1

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands/new-bloc.command.ts, extensions/vscode/src/commands/new-cubit.command.ts, extensions/vscode/src/utils/analyze-dependencies.ts, extensions/vscode/src/utils/get-pubspec-path.ts, extensions/vscode/src/utils/get-pubspec.ts, extensions/vscode/src/utils/has-dependency.ts
**READY**
NO
- fix: Equatable not being recognized on Windows
=> fix(vscode): fix pubspec.yaml file read on windows

packages/hydrated_bloc/lib/src/hydrated_cubit.dart, packages/hydrated_bloc/test/cubits/bad_cubit.dart, packages/hydrated_bloc/test/cubits/cyclic_cubit.dart, packages/hydrated_bloc/test/cubits/freezed_cubit.dart, packages/hydrated_bloc/test/e2e_test.dart, packages/hydrated_bloc/test/hydrated_bloc_test.dart
**READY**
YES 
closes #1452 and #1453
=> fix(hydrated_bloc): traversals, e2e, list fix

packages/hydrated_bloc/test/cubits/bad_cubit.dart, packages/hydrated_bloc/test/e2e_test.dart
=> fix(hydrated_bloc): code-cov 100%

packages/hydrated_bloc/lib/src/hydrated_cubit.dart, packages/hydrated_bloc/test/cubits/list_cubit.dart, packages/hydrated_bloc/test/e2e_test.dart
=> test(hydrated_bloc): adding complex list test

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/lib/src/hydrated_cubit.dart, packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/cubits/list_cubit.dart, packages/hydrated_bloc/test/e2e_test.dart
**READY**
NO
- fix(hydrated bloc): traversal empty list
=> fix(hydrated bloc): traversal empty list

docs/fr/flutterlogintutorial.md
=> docs(flutter_login): FR Translations

docs/fr/coreconcepts.md
=> docs: FR updates to coreconcepts

docs/fr/flutterbloccoreconcepts.md
=> docs: FR updates to flutterbloccoreconcepts

docs/blocvscodeextension.md, docs/cs/blocvscodeextension.md, docs/es/blocvscodeextension.md, docs/fr/blocvscodeextension.md, docs/jp/blocvscodeextension.md, docs/pt-br/blocvscodeextension.md, docs/ru/blocvscodeextension.md, docs/zh-cn/blocvscodeextension.md, extensions/vscode/README.md, extensions/vscode/snippets/bloc.json
**READY**
NO
This pull request merges the snippets from https://github.com/zepfietje/vscode-bloc-snippets and https://github.com/zepfietje/vscode-cubit-snippets so we have all convenient snippets in the main VS Code extension.
Also, some handy basic state and event snippets have been added. Partially related to https://github.com/felangel/bloc/issues/1442.
=> feat(vscode): update snippets and documentation

packages/bloc/lib/src/cubit.dart, packages/bloc/test/cubit_test.dart
**READY**
NO
- refactor: make internal `StreamController` instantiation lazy
- refactor: remove `drain` on `close`
=> refactor(bloc): cubit memory and performance improvements

examples/flutter_counter/analysis_options.yaml, examples/flutter_counter/lib/app.dart, examples/flutter_counter/lib/counter/cubit/counter_cubit.dart, examples/flutter_counter/lib/counter/view/counter_page.dart, examples/flutter_counter/lib/counter/view/counter_view.dart, examples/flutter_counter/lib/counter_observer.dart
**READY**
NO
- docs(flutter_counter): public member api docs
=> docs(flutter_counter): public member api docs

packages/bloc_test/CHANGELOG.md, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/test/bloc_bloc_test_test.dart
**READY**
NO
- fix(bloc_test): test timeouts when verify fails (closes #1639)
- fix(bloc_test): timeouts when expect fails (closes #1643)
=> fix(bloc_test): test timeouts when verify fails

docs/fluttercountertutorial.md
**READY**
NO
Add folder structure descriptions while following the tutorial.
=> docs: add directory structure to flutter counter tutorial

packages/flutter_bloc/lib/src/multi_repository_provider.dart
**READY**
NO
- `MultiRepositoryProvider` extends `MultiProvider` (closes #1672)
=> refactor(flutter_bloc): MultiRepositoryProvider extends MultiProvider

examples/github_search/flutter_github_search/lib/main.dart, examples/github_search/flutter_github_search/lib/search_form.dart, examples/github_search/flutter_github_search/pubspec.yaml
NO
- refactor: minor updates to flutter github search (closes #1667)
=> refactor: minor updates to flutter github search

packages/flutter_bloc/lib/src/bloc_builder.dart
**READY**
NO
- refactor(flutter_bloc): `BlocBuilder` to use `BlocListener` which simplifies the implementation and eliminates some repeated code.
=> refactor(flutter_bloc): BlocBuilder extends BlocListener

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- fix(bloc_test): restrict mockito to <4.1.2 (closes #1676)
=> fix(bloc_test): restrict mockito to <4.1.2

packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/test/bloc_builder_test.dart
**READY**
NO
- fix(flutter_bloc): BlocBuilder performs new lookup in didUpdateWidget
=> fix(flutter_bloc): BlocBuilder performs new lookup in didUpdateWidget

packages/flutter_bloc/lib/src/bloc_consumer.dart
**READY**
NO
- refactor(flutter_bloc): BlocConsumer requires single subscription (addresses #1634)
=> refactor(flutter_bloc): BlocConsumer requires single subscription

packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_consumer.dart, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_consumer_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart
**READY**
NO
- fix(flutter_bloc): state synchronization issue for rapidly emitting blocs (closes #1682)
=> fix(flutter_bloc): state synchronization issue

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v6.0.4
- fix: state synchronization issue when providing a condition
=> chore(flutter_bloc): v6.0.4

packages/bloc/lib/src/bloc.dart
**READY**
NO
- improve internal structure of bloc code to match the flow of state changes
- improve `mapEventToState` inline documentation (closes #1697)
=> docs(bloc): internal organization and documentation improvements

packages/bloc_test/CHANGELOG.md, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/bloc_bloc_test_test.dart
**READY**
NO
- fix(bloc_test): add deep equality warning when `blocTest` fails and expected states appear to be equal to the actual states (closes #1275)
=> fix(bloc_test): add deep equality warning

docs/index.html
**READY**
NO
- docs: support dark mode
=> docs: support dark mode

docs/flutterfirebaselogintutorial.md
FIXED: "authentication" -> "authenticate"
**READY**
NO
closes #1738
=> docs: minor typo fix in flutterfirebaselogintutorial.md

docs/coreconcepts.md
Just a small language fix.
**READY**
NO
=> docs: Update coreconcepts.md

docs/whybloc.md
**READY**
NO
Minor updates to why bloc documentation
=> docs: minor updates to why bloc

docs/flutterfirebaselogintutorial.md
**READY**
NO
- docs: add missing SignUpForm section to FirebaseLogin
=> docs: add missing SignUpForm section to FirebaseLogin

README.md
**READY**
NO
- Added a new **Books** section with a reference to our new Dart and Flutter book!
=> docs: add a reference to complete flutter reference

.github/workflows/bloc_test.yaml, .gitignore, packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/pubspec.yaml, tool/coverage.sh
**READY**
NO
- fix(bloc_test): revert sdk version to >=2.7.0 (fix pana score)
=> fix(bloc_test): revert sdk version to >=2.7.0

examples/flutter_firebase_login/pubspec.yaml, examples/flutter_firestore_todos/lib/widgets/tab_selector.dart, examples/flutter_todos/lib/widgets/tab_selector.dart
**READY**
NO
- docs: update examples to flutter v1.22.0
=> docs: update examples to flutter v1.22.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v6.0.6
- docs: improve inline documentation for `buildWhen`
=> chore(flutter_bloc): v6.0.6

.github/workflows/replay_bloc.yaml, packages/replay_bloc/lib/src/replay_bloc.dart, packages/replay_bloc/lib/src/replay_cubit.dart, packages/replay_bloc/pubspec.yaml, packages/replay_bloc/test/main.dart
**READY**
NO
- docs(replay_bloc): add inline documentation to mixins
=> docs(replay_bloc): add inline documentation to mixins

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/templates/cubit-state.template.ts, extensions/vscode/src/templates/cubit.template.ts
**READY**
NO
- fix(vscode): freezed cubit template typo (closes #1821)
=> fix(vscode): freezed cubit template typo

.github/workflows/bloc.yaml, packages/bloc/CHANGELOG.md, packages/bloc/README.md, packages/bloc/example/main.dart, packages/bloc/lib/src/bloc.dart, packages/bloc/lib/src/bloc_observer.dart, packages/bloc/lib/src/cubit.dart, packages/bloc/pubspec.yaml, packages/bloc/test/bloc_observer_test.dart, packages/bloc/test/bloc_test.dart, packages/bloc/test/blocs/counter/counter_bloc.dart, packages/bloc/test/cubit_test.dart, packages/bloc/test/cubits/counter_cubit.dart, packages/bloc/test/main.dart
**READY**
NO
- feat(bloc): add `onCreate` and `onClose` to `BlocObserver` (closes #1830)
- ci(bloc): update to Dart 2.10.0
=> feat(bloc): add onCreate and onClose to BlocObserver

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v7.1.0
=> chore(bloc_test): v7.1.0

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/lib/src/hydrated_storage.dart, packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/e2e_test.dart
**READY**
NO
- fix(hydrated_bloc): storage exception on clear and rehydrate (closes #1850)
=> fix(hydrated_bloc): storage exception on clear and rehydrate

docs/flutterlogintutorial.md
READY
NO
The sentence reads better with the suggested change.
- [x ] 📝 Documentation
=> docs: fix typos in login tutorial

examples/angular_counter/pubspec.yaml, packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): bump to v6.0.0
=> chore(angular_bloc): bump to v6.0.0

examples/flutter_firestore_todos/ios/Podfile.lock, examples/flutter_firestore_todos/ios/Runner.xcodeproj/project.pbxproj, examples/flutter_firestore_todos/lib/main.dart, examples/flutter_firestore_todos/todos_repository/lib/src/entities/todo_entity.dart, examples/flutter_firestore_todos/todos_repository/lib/src/firebase_todos_repository.dart, examples/flutter_firestore_todos/todos_repository/pubspec.yaml, examples/flutter_firestore_todos/user_repository/lib/src/firebase_user_repository.dart, examples/flutter_firestore_todos/user_repository/pubspec.yaml
Ready
NO
I upgraded the firebase code for the Firestore Todos project.
=> docs: update firebase in firestore todos example

docs/migration.md
=> docs: fix extension method name in migration guide

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/README.md, packages/replay_bloc/lib/replay_bloc.dart, packages/replay_bloc/pubspec.yaml
**READY**
NO
- feat(replay_bloc): v0.0.1-dev.4
- feat: export `package:bloc/bloc.dart` (addresses of #1695)
- deps: update to `bloc: ^6.1.0`
- deps: require dart >=2.6.0
=> feat(replay_bloc): v0.0.1-dev.4

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/lib/hydrated_bloc.dart, packages/hydrated_bloc/pubspec.yaml, packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/lib/replay_bloc.dart
**READY**
NO
- feat(hydrated_bloc): v6.1.0
- feat: export `package:bloc/bloc.dart` (addresses #1695)
- deps: update to `bloc: ^6.1.0`
- deps: require `dart >=2.6.0`
=> feat(hydrated_bloc): v6.1.0

docs/fr/faqs.md, docs/fr/flutterbloccoreconcepts.md, docs/fr/fluttercountertutorial.md
Update french translations to include changes from 5f94d0b and c273e8a.
READY
NO
Update french translations to include changes from 5f94d0b and c273e8a (Faq, Bloc core concepts and counter tutorial).
=> docs: update french translations for Faq, Bloc core concepts and counter tuto

.github/workflows/angular_bloc.yaml, .github/workflows/angular_dart_examples.yaml, .github/workflows/flutter_bloc.yaml, .github/workflows/flutter_examples.yaml, .github/workflows/hydrated_bloc.yaml
**READY**
NO
- ci: upgrade to flutter-action v1.4.0
=> ci: upgrade to flutter-action v1.4.0

docs/fr/_coverpage.md, docs/fr/migration.md
READY
NO
Update french translations to include changes from 9e3282a.
=> docs: update french migration doc for 6.x versions

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/extension.ts
**READY**
NO
- feat(vscode): add checkForUpdates extension setting (closes #1962)
=> feat(vscode): add checkForUpdates extension setting

docs/zh-cn/migration.md
**READY**
NO
Add zh-cn migration docs
=> docs: update zh-cn migration

examples/flutter_infinite_list/android/gradle.properties, examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart
**READY**
NO
closes https://github.com/felangel/bloc/issues/1858
=> fix(flutter_infinite_list): hide bottom loader when no more posts are available

packages/bloc_test/lib/src/mock_bloc.dart
**READY**
NO
In the current documentation of the MockBloc class it says you need to provide an event and state type when extending it. However this is not the case anymore since you only need to provide the state in the current bloc_test version.
=> docs: adjust MockBloc documentation to class api

packages/bloc/lib/src/cubit.dart, packages/bloc/test/bloc_test.dart, packages/bloc/test/cubit_test.dart
**READY**
NO
- fix(bloc): close always emits done (closes #1943)
=> fix(bloc): close always emits done

docs/jp/blocnamingconventions.md, docs/jp/flutterbloccoreconcepts.md, docs/jp/testing.md
**READY**
NO
Minor typo fix in Japanese
=> docs: fix typo in Japanese

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/lib/src/bloc_builder.dart, packages/flutter_bloc/lib/src/bloc_consumer.dart, packages/flutter_bloc/lib/src/bloc_listener.dart, packages/flutter_bloc/lib/src/bloc_provider.dart, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_consumer_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/multi_bloc_listener_test.dart, packages/flutter_bloc/test/multi_bloc_provider_test.dart
**IN DEVELOPMENT**
YES
- feat(flutter_bloc)!: v7.0.0
- **BREAKING**: remove `context.bloc` extension
- **BREAKING**: rename `cubit` parameter in `BlocListener` to `value`
- **BREAKING**: rename `cubit` parameter in `BlocBuilder` to `value`
- **BREAKING**: rename `cubit` parameter in `BlocConsumer` to `value`
- docs: update inline API docs
=> feat(flutter_bloc)!: v7.0.0

examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart
**READY**
NO
- fix(flutter_infinite_list): hasReachedMax logic (closes #2016)
=> fix(flutter_infinite_list): hasReachedMax logic

.github/workflows/angular_bloc.yaml, .github/workflows/angular_dart_examples.yaml
**READY**
NO
- ci: fix angular_bloc workflows
=> ci: fix angular_bloc workflows

README.md, packages/angular_bloc/README.md, packages/bloc/README.md, packages/bloc_test/README.md, packages/flutter_bloc/README.md, packages/hydrated_bloc/README.md, packages/replay_bloc/README.md
**READY**
NO
- docs: improve sponsors section
=> docs: improve sponsors section

packages/bloc/README.md
**READY**
NO
- Updated URL in `README.md`
=> docs: update sponsors url in README

packages/flutter_bloc/lib/src/bloc_provider.dart, packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
NO
- fix(flutter_bloc): BlocProvider.value use InheritedProvider.value (related to #2127)
=> fix(flutter_bloc): BlocProvider.value use InheritedProvider.value

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v6.1.2
=> chore(flutter_bloc): v6.1.2

examples/flutter_infinite_list/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart, examples/flutter_infinite_list/lib/posts/bloc/post_state.dart, examples/flutter_infinite_list/lib/posts/models/post.dart, examples/flutter_infinite_list/lib/posts/view/posts_list.dart, examples/flutter_infinite_list/lib/posts/widgets/post_list_item.dart, examples/flutter_infinite_list/pubspec.yaml
**READY**
NO
I have migrated this example to null safety
=> feat(flutter_infinite_list): null safety

docs/zh-cn/blocvscodeextension.md
doc: add zh-cn translation to blocvscodeextension.md file
**READY**
NO
Add zh_cn translation to blocvscodeextension.md https://github.com/felangel/bloc/commit/5a361b06958f0fee8a076ea0b5d2d644d74b2d80
=> docs: add zh_cn translation to blocvscodeextension.md

packages/flutter_bloc/lib/src/bloc_builder.dart
=> Format the code snippet of BlocBuilder

docs/es/migration.md
**READY**
NO
Update the migration guide.
=> update the migration guide

examples/flutter_form_validation/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, examples/flutter_form_validation/lib/bloc/my_form_bloc.dart, examples/flutter_form_validation/lib/bloc/my_form_event.dart, examples/flutter_form_validation/lib/bloc/my_form_state.dart, examples/flutter_form_validation/lib/main.dart, examples/flutter_form_validation/lib/models/email.dart, examples/flutter_form_validation/lib/models/password.dart, examples/flutter_form_validation/pubspec.yaml
=> migrate flutter_form_validation to null safety

.github/workflows/bloc_test.yaml
Update bloc_test.yaml workflow with new dart syntax as example
=> ci(bloc_test): update bloc_test.yaml workflow with new dart syntax

docs/flutterfirebaselogintutorial.md, docs/flutterfirestoretodostutorial.md, docs/flutterlogintutorial.md, docs/flutterweathertutorial.md
Fixed definition for BlocListener widget 
READY
NO
Updated definition of BlocListener in the pages with examples.
=> docs: fixed definition of BlocListener

packages/bloc/CHANGELOG.md, packages/bloc/lib/src/bloc.dart, packages/bloc/pubspec.yaml
**READY**
NO
- fix(bloc): memory leak due to internal event stream being a broadcast stream (closes #2186)
=> fix(bloc): memory leak due to event broadcast stream

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore: upgrade to `bloc ^6.1.2`
- chore: upgrade to `provider ^4.3.3`
=> chore(flutter_bloc): v6.1.3

packages/bloc/CHANGELOG.md, packages/bloc/lib/src/bloc.dart, packages/bloc/pubspec.yaml, packages/bloc/test/bloc_test.dart, packages/bloc/test/blocs/counter/counter.dart, packages/bloc/test/blocs/counter/merge_bloc.dart
**READY**
NO
- fix(bloc): transform events multiple subscriptions
=> fix(bloc): transform events multiple subscriptions

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/lib/flutter_bloc.dart
**READY**
NO
- fix(flutter_bloc): expose ProviderNotFoundException (closes #2184)
=> feat(flutter_bloc): expose ProviderNotFoundException

packages/bloc_test/CHANGELOG.md, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml
**READY**
NO
- fix(bloc_test): mocktail: ">=0.0.1-dev.12 <0.0.1" (closes #2196)
=> fix(bloc_test): mocktail: ">=0.0.1-dev.12 <0.0.1"

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): upgrade to provider ^5.0.0 (closes #2202)
=> chore(flutter_bloc): upgrade to provider ^5.0.0

examples/flutter_counter/pubspec.yaml, examples/flutter_counter/test/counter/view/counter_view_test.dart, packages/bloc_test/CHANGELOG.md, packages/bloc_test/lib/src/mock_bloc.dart, packages/bloc_test/lib/src/when_listen.dart, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/bloc_bloc_test_test.dart, packages/bloc_test/test/cubit_bloc_test_test.dart, packages/bloc_test/test/mock_bloc_test.dart
**READY**
YES
- feat(bloc_test)!: upgrade to mocktail v0.0.2
=> feat(bloc_test)!: upgrade to mocktail v0.0.2

packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/hydrated_bloc_test.dart, packages/hydrated_bloc/test/hydrated_cubit_test.dart, packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
NO
- feat(hydrated_bloc): use mocktail v0.0.2-dev and bump deps
=> feat(hydrated_bloc): use mocktail v0.0.2-dev and bump deps

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/example/lib/main.dart, packages/hydrated_bloc/example/pubspec.yaml, packages/hydrated_bloc/lib/src/hydrated_storage.dart, packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
NO
- fix(hydrated_bloc): web support (closes #2193)
```dart
void main() async {
WidgetsFlutterBinding.ensureInitialized();
HydratedBloc.storage = await HydratedStorage.build(
storageDirectory: kIsWeb
? HydratedStorage.webStorageDirectory
: await getTemporaryDirectory(),
);
runApp(App());
}
```
=> fix(hydrated_bloc): web support

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/bloc_bloc_test_test.dart, packages/bloc_test/test/cubit_bloc_test_test.dart
**READY**
YES
- feat(bloc_test)!: support dynamic seed values (closes #2206)
```dart
blocTest(
...
seed: value,
);
```
```dart
blocTest(
...
seed: () => value,
);
```
=> feat(bloc_test)!: support dynamic seed values

examples/flutter_counter/pubspec.yaml, examples/flutter_counter/test/counter/cubit/counter_cubit_test.dart
**READY**
NO
- fix(flutter_counter): update to support bloc_test v8.0.0-nullsafety.4
=> fix(flutter_counter): update to support bloc_test v8.0.0-nullsafety.4

docs/ko-kr/coreconcepts.md
fixed duplicate sentence of English and Korean.
**READY**
NO
It is a duplicate sentence of English and Korean.
=> docs : ko-kr - fixed duplicate sentences

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/lib/src/repository_provider.dart, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/repository_provider_test.dart
**READY**
YES
- refactor(flutter_bloc)!: remove deprecated `context.repository` extension
=> refactor(flutter_bloc)!: remove context repository extension

examples/flutter_complex_list/lib/simple_bloc_observer.dart, examples/flutter_counter/lib/counter_observer.dart, examples/flutter_firestore_todos/lib/blocs/simple_bloc_observer.dart, examples/flutter_infinite_list/lib/simple_bloc_observer.dart, examples/flutter_shopping_cart/lib/simple_bloc_observer.dart, examples/flutter_todos/lib/blocs/simple_bloc_observer.dart, packages/bloc/CHANGELOG.md, packages/bloc/README.md, packages/bloc/example/main.dart, packages/bloc/lib/src/bloc_observer.dart, packages/flutter_bloc/example/lib/main.dart, packages/replay_bloc/example/lib/simple_bloc_observer.dart
**READY**
YES
- refactor(bloc): improve onTransition and onEvent signature to be consistent with v6.0.0
=> refactor(bloc): improve onTransition and onEvent signature

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v8.0.0-nullsafety.6
=> chore(bloc_test): v8.0.0-nullsafety.6

packages/flutter_bloc/README.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.0.0-nullsafety.6
=> chore(flutter_bloc): v7.0.0-nullsafety.6

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/README.md, packages/hydrated_bloc/example/linux/flutter/generated_plugin_registrant.cc, packages/hydrated_bloc/example/linux/flutter/generated_plugin_registrant.h, packages/hydrated_bloc/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v7.0.0-nullsafety.4
=> chore(hydrated_bloc): v7.0.0-nullsafety.4

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/README.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.0.1-nullsafety.3
=> chore(replay_bloc): v0.0.1-nullsafety.3

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v7.0.0
=> chore(bloc): v7.0.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v8.0.0
=> chore(bloc_test): v8.0.0

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v7.0.0
=> chore(hydrated_bloc): v7.0.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.0.0
=> chore(flutter_bloc): v7.0.0

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.0.1
=> chore(replay_bloc): v0.0.1

docs/_coverpage.md, docs/_snippets/core_concepts/counter_bloc_on_transition.dart.md, docs/_snippets/core_concepts/simple_bloc_observer_complete.dart.md, docs/_snippets/flutter_todos_tutorial/simple_bloc_observer.dart.md, docs/_snippets/flutter_weather_tutorial/simple_bloc_observer.dart.md, docs/az/_coverpage.md, docs/coreconcepts.md, docs/cs/_coverpage.md, docs/es/_coverpage.md, docs/fr/_coverpage.md, docs/jp/_coverpage.md, docs/ko-kr/_coverpage.md, docs/migration.md, docs/pt-br/_coverpage.md, docs/ru/_coverpage.md, docs/zh-cn/_coverpage.md, docs/zh-cn/coreconcepts.md
**READY**
NO
- docs: v7.0.0 migration guide (closes #2228)
=> docs: v7.0.0 migration guide

docs/coreconcepts.md
**READY**
NO
Just corrected minor typos in the docs.
=> docs: Correct typos

docs/assets/style.css, docs/index.html
**READY**
NO
- fix: docs sidebar render order on coverpage (closes #2299)
=> fix: docs sidebar render order on coverpage

extensions/vscode/package-lock.json, extensions/vscode/src/utils/get-pubspec.ts
**READY**
NO
- chore(vscode): upgrade dependencies
=> chore(vscode): upgrade dependencies

docs/coreconcepts.md
**READY**
NO
I fixed a small typo error in docs.
=> fix(docs): small error

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package.json, extensions/vscode/snippets/bloc_test.json
**READY**
NO
- feat(vscode): add `blocTest` snippet
=> feat(vscode): add blocTest snippet

extensions/vscode/README.md, extensions/vscode/snippets/bloc_test.json
**READY**
NO
- feat(vscode): add import bloc_test snippet
=> feat(vscode): add import bloc_test snippet

extensions/intellij/README.md, extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml
**READY**
NO
- feat(intellij): add import bloc_test snippet
=> feat(intellij): add import bloc_test snippet

examples/flutter_counter/lib/counter_observer.dart, examples/flutter_counter/macos/Runner.xcodeproj/project.pbxproj, examples/flutter_counter/macos/Runner.xcworkspace/contents.xcworkspacedata
**READY**
NO
- docs(flutter_counter): update BlocObserver to override `onChange` rather than `onTransition` since the example uses a `Cubit`.
=> docs(flutter_counter): fix BlocObserver

docs/migration.md
**READY**
NO
- docs: fix bloc_test versions in migration guide (closes #2397)
=> docs: fix bloc_test versions in migration guide

.github/DOCS_ISSUE_TEMPLATE.md
Hey, unfortunately, I no longer have time to manage the Czech translation, so I will have to remove myself from the list, so I don't get ping every time the docs change. 
Sorry for the trouble. I hope in the future I will be able to help again. <3
=> docs: Czech docs

docs/pt-br/migration.md, docs/pt-br/whybloc.md
Updating some parts of the pt_BR docs
=> docs(pt_BR): update documentation

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore(intelliJ): v2.2.1
=> chore(intelliJ): v2.2.1

packages/angular_bloc/test/bloc_pipe_test.dart
**READY**
NO
- fix(angular_bloc): analysis errors (directives_ordering)
=> fix(angular_bloc): analysis errors (directives_ordering)

examples/flutter_firebase_login/lib/app/view/app.dart, examples/flutter_firebase_login/lib/home/view/home_page.dart, examples/flutter_firebase_login/lib/login/view/login_form.dart, examples/flutter_firebase_login/lib/login/view/login_page.dart, examples/flutter_firebase_login/lib/sign_up/view/sign_up_form.dart, examples/flutter_firebase_login/lib/sign_up/view/sign_up_page.dart, examples/flutter_firebase_login/linux/flutter/generated_plugin_registrant.cc, examples/flutter_firebase_login/linux/flutter/generated_plugin_registrant.h, examples/flutter_firebase_login/linux/flutter/generated_plugins.cmake, examples/flutter_firebase_login/macos/Flutter/GeneratedPluginRegistrant.swift, examples/flutter_firebase_login/macos/Flutter/ephemeral/Flutter-Generated.xcconfig, examples/flutter_firebase_login/macos/Flutter/ephemeral/flutter_export_environment.sh, examples/flutter_firebase_login/macos/Podfile, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_firebase_login/test/app/view/app_test.dart, examples/flutter_firebase_login/test/home/view/home_page_test.dart, examples/flutter_firebase_login/test/login/view/login_form_test.dart, examples/flutter_firebase_login/test/login/view/login_page_test.dart, examples/flutter_firebase_login/test/sign_up/view/sign_up_form_test.dart
**READY**
NO
- fix(flutter_firebase_login): update analysis options
=> fix(flutter_firebase_login): update analysis options

examples/flutter_login/pubspec.yaml
**READY**
NO
- chore(flutter_login): update dependencies (closes #2344)
=> chore(flutter_login): update dependencies

examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart, examples/flutter_firebase_login/lib/app/bloc/app_state.dart, examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart, examples/flutter_firebase_login/packages/authentication_repository/lib/src/models/user.dart, examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart, examples/flutter_firebase_login/packages/authentication_repository/test/models/user_test.dart, examples/flutter_firebase_login/test/app/bloc/app_bloc_test.dart, examples/flutter_firebase_login/test/app/bloc/app_state_test.dart, examples/flutter_firebase_login/test/app/view/app_test.dart
**READY**
NO
- refactor(flutter_firebase_login): rename anonymous user to empty user
=> refactor(flutter_firebase_login): rename anonymous user to empty user

examples/flutter_firebase_login/lib/sign_up/view/sign_up_form.dart, examples/flutter_firebase_login/test/sign_up/view/sign_up_form_test.dart
**READY**
NO
- fix(flutter_firebase_login): sign up routing (closes #2456)
=> fix(flutter_firebase_login): sign up routing

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v8.0.1
- feat: allow `blocTest` to capture non-exceptions
- feat: export `mocktail`
=> chore(bloc_test): v8.0.1

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/code-actions/bloc-code-action-provider.ts
=> feat(vscode): show code actions in refactor menu

.github/workflows/angular_bloc.yaml, .github/workflows/angular_dart_examples.yaml, packages/angular_bloc/example/example.dart, packages/angular_bloc/test/bloc_pipe_test.dart
**READY**
NO
- refactor(angular_bloc): analysis warnings
- remove unnecessary imports
=> refactor(angular_bloc): analysis warnings

.github/workflows/bloc.yaml, .github/workflows/bloc_test.yaml, .github/workflows/flutter_bloc.yaml, .github/workflows/flutter_examples.yaml, .github/workflows/hydrated_bloc.yaml, .github/workflows/replay_bloc.yaml, packages/bloc/pubspec.yaml, packages/hydrated_bloc/pubspec.yaml, packages/replay_bloc/pubspec.yaml
**READY**
NO
- ci: upgrade ci workflows
- use setup-dart action
- upgrade flutter-action
- use latest dart commands
- remove package:coverage from dev dependencies
=> ci: upgrade ci workflows

examples/flutter_firebase_login/lib/app/bloc_observer.dart, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart, examples/flutter_firebase_login/packages/cache/pubspec.yaml, examples/flutter_firebase_login/packages/cache/test/cache_test.dart, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_firebase_login/test/login/cubit/login_cubit_test.dart, examples/flutter_firebase_login/test/login/view/login_form_test.dart, examples/flutter_firebase_login/test/sign_up/cubit/sign_up_cubit_test.dart, examples/flutter_firebase_login/test/sign_up/view/sign_up_form_test.dart
**READY**
NO
- fix(flutter_firebase_login): upgrade to very_good_analysis v2.1.0
=> fix(flutter_firebase_login): upgrade to very_good_analysis v2.1.0

extensions/vscode/package-lock.json
**READY**
NO
- deps(vscode): update browserslist dependency
=> deps(vscode): update browserslist dependency

docs/fluttertimertutorial.md
**READY**
NO
- docs(flutter_timer): update key topics to remove incorrect cubit reference (closes #2467)
=> docs(flutter_timer): update key topics to remove incorrect cubit reference

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.0.2
=> chore(replay_bloc): v0.0.2

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.0.1
=> chore(flutter_bloc): v7.0.1

README.md, packages/flutter_bloc/README.md
**READY**
NO
- docs: add I/O photo booth to examples list
=> docs: add I/O photo booth to examples list

.github/workflows/bloc_test.yaml
**READY**
NO
- ci(bloc_test): verify pub score
=> ci(bloc_test): verify pub score

.github/workflows/bloc.yaml
**READY**
NO
- ci(bloc): verify pub score
=> ci(bloc): verify pub score

.github/workflows/bloc.yaml, .github/workflows/bloc_test.yaml, tool/verify_pub_score.sh
**READY**
NO
- ci: refactor pub score check
=> ci: refactor pub score check

.github/workflows/bloc.yaml, .github/workflows/bloc_test.yaml, .github/workflows/flutter_bloc.yaml
**READY**
NO
- ci(flutter_bloc): verify pub score
=> ci(flutter_bloc): verify pub score

.github/workflows/hydrated_bloc.yaml
**READY**
NO
- ci(hydrated_bloc): verify pub score
=> ci(hydrated_bloc): verify pub score

.github/workflows/replay_bloc.yaml
**READY**
NO
- ci(replay_bloc): verify pub score
=> ci(replay_bloc): verify pub score

.github/workflows/angular_bloc.yaml
**READY**
NO
- ci(angular_bloc): verify pub score
=> ci(angular_bloc): verify pub score

.github/workflows/ci.yaml
=> ci: pana noop

packages/hydrated_bloc/example/lib/main.dart, packages/hydrated_bloc/example/pubspec.yaml, packages/hydrated_bloc/lib/src/hydrated_storage.dart, packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/e2e_test.dart, packages/hydrated_bloc/test/hydrated_storage_test.dart
**READY**
NO
- fix(hydrated_bloc): HydratedStorage clear behavior (closes #2407)
=> fix(hydrated_bloc): HydratedStorage clear behavior

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v7.0.1
=> chore(hydrated_bloc): v7.0.1

examples/flutter_weather/packages/meta_weather_api/lib/src/models/location.dart, examples/flutter_weather/packages/meta_weather_api/lib/src/models/location.g.dart, examples/flutter_weather/packages/meta_weather_api/test/location_test.dart
READY
NO
Create a JsonConverter for LatLng
- [x ] 🧹 Code refactor
=> flutter_weather: refactor location models, tests to use JsonConverter

packages/bloc_test/CHANGELOG.md, packages/bloc_test/lib/bloc_test.dart, packages/bloc_test/pubspec.yaml
**READY**
NO
- fix(bloc_test): revert `mocktail` export to reduce conflicts with `mockito` (closes #2510)
=> fix(bloc_test): revert mocktail export

examples/flutter_weather/lib/main.dart, examples/flutter_weather/packages/meta_weather_api/lib/src/meta_weather_api_client.dart, examples/flutter_weather/packages/meta_weather_api/pubspec.yaml, examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart, examples/flutter_weather/packages/weather_repository/pubspec.yaml, examples/flutter_weather/pubspec.yaml
**READY**
NO
- docs(flutter_weather): fix metaweather_api tests
=> docs(flutter_weather): fix metaweather_api tests

extensions/vscode/src/utils/get-selected-text.ts
**READY**
NO
- fix(vscode): wrap with selection
=> fix(vscode): wrap with selection

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v5.6.2
=> chore(vscode): v5.6.2

docs/flutterweathertutorial.md
READY
NO
fix pub.dev links to json serializable , json annotation, and blade runner
=> docs(flutter_weather): fix pub.dev links to json serialization packages

README.md, docs/_coverpage.md, docs/es/README.md, packages/angular_bloc/README.md, packages/bloc/README.md, packages/bloc_test/README.md, packages/flutter_bloc/README.md, packages/hydrated_bloc/README.md, packages/replay_bloc/README.md
**READY**
NO
- docs: update stream sponsorship urls
=> docs: update stream sponsorship urls

docs/fluttertimertutorial.md, examples/flutter_timer/pubspec.yaml
READY
NO
* Update documentation for flutter timer tutorial
=> docs: update timer tutorial

docs/_sidebar.md, docs/az/_sidebar.md, docs/ko-kr/_sidebar.md
**READY**
NO
- docs: update sidebar tutorial links
=> docs: update sidebar tutorial links

docs/flutterangulargithubsearch.md, examples/github_search/common_github_search/pubspec.yaml
**READY**
NO
* Updates to the Github Search Tutorial.
=> docs: github_search tutorial updates

docs/_sidebar.md, docs/az/_sidebar.md, docs/cs/_sidebar.md, docs/es/_sidebar.md, docs/fr/_sidebar.md, docs/jp/_sidebar.md, docs/ko-kr/_sidebar.md, docs/pt-br/_sidebar.md, docs/ru/_sidebar.md, docs/zh-cn/_sidebar.md
**READY**
NO
- docs(github_search): update sidebar
=> docs(github_search): update sidebar

examples/flutter_counter/pubspec.yaml
=> fix(counter_example): integration_test dependency with null-safety

docs/es/flutterweathertutorial.md, docs/pt-br/flutterweathertutorial.md, docs/ru/flutterweathertutorial.md
**READY**
NO
- docs(flutter_weather): update weather tutorial localizations
=> docs(flutter_weather): update weather tutorial localizations

extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml
**READY**
NO
- Fixes `import bloc` snippets which worked only in statements but not outside of the body class (at the top level)
- Adds an enum chooser to specify whether it is `Bloc or Cubit`
https://user-images.githubusercontent.com/67197047/124175827-5f1f8d00-daae-11eb-9548-5da97e0a88a5.mp4
=> feat(intelliJ): update live templates

examples/flutter_firestore_todos/lib/blocs/stats/stats_bloc.dart, examples/flutter_firestore_todos/lib/blocs/stats/stats_event.dart, examples/flutter_todos/lib/blocs/stats/stats_event.dart
**READY**
NO
- chore(flutter_todos): rename UpdateStats to StatsUpdates
=> refactor(flutter_todos): rename UpdateStats to StatsUpdates

examples/flutter_shopping_cart/test/cart/bloc/cart_bloc_test.dart
**READY**
NO
- fix(flutter_shopping_cart): fix typo in CartBloc test description (closes #2596)
=> fix(flutter_shopping_cart): typo in CartBloc test description

packages/bloc/lib/src/bloc.dart
**READY**
NO
- refactor(bloc): simplify event controller initialization (closes #2607)
=> refactor(bloc): simplify event controller initialization

packages/bloc/lib/src/bloc.dart, packages/bloc/test/bloc_on_test.dart
**READY**
NO
- refactor: revert event controller changes
=> refactor: revert event controller changes

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.1.0
- feat: add `BlocSelector`
=> chore(flutter_bloc): v7.1.0

packages/flutter_bloc/test/bloc_builder_test.dart, packages/flutter_bloc/test/bloc_consumer_test.dart, packages/flutter_bloc/test/bloc_listener_test.dart, packages/flutter_bloc/test/bloc_provider_test.dart, packages/flutter_bloc/test/multi_bloc_listener_test.dart, packages/flutter_bloc/test/multi_bloc_provider_test.dart
**READY**
NO
- chore(flutter_bloc): organize imports
=> chore(flutter_bloc): organize imports

examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart, examples/flutter_infinite_list/test/posts/bloc/post_bloc_test.dart
**READY**
NO
Changed line 26 on `post_bloc.dart` from `events.debounceTime` to `events.throttleTime`. Changed as well it's corresponding unit test and removed the `wait` parameter on line 59 in `post_bloc_test.dart`.
=> feat(flutter_infinite_list): use throttleTime instead of debounceTime

extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml
**READY**
NO
sry if I spam you too much with this extension PRs 😅
since this is a new widget, I do not think it is yet needed to have it in `Wrap menu` since not many people won't be on the newest version + it requires some additional changes as it has some additional variable parameters
https://user-images.githubusercontent.com/67197047/127551107-f027dc55-7bac-4969-bd5d-2574c357ddbf.mp4
=> feat(intelliJ): add blocselector live template

extensions/vscode/README.md, extensions/vscode/snippets/flutter_bloc.json
**READY**
NO
- feat(vscode): add BlocSelector snippet
=> feat(vscode): add BlocSelector snippet

extensions/vscode/README.md, extensions/vscode/package.json, extensions/vscode/src/code-actions/bloc-code-action-provider.ts, extensions/vscode/src/commands/wrap-with.command.ts, extensions/vscode/src/extension.ts
**READY**
NO
- feat(vscode): Wrap with BlocSelector
=> feat(vscode): Wrap with BlocSelector

extensions/vscode/src/utils/analyze-dependencies.ts
**READY**
NO
- feat(vscode): update analyze dependency versions
=> feat(vscode): update analyze dependency versions

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v5.7.0
- feat: add snippets for `BlocSelector`
- feat: add `Wrap with BlocSelector` action
- feat: update to latest packages
- bloc_test -> ^8.1.0
- equatable -> ^2.0.3
- flutter_bloc -> ^7.1.0
- hydrated_bloc -> ^7.0.1
- sealed_flutter_bloc -> ^7.0.0
=> chore(vscode): v5.7.0

docs/coreconcepts.md
**READY**
NO
Update documentation.
=> docs(coreconcepts): Bloc extends BlocBase

docs/coreconcepts.md
You reviewed https://github.com/felangel/bloc/pull/2645 too fast :)
**READY**
NO
- [ x] 📝 Documentation
=> docs(coreconcepts): Bloc extends BlocBase (not Cubit)

extensions/vscode/package-lock.json
=> chore(deps): bump path-parse to v1.0.7

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml
**READY**
NO
- chore: bump version to v2.4.0
=> chore(intellij): v2.4.0

docs/flutterweathertutorial.md
[Code snippet](https://github.com/felangel/bloc/blob/master/docs/_snippets/flutter_weather_tutorial/repository_layer/export_top_level_models.dart.md) shows contents, not directory structure.
**READY**
NO
Update weather tutorial docs.
- [ x] 📝 Documentation
=> Update weather tutorial

packages/bloc/lib/src/bloc.dart, packages/bloc/test/bloc_test.dart, packages/bloc/test/cubit_test.dart
**READY**
NO
- feat(bloc): expose isClosed (closes #2398)
=> feat(bloc): expose isClosed on BlocBase

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v7.1.0
- feat: expose `isClosed` getter on `BlocBase`
- refactor: simplify internal event controller initialization
- docs: update `onChange` description in README
- docs: update GetStream sponsorship urls
=> chore(bloc): v7.1.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/build.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/ci.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/performance.md, .github/ISSUE_TEMPLATE/refactor.md, .github/ISSUE_TEMPLATE/revert.md, .github/ISSUE_TEMPLATE/style.md, .github/ISSUE_TEMPLATE/test.md
**READY**
NO
- chore: add issue templates
=> chore: add issue templates

.github/workflows/bloc_tools.yaml, packages/bloc_tools/.gitignore, packages/bloc_tools/CHANGELOG.md, packages/bloc_tools/LICENSE, packages/bloc_tools/README.md, packages/bloc_tools/analysis_options.yaml, packages/bloc_tools/bin/bloc.dart, packages/bloc_tools/dart_test.yaml, packages/bloc_tools/example/README.md, packages/bloc_tools/lib/bloc_tools.dart, packages/bloc_tools/lib/src/command_runner.dart, packages/bloc_tools/lib/src/version.dart, packages/bloc_tools/pubspec.yaml, packages/bloc_tools/test/ensure_build_test.dart, packages/bloc_tools/test/src/command_runner_test.dart
**READY**
NO
- feat(bloc_tools): create package:bloc_tools
=> feat(bloc_tools): create package:bloc_tools

.github/workflows/angular_bloc.yaml, .github/workflows/bloc.yaml, .github/workflows/bloc_test.yaml, .github/workflows/bloc_tools.yaml, .github/workflows/flutter_bloc.yaml, .github/workflows/hydrated_bloc.yaml, .github/workflows/replay_bloc.yaml
**READY**
NO
- ci: use pana v0.19.1 (due to https://github.com/dart-lang/pana/issues/941)
=> ci: use pana v0.19.1

extensions/vscode/src/utils/analyze-dependencies.ts
**READY**
NO
- feat(vscode): upgrade to bloc v7.1.0
=> feat(vscode): upgrade to bloc v7.1.0

.gitignore, examples/flutter_firebase_login/android/build.gradle, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/packages/cache/pubspec.yaml, examples/flutter_firebase_login/packages/form_inputs/pubspec.yaml, examples/flutter_firebase_login/pubspec.yaml
READY
NO
Upgraded the versions of the firebase login example
=> Upgrade flutter firebase login example

extensions/vscode/package.json, extensions/vscode/src/code-actions/bloc-code-action-provider.ts, extensions/vscode/src/commands/convert-to.command.ts, extensions/vscode/src/commands/index.ts, extensions/vscode/src/extension.ts, extensions/vscode/src/utils/convert-to.ts, extensions/vscode/src/utils/index.ts
**READY**
NO
- feat(vscode): Convert to Multi Widget Action (closes #2610)
=> feat(vscode): Convert to Multi Widget Action

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v5.8.0
=> chore(vscode): v5.8.0

packages/bloc_tools/README.md
**READY**
NO
- docs(bloc_tools): update README header
=> docs(bloc_tools): update README header

docs/_coverpage.md, docs/az/_coverpage.md, docs/cs/_coverpage.md, docs/de-de/_coverpage.md, docs/es/_coverpage.md, docs/fr/_coverpage.md, docs/jp/_coverpage.md, docs/ko-kr/_coverpage.md, docs/pt-br/_coverpage.md, docs/ru/_coverpage.md, docs/zh-cn/_coverpage.md
**READY**
NO
- docs: update coverpage version to 7.2.0
=> docs: update coverpage version to 7.2.0

packages/flutter_bloc/README.md
**READY**
NO
- docs(flutter_bloc): update usage section in README (closes #2706)
=> docs(flutter_bloc): update usage section in README

CONTRIBUTING.md
**READY**
NO
- docs: update local server snippet in CONTRIBUTING (closes #2715)
=> docs: update local server snippet in CONTRIBUTING

docs/_snippets/flutter_firestore_todos_tutorial/authentication_bloc.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/map_load_todos_to_state.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/map_todos_updated_to_state.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/on_load_todos.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/on_todos_updated.dart.md, docs/_snippets/flutter_firestore_todos_tutorial/todos_bloc.dart.md, docs/cs/flutterfirestoretodostutorial.md, docs/es/flutterfirestoretodostutorial.md, docs/flutterfirestoretodostutorial.md, docs/jp/flutterfirestoretodostutorial.md, docs/pt-br/flutterfirestoretodostutorial.md, docs/ru/flutterfirestoretodostutorial.md, docs/zh-cn/flutterfirestoretodostutorial.md
**READY**
NO
- Migrate `flutter_firestore_todos` tutorial to bloc v8.0.0.
=> docs(flutter_firestore_todos): update tutorial to v8.0.0

docs/flutterfirebaselogintutorial.md
**READY**
NO
- Small fixes to `flutter_firebase_login` tutorial.
=> docs(flutter_firebase_login): minor fixes

.github/workflows/angular_bloc.yaml, .github/workflows/angular_dart_examples.yaml
**READY**
NO
- ci(angular_bloc): use dart 2.12
=> ci(angular_bloc): use dart 2.12

docs/_snippets/flutter_angular_github_search/common/github_search_bloc.dart.md, docs/flutterangulargithubsearch.md
**READY**
NO
- Migrate `github_search` tutorial to bloc v8.0.0.
=> docs(github_search): update to 8.0.0

docs/_snippets/faqs/equatable_yield.dart.md, docs/_snippets/faqs/state_not_updating_bad_3.dart.md, docs/_snippets/faqs/state_not_updating_good_2.dart.md, docs/_snippets/faqs/state_not_updating_good_3.dart.md, docs/faqs.md
**READY**
NO
- Migrate FAQ's answers to v8.0.0.
=> docs(faq): update to 8.0.0

docs/_snippets/architecture/business_logic_component.dart.md
**READY**
NO
- Migrate bloc snippet on architecture to v8.0.0.
=> docs(architecture): update bloc snippet to 8.0.0

docs/_snippets/testing/counter_bloc.dart.md, docs/_snippets/testing/counter_bloc_test_bloc_test.dart.md, docs/testing.md
**READY**
NO
- Migrate testing documentation to v8.0.0.
=> docs(testing): update to 8.0.0

docs/_snippets/recipes_flutter_show_snack_bar/data_bloc.dart.md, docs/recipesfluttershowsnackbar.md
**READY**
YES
- Migrate snack bar recipe snippets to v8.0.0.
=> docs: update snackbar recipe to 8.0.0

docs/_snippets/recipes_flutter_bloc_access/anonymous_route_access/home_page.dart.md, docs/_snippets/recipes_flutter_bloc_access/counter_bloc.dart.md, docs/_snippets/recipes_flutter_bloc_access/generated_route_access/home_page.dart.md, docs/_snippets/recipes_flutter_bloc_access/global_access/counter_page.dart.md, docs/_snippets/recipes_flutter_bloc_access/local_access/counter_page.dart.md, docs/_snippets/recipes_flutter_bloc_access/named_route_access/home_page.dart.md, docs/recipesflutterblocaccess.md
**READY**
NO
- Migrate bloc access recipe to v8.0.0.
=> docs: update bloc access recipe to 8.0.0

docs/es/flutterinfinitelisttutorial.md
=> docs: broken links for spanish tutorial

.github/workflows/angular_bloc.yaml, .github/workflows/angular_dart_examples.yaml, examples/angular_counter/CHANGELOG.md, examples/angular_counter/lib/src/counter_page/counter_page_component.dart, examples/angular_counter/lib/src/counter_page/counter_page_component.html, examples/angular_counter/pubspec.yaml, examples/angular_counter/web/main.dart, examples/github_search/angular_github_search/lib/src/search_form/search_bar/search_bar_component.dart, examples/github_search/angular_github_search/lib/src/search_form/search_body/search_body_component.dart, examples/github_search/angular_github_search/lib/src/search_form/search_body/search_results/search_result_item/search_result_item_component.dart, examples/github_search/angular_github_search/lib/src/search_form/search_body/search_results/search_result_item/search_result_item_component.html, examples/github_search/angular_github_search/lib/src/search_form/search_body/search_results/search_results_component.dart, examples/github_search/angular_github_search/lib/src/search_form/search_form_component.dart, examples/github_search/angular_github_search/lib/src/search_form/search_form_component.html, examples/github_search/angular_github_search/pubspec.yaml, packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/README.md, packages/angular_bloc/example/example.dart, packages/angular_bloc/lib/src/pipes/bloc_pipe.dart, packages/angular_bloc/pubspec.yaml, packages/angular_bloc/test/bloc_pipe_test.dart
**READY**
YES
- feat(angular_bloc)!: v7.0.0 (closes #2750)
- **BREAKING**: refactor: upgrade to `angular ^7.0.0`
- **BREAKING**: refactor: upgrade to `bloc ^7.0.0`
- **BREAKING**: refactor upgrade to null safety (`dart >= 2.12.0`)
=> feat(angular_bloc)!: v7.0.0

packages/hydrated_bloc/example/linux/flutter/generated_plugin_registrant.cc, packages/hydrated_bloc/example/linux/flutter/generated_plugin_registrant.h
**READY**
NO
- chore(hydrated_bloc): update generated_plugin_registrant in example
=> chore(hydrated_bloc): update generated_plugin_registrant in example

examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart
**READY**
NO
- chore(flutter_firebase_login): remove unnecessary state parameter
- closes https://github.com/felangel/bloc/issues/2749
=> chore(flutter_firebase_login): remove unnecessary state parameter

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v7.1.0
- feat: upgrade to `bloc ^7.2.0`
=> chore(angular_bloc): v7.1.0

packages/bloc_test/pubspec.yaml, packages/bloc_test/test/legacy/blocs/debounce_counter_bloc.dart
**READY**
NO
- fix(bloc_test): ignore deprecated member use
=> fix(bloc_test): ignore deprecated member use

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v8.2.0
- feat: upgrade to `bloc ^7.2.0`
=> chore(bloc_test): v8.2.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.3.0
- feat: upgrade to `bloc: ^7.2.0`
=> chore(flutter_bloc): v7.3.0

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v7.1.0
- feat: upgrade to `bloc ^7.2.0`
=> chore(hydrated_bloc): v7.1.0

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.1.0
- feat: upgrade to `bloc ^7.2.0`
=> chore(replay_bloc): v0.1.0

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/snippets/bloc.json, extensions/vscode/snippets/bloc_test.json, extensions/vscode/snippets/flutter_bloc.json, extensions/vscode/src/utils/analyze-dependencies.ts
**READY**
NO
- feat(vscode): v6.0.0
- **BREAKING**: update to bloc ^7.2.0
- update snippets to use `on<Event>` instead of deprecated `mapEventToState`
- feat: add `onevent` snippet to register a new `EventHandler`
- feat: update to latest packages
- bloc -> ^7.2.0
- flutter_bloc -> ^7.3.0
- angular_bloc -> ^7.1.0
- bloc_test -> ^8.2.0
- replay_bloc -> ^0.1.0
- bloc_concurrency -> ^0.1.0
- sealed_flutter_bloc -> ^7.1.0
=> feat(vscode): v6.0.0

examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart, examples/flutter_bloc_with_stream/lib/bloc/ticker_event.dart, examples/flutter_bloc_with_stream/lib/bloc/ticker_state.dart, examples/flutter_bloc_with_stream/lib/main.dart, examples/flutter_bloc_with_stream/pubspec.yaml, examples/flutter_bloc_with_stream/test/bloc/ticker_bloc_test.dart, examples/flutter_bloc_with_stream/test/bloc/ticker_event_test.dart, examples/flutter_bloc_with_stream/test/bloc/ticker_state_test.dart, examples/flutter_bloc_with_stream/test/ticker_page_test.dart
**READY**
NO
- docs(flutter_bloc_with_stream): update to include a complete state
- closes #2768
=> docs(flutter_bloc_with_stream): update to include a complete state

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml, extensions/intellij/intellij_generator_plugin/src/main/resources/liveTemplates/Bloc.xml
**READY**
NO
- chore(intelliJ): v3.0.0
- Support for Bloc v7.2.0 (on<Event> API)
=> chore(intelliJ): v3.0.0

extensions/intellij/intellij_generator_plugin/build.gradle, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/intention_action/BlocWrapWithBlocSelectorIntentionAction.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/intention_action/SnippetType.kt, extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/intention_action/Snippets.kt, extensions/intellij/intellij_generator_plugin/src/main/resources/META-INF/plugin.xml, extensions/intellij/intellij_generator_plugin/src/main/resources/intentionDescriptions/BlocWrapWithBlocSelectorIntentionAction/after.java.template, extensions/intellij/intellij_generator_plugin/src/main/resources/intentionDescriptions/BlocWrapWithBlocSelectorIntentionAction/before.java.template, extensions/intellij/intellij_generator_plugin/src/main/resources/intentionDescriptions/BlocWrapWithBlocSelectorIntentionAction/description.html
**READY**
NO
- feat(intellij): Wrap with BlocSelector (closes #2786)
=> feat(intellij): Wrap with BlocSelector

packages/bloc/CHANGELOG.md, packages/bloc/lib/src/bloc.dart, packages/bloc/pubspec.yaml, packages/bloc/test/bloc_event_transformer_test.dart
**READY**
NO
- fix(bloc): on<E extend Event> should have EventTransformer<E> (closes #2794)
=> fix(bloc): on<E extend Event> should have EventTransformer<E>

.github/workflows/bloc_concurrency.yaml, packages/bloc_concurrency/test/src/concurrent_test.dart, packages/bloc_concurrency/test/src/droppable_test.dart, packages/bloc_concurrency/test/src/helpers.dart, packages/bloc_concurrency/test/src/restartable_test.dart, packages/bloc_concurrency/test/src/sequential_test.dart
**READY**
NO
- refactor(bloc_concurrency): use classes for events in tests
=> refactor(bloc_concurrency): use classes for events in tests

.github/workflows/angular_bloc.yaml, .github/workflows/bloc.yaml, .github/workflows/bloc_concurrency.yaml, .github/workflows/bloc_test.yaml, .github/workflows/bloc_tools.yaml, .github/workflows/flutter_bloc.yaml, .github/workflows/hydrated_bloc.yaml, .github/workflows/replay_bloc.yaml
**READY**
NO
- ci: update very_good_coverage and pana
- very_good_coverage -> 1.2.0
- pana -> latest
=> ci: update very_good_coverage and pana

docs/pt-br/migration.md
**READY**
NO
Update migration guide by adding info related to v7.2.0.
=> docs(pt-br): update migration guide by adding v7.2.0 info

README.md
**READY**
NO
- docs: add bloc_test and bloc_concurrency doc links to README
=> docs: add bloc_test and bloc_concurrency doc links to README

docs/migration.md
**READY**
NO
- docs(migration): describe how to retain legacy behavior via new API (closes #2790)
=> docs(migration): describe how to retain legacy behavior via new API

examples/flutter_infinite_list/ios/Flutter/AppFrameworkInfo.plist, examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart, examples/flutter_infinite_list/pubspec.yaml, examples/flutter_infinite_list/test/posts/bloc/post_bloc_test.dart, examples/flutter_infinite_list/test/posts/view/posts_page_test.dart
**READY**
NO
- fix(flutter_infinite_list): apply throttleDroppable event transformer (closes #2800)
=> fix(flutter_infinite_list): apply throttleDroppable event transformer

.github/DOCS_ISSUE_TEMPLATE.md, docs/pt-br/blocvscodeextension.md, docs/pt-br/gettingstarted.md
**READY**
NO
Update docs translations related to issue #1196:
- getting started (900d2c2)
- vscode extension (f2f0dca)
=> docs(pt-br): getting started and vscode

packages/flutter_bloc/lib/flutter_bloc.dart
**READY**
NO
- docs(flutter_bloc): add inline docs to library
=> docs(flutter_bloc): add inline docs to library

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml, packages/flutter_bloc/test/bloc_provider_test.dart
**READY**
YES
- **BREAKING**: feat: upgrade to `bloc v8.0.0-dev.2`
=> feat(flutter_bloc)!: v8.0.0-dev.1

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v8.4.0
- feat: upgrade to `mocktail ^0.2.0`
=> chore(bloc_test): v8.4.0

examples/flutter_bloc_with_stream/pubspec.yaml, examples/flutter_bloc_with_stream/test/ticker_page_test.dart, examples/flutter_complex_list/pubspec.yaml, examples/flutter_counter/pubspec.yaml, examples/flutter_dynamic_form/pubspec.yaml, examples/flutter_dynamic_form/test/new_car/view/new_car_page_test.dart, examples/flutter_firebase_login/packages/authentication_repository/pubspec.yaml, examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart, examples/flutter_firebase_login/pubspec.yaml, examples/flutter_firebase_login/test/app/view/app_test.dart, examples/flutter_firebase_login/test/home/view/home_page_test.dart, examples/flutter_firebase_login/test/login/view/login_form_test.dart, examples/flutter_firebase_login/test/sign_up/view/sign_up_form_test.dart, examples/flutter_infinite_list/pubspec.yaml, examples/flutter_infinite_list/test/posts/view/posts_list_test.dart, examples/flutter_login/pubspec.yaml, examples/flutter_login/test/login/view/login_form_test.dart, examples/flutter_shopping_cart/pubspec.yaml, examples/flutter_shopping_cart/test/cart/view/cart_page_test.dart, examples/flutter_shopping_cart/test/catalog/view/catalog_page_test.dart, examples/flutter_shopping_cart/test/helper.dart, examples/flutter_timer/pubspec.yaml, examples/flutter_timer/test/timer/view/timer_page_test.dart, examples/flutter_weather/packages/meta_weather_api/pubspec.yaml, examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart, examples/flutter_weather/packages/weather_repository/pubspec.yaml, examples/flutter_weather/pubspec.yaml, examples/flutter_weather/test/app_test.dart, examples/flutter_weather/test/settings/view/settings_page_test.dart, examples/flutter_weather/test/weather/view/weather_page_test.dart
**READY**
NO
- chore(examples): upgrade to mocktail ^0.2.0
=> chore(examples): upgrade to mocktail ^0.2.0

packages/bloc/CHANGELOG.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.0.0-dev.4
- **BREAKING**: feat: improve error handling/reporting
- `BlocUnhandledErrorException` is removed
- Uncaught exceptions are always reported to `onError` and rethrown
- `addError` reports error to `onError` but does not propagate as an uncaught exception
=> chore(bloc): v8.0.0-dev.4

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.0.0-dev.4
=> chore(bloc_test): v9.0.0-dev.4

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/lib/src/hydrated_bloc.dart, packages/hydrated_bloc/pubspec.yaml, packages/hydrated_bloc/test/e2e_test.dart, packages/hydrated_bloc/test/hydrated_bloc_test.dart, packages/hydrated_bloc/test/hydrated_cubit_test.dart
**READY**
NO
- chore(hydrated_bloc): v8.0.0-dev.3
=> chore(hydrated_bloc): v8.0.0-dev.3

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.3.2
=> chore(flutter_bloc): v7.3.2

packages/bloc_test/lib/src/bloc_test.dart, packages/bloc_test/pubspec.yaml, packages/bloc_test/test/bloc_bloc_test_test.dart, packages/bloc_test/test/legacy/bloc_bloc_test_test.dart
**READY**
NO
- feat(bloc_test): prettier diffing
- closes #1783
=> feat(bloc_test): prettier diffing

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v8.5.0
- feat: prettier diffing when using `blocTest` and `expect` does not match emitted states ([#1783](https://github.com/felangel/bloc/issues/1783))
=> chore(bloc_test): v8.5.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v7.3.3
=> chore(flutter_bloc): v7.3.3

extensions/vscode/src/commands/new-bloc.command.ts
**READY**
NO
- refactor(vscode): specify explicit types for Promises
=> refactor(vscode): specify explicit types for Promises

extensions/vscode/src/utils/analyze-dependencies.ts
**READY**
NO
- feat(vscode): update latest package versions
- bloc -> ^7.2.1
- flutter_bloc -> ^7.3.3
- bloc_test -> ^8.5.0
=> feat(vscode): update latest package versions

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.1.0
=> chore(vscode): v6.1.0

docs/_snippets/core_concepts/simple_bloc_observer_on_change_usage.dart.md, docs/_snippets/core_concepts/simple_bloc_observer_on_transition_usage.dart.md, packages/bloc/CHANGELOG.md, packages/bloc/README.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.0.0-dev.5
=> chore(bloc): v8.0.0-dev.5

examples/angular_counter/web/main.dart, packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/README.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v8.0.0-dev.3
=> chore(angular_bloc): v8.0.0-dev.3

packages/bloc_test/CHANGELOG.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.0.0-dev.5
=> chore(bloc_test): v9.0.0-dev.5

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/analysis_options.yaml, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.2.0-dev.2
=> chore(bloc_concurrency): v0.2.0-dev.2

packages/replay_bloc/CHANGELOG.md, packages/replay_bloc/pubspec.yaml
**READY**
NO
- chore(replay_bloc): v0.2.0-dev.3
=> chore(replay_bloc): v0.2.0-dev.3

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.0.0-dev.3
=> chore(flutter_bloc): v8.0.0-dev.3

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/README.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v8.0.0-dev.4
=> chore(hydrated_bloc): v8.0.0-dev.4

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/README.md, packages/hydrated_bloc/lib/src/hydrated_storage.dart, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v8.0.0-dev.5
=> chore(hydrated_bloc): v8.0.0-dev.5

packages/bloc/lib/src/bloc.dart
**READY**
NO
- refactor(bloc): use const zone token
=> refactor(bloc): use const zone token

packages/hydrated_bloc/lib/src/hydrated_bloc.dart
**READY**
NO
- refactor(hydrated_bloc): use const zone token
=> refactor(hydrated_bloc): use const zone token

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/utils/analyze-dependencies.ts, extensions/vscode/src/utils/get-latest-package-version.ts, extensions/vscode/src/utils/index.ts
**READY**
NO
- feat(vscode): query latest package versions from pub.dev
=> feat(vscode): query latest package versions from pub.dev

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
NO
- chore(vscode): v6.2.0
=> chore(vscode): v6.2.0

packages/bloc/CHANGELOG.md, packages/bloc/README.md, packages/bloc/pubspec.yaml
**READY**
NO
- chore(bloc): v8.0.0
=> chore(bloc): v8.0.0

packages/angular_bloc/CHANGELOG.md, packages/angular_bloc/README.md, packages/angular_bloc/pubspec.yaml
**READY**
NO
- chore(angular_bloc): v8.0.0
=> chore(angular_bloc): v8.0.0

packages/bloc_concurrency/CHANGELOG.md, packages/bloc_concurrency/README.md, packages/bloc_concurrency/pubspec.yaml
**READY**
NO
- chore(bloc_concurrency): v0.2.0
=> chore(bloc_concurrency): v0.2.0

packages/hydrated_bloc/CHANGELOG.md, packages/hydrated_bloc/README.md, packages/hydrated_bloc/pubspec.yaml
**READY**
NO
- chore(hydrated_bloc): v8.0.0
=> chore(hydrated_bloc): v8.0.0

packages/bloc_test/CHANGELOG.md, packages/bloc_test/README.md, packages/bloc_test/pubspec.yaml
**READY**
NO
- chore(bloc_test): v9.0.0
=> chore(bloc_test): v9.0.0

packages/flutter_bloc/CHANGELOG.md, packages/flutter_bloc/README.md, packages/flutter_bloc/pubspec.yaml
**READY**
NO
- chore(flutter_bloc): v8.0.0
=> chore(flutter_bloc): v8.0.0

docs/_coverpage.md, docs/az/_coverpage.md, docs/cs/_coverpage.md, docs/de-de/_coverpage.md, docs/es/_coverpage.md, docs/fr/_coverpage.md, docs/jp/_coverpage.md, docs/ko-kr/_coverpage.md, docs/pt-br/_coverpage.md, docs/ru/_coverpage.md, docs/zh-cn/_coverpage.md
**READY**
NO
- docs(coverpage): update to v8.0.0
=> docs(coverpage): update to v8.0.0

docs/_snippets/getting_started/angular_bloc_pubspec.yaml.md, docs/_snippets/getting_started/bloc_pubspec.yaml.md, docs/_snippets/getting_started/flutter_bloc_pubspec.yaml.md
**READY**
NO
- docs(getting_started): update versions
=> docs(getting_started): update versions
